/*
 * Copyright (c) 2015, Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * [X_MACRO](https://en.wikipedia.org/wiki/X_Macro) used to define a log_module.
 * DEFINE_LOGGER_MODULE(<module id>, <module name>, <enable_debug>)
 */

DEFINE_LOGGER_MODULE(LOG_MODULE_MAIN, "MAIN", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_LOG, "LOG", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_OS, "OS", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_FG, "FG_S", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_BS, "BATT_S", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_UTIL, "UTIL", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_USB, "USB", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_UI_SVC, "UI_SVC", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_LED, "LED", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_VIBR, "DRV2605", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_IPC, "IPC_UA", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_PHY_SS, "PHY_SS", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_BMI160, "BMI160", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_OPEN_CORE, "OPEN_CORE", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_SS_SVC, "SS_SVC", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_SC_IPC, "SC_IPC", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_BP, "BAT_P", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_PS, "PWR_SUP", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_CH, "CHGR", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_BLE, "BLE", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_DRV, "DRV", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_CUNIT, "CUNIT", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_CFW, "CFW", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_GPIO_SVC, "GPIO_SVC", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_PWRBTN, "PWRBTN", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_NFC, "NFC", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_IQ, "IQ", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_BME280, "BME280", 0)
DEFINE_LOGGER_MODULE(LOG_MODULE_RECOVERY, "RECOVERY", 0)
