//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/replay/AbstractHWTestSensor.java
//

#ifndef _AbstractHWTestSensor_H_
#define _AbstractHWTestSensor_H_

@class SensorType;

#import "JB.h"
#import "AbstractHWSensor.h"

@interface AbstractHWTestSensor : AbstractHWSensor {
 @public
  SensorType *m_sensorType_;
}

- (instancetype)initWithLong:(long64)sampleIntervalInMillis
          withSensorType:(SensorType *)sensorType;

- (boolean)startSensor;

- (boolean)stopSensor;

- (boolean)pauseSensor;

- (boolean)resumeSensor;

- (SensorType *)getSensorType;

- (void)changeSampleRateWithLong:(long64)intervalInMillis;

- (void)copyAllFieldsTo:(AbstractHWTestSensor *)other;

@end

FOUNDATION_EXPORT BOOL AbstractHWTestSensor_initialized;
J2OBJC_STATIC_INIT(AbstractHWTestSensor)

//J2OBJC_FIELD_SETTER(AbstractHWTestSensor, m_sensorType_, SensorType *)

FOUNDATION_EXPORT NSString *AbstractHWTestSensor_TAG_;
J2OBJC_STATIC_FIELD_GETTER(AbstractHWTestSensor, TAG_, NSString *)

typedef AbstractHWTestSensor ComIntelWearablePlatformTimeiqSensorsReplayAbstractHWTestSensor;

#endif // _AbstractHWTestSensor_H_
