//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/utils/apiUsageAudit/ApiUsageDebug.java
//

#ifndef _ApiUsageDebug_H_
#define _ApiUsageDebug_H_

@class Result;
@class ResultData;
@protocol IAuditManager;
@protocol ITSOTimeUtil;

#import "JB.h"
#import "ApiUsageUtil.h"

/**
 @brief Created by stzour on 11/11/2015.
 */
@interface ApiUsageDebug : ApiUsageUtil {
 @public
  int usageCounter_;
}

- (instancetype)init;

- (instancetype)initWithITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil
                   withIAuditManager:(id<IAuditManager>)auditManager;

- (void)sendAuditWithResult:(Result *)result;

- (void)sendAuditWithResultData:(ResultData *)resultData;

- (int)getUsageCounter;

- (void)initUsageCounter OBJC_METHOD_FAMILY_NONE;

- (void)copyAllFieldsTo:(ApiUsageDebug *)other;

@end

__attribute__((always_inline)) inline void ApiUsageDebug_init() {}

typedef ApiUsageDebug ComIntelWearablePlatformTimeiqCommonUtilsApiUsageAuditApiUsageDebug;

#endif // _ApiUsageDebug_H_
