//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/routeprovider/request/ARequest.java
//

#ifndef _ARequest_H_
#define _ARequest_H_

#import "JB.h"

@interface ARequest : NSObject {
 @public
  NSString *clientTimestamp_;
}

/**
 @brief Constructor
 */
- (instancetype)init;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (NSString *)description;

- (NSString *)getClientTimestamp;

- (void)setClientTimestampWithNSString:(NSString *)clientTimestamp;

- (void)copyAllFieldsTo:(ARequest *)other;

@end

__attribute__((always_inline)) inline void ARequest_init() {}

//J2OBJC_FIELD_SETTER(ARequest, clientTimestamp_, NSString *)

typedef ARequest ComIntelWearablePlatformTimeiqRouteproviderRequestARequest;

#endif // _ARequest_H_
