//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/abstracts/ATSOSemanticPlace.java
//

#ifndef _ATSOSemanticPlace_H_
#define _ATSOSemanticPlace_H_

@class Coord;
@class PlaceID;
@class SemanticKey;
@class SemanticTag;
#import "JBHashtable.h"

#import "JB.h"
#import "ATSOPlace.h"
#import "ITSOSemanticPlace.h"

@interface ATSOSemanticPlace : ATSOPlace < ITSOSemanticPlace > {
 @public
  NSString *placeDescription_;
  NSString *normalizedPlaceDescription_;
  boolean isNormalizedDescriptionSet_;
  SemanticKey *semanticKey_;
}

/**
 @brief Constructor
 */
- (instancetype)init;

/**
 @brief Copy constructor
 @param other
 */
- (instancetype)initWithATSOSemanticPlace:(ATSOSemanticPlace *)other;

/**
 @brief Constructor
 @param userId
 @param center
 @param address
 @param placeDescription
 @param semanticKey
 */
- (instancetype)initWithNSString:(NSString *)userId
                       withCoord:(Coord *)center
                    withNSString:(NSString *)address
                    withNSString:(NSString *)placeDescription
                 withSemanticKey:(SemanticKey *)semanticKey;

/**
 @brief Constructor
 @param objectId
 @param userId
 @param center
 @param address
 @param placeDescription
 @param semanticKey
 */
- (instancetype)initWithNSString:(NSString *)objectId
                    withNSString:(NSString *)userId
                       withCoord:(Coord *)center
                    withNSString:(NSString *)address
                    withNSString:(NSString *)placeDescription
                 withSemanticKey:(SemanticKey *)semanticKey;

/**
 @brief Constructor
 @param objectId
 @param userId
 @param modificationTimeInNano
 @param center
 @param address
 @param placeDescription
 @param semanticKey
 */
- (instancetype)initWithNSString:(NSString *)objectId
                    withNSString:(NSString *)userId
                        withLong:(long64)modificationTimeInNano
                       withCoord:(Coord *)center
                    withNSString:(NSString *)address
                    withNSString:(NSString *)placeDescription
                 withSemanticKey:(SemanticKey *)semanticKey;

- (void)validate;

- (void)setMembersAndValidateWithNSString:(NSString *)placeDescription
                          withSemanticKey:(SemanticKey *)semanticKey;

- (boolean)isHome;

- (boolean)isWork;

- (SemanticKey *)getSemanticKey;

- (void)setSemanticKeyWithSemanticKey:(SemanticKey *)semanticKey;

- (NSString *)getPlaceDescription;

- (void)setPlaceDescriptionWithNSString:(NSString *)placeDescription;

- (NSString *)getNormalizedPlaceDescription;

- (PlaceID *)getPlaceID;

- (void)setNormalizedPlaceDescriptionWithNSString:(NSString *)normalizedPlaceDescription;

- (NSString *)clearStringWithNSString:(NSString *)string;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (SemanticKey *)semanticKeyFallbackCreationWithNSString:(NSString *)normalizedDescription
                                     withSemanticTag:(SemanticTag *)semanticTag;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(ATSOSemanticPlace *)other;

@end

__attribute__((always_inline)) inline void ATSOSemanticPlace_init() {}

//J2OBJC_FIELD_SETTER(ATSOSemanticPlace, placeDescription_, NSString *)
//J2OBJC_FIELD_SETTER(ATSOSemanticPlace, normalizedPlaceDescription_, NSString *)
//J2OBJC_FIELD_SETTER(ATSOSemanticPlace, semanticKey_, SemanticKey *)

FOUNDATION_EXPORT NSString *ATSOSemanticPlace_PLACE_DESCRIPTION_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ATSOSemanticPlace, PLACE_DESCRIPTION_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *ATSOSemanticPlace_SEMANTIC_KEY_;
J2OBJC_STATIC_FIELD_GETTER(ATSOSemanticPlace, SEMANTIC_KEY_, NSString *)

FOUNDATION_EXPORT NSString *ATSOSemanticPlace_BC_SEMANTIC_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ATSOSemanticPlace, BC_SEMANTIC_TAG_, NSString *)

typedef ATSOSemanticPlace ComIntelWearablePlatformTimeiqDbobjectsAbstractsATSOSemanticPlace;

#endif // _ATSOSemanticPlace_H_
