//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/utils/retry/BackoffAlgorithmHelperBase.java
//

#ifndef _BackoffAlgorithmHelperBase_H_
#define _BackoffAlgorithmHelperBase_H_

@class BackoffAlgorithmType;

#import "JB.h"
#import "IBackoffAlgorithm.h"

/**
 @brief Created by mleib on 08/04/2015.
 */
@interface BackoffAlgorithmHelperBase : NSObject < IBackoffAlgorithm > {
 @public
  BackoffAlgorithmType *BACKOFF_ALGORITHM_TYPE_;
  long64 m_currentInterval_;
  long64 STARTING_INTERVAL_;
}

- (instancetype)initWithBackoffAlgorithmType:(BackoffAlgorithmType *)backoffAlgorithmType
                                        withLong:(long64)startingInterval;

- (long64)getNextInterval;

- (void)nextInterval;

- (void)resetInterval;

- (BackoffAlgorithmType *)getBackoffAlgorithmType;

- (long64)getCurrentInterval;

- (void)copyAllFieldsTo:(BackoffAlgorithmHelperBase *)other;

@end

FOUNDATION_EXPORT BOOL BackoffAlgorithmHelperBase_initialized;
J2OBJC_STATIC_INIT(BackoffAlgorithmHelperBase)

//J2OBJC_FIELD_SETTER(BackoffAlgorithmHelperBase, BACKOFF_ALGORITHM_TYPE_, BackoffAlgorithmType *)

FOUNDATION_EXPORT NSString *BackoffAlgorithmHelperBase_TAG_;
J2OBJC_STATIC_FIELD_GETTER(BackoffAlgorithmHelperBase, TAG_, NSString *)

typedef BackoffAlgorithmHelperBase ComIntelWearablePlatformTimeiqCommonUtilsRetryBackoffAlgorithmHelperBase;

#endif // _BackoffAlgorithmHelperBase_H_
