//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/calendar/CalendarOperationException.java
//

#ifndef _CalendarOperationException_H_
#define _CalendarOperationException_H_

#import "JB.h"
#import "NSException+JavaAPI.h"

/**
 @brief Created by eskoran on 02/11/2015.
 */
@interface CalendarOperationException : Exception {
}

- (instancetype)initWithException:(Exception *)e;

@end

__attribute__((always_inline)) inline void CalendarOperationException_init() {}

typedef CalendarOperationException ComIntelWearablePlatformTimeiqCommonCalendarCalendarOperationException;

#endif // _CalendarOperationException_H_
