//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/calendar/CalendarDetailsProviderModule.java
//

#ifndef _CalendarDetailsProviderModule_H_
#define _CalendarDetailsProviderModule_H_

@class Result;
@class ResultData;
@protocol ITSOCalendarsManager;
@protocol IUserPrefs;
#import "JBArrayList.h"

#import "JB.h"
#import "ICalendarDetailsProviderModule.h"

/**
 @brief Created by eskoran on 29/10/2015.
 */
@interface CalendarDetailsProviderModule : NSObject < ICalendarDetailsProviderModule > {
 @public
  id<IUserPrefs> userPrefs_;
  id<ITSOCalendarsManager> calendarsManager_;
}

- (instancetype)init;

- (instancetype)initWithIUserPrefs:(id<IUserPrefs>)userPrefs
          withITSOCalendarsManager:(id<ITSOCalendarsManager>)calendarsManager;

- (ResultData *)getAvailableCalendars;

- (ResultData *)getWriteCalendar;

- (Result *)setWriteCalendarWithNSString:(NSString *)calendarId;

- (ResultData *)getReadCalendars;

- (Result *)setReadCalendarsWithJavaUtilList:(ArrayList*)calendarIds;

- (void)copyAllFieldsTo:(CalendarDetailsProviderModule *)other;

@end

__attribute__((always_inline)) inline void CalendarDetailsProviderModule_init() {}

//J2OBJC_FIELD_SETTER(CalendarDetailsProviderModule, userPrefs_, id<IUserPrefs>)
//J2OBJC_FIELD_SETTER(CalendarDetailsProviderModule, calendarsManager_, id<ITSOCalendarsManager>)

typedef CalendarDetailsProviderModule ComIntelWearablePlatformTimeiqCommonCalendarCalendarDetailsProviderModule;

#endif // _CalendarDetailsProviderModule_H_
