//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/core/initiation/CommonDaoInitializerSQL.java
//

#ifndef _CommonDaoInitializerSQL_H_
#define _CommonDaoInitializerSQL_H_

#import "JBClass.h"
#import "JBArrayList.h"
@protocol IDBSourceDefinition;

#import "JB.h"

/**
 @brief <p><b>This class is intended to initialize DAO's for Android type app's</b></p> <p/> Class will initialize All Common DAO objects for using underline SQL light implementation.
 Created by aeirew on 01/09/2015.
 */
@interface CommonDaoInitializerSQL : NSObject {
 @public
  ArrayList *m_listeners_;
}

- (instancetype)initWithNSString:(NSString *)dbName;

+ (void)init__WithNSString:(NSString *)dbName OBJC_METHOD_FAMILY_NONE;

+ (void)dispose;

- (void)generateGenericDaos;

- (void)createGenericDaoWithClass :(Class )deserializeClassName;

- (void)createSyncGenericDaoWithClass :(Class )deserializeClassName;

- (void)copyAllFieldsTo:(CommonDaoInitializerSQL *)other;

@end

__attribute__((always_inline)) inline void CommonDaoInitializerSQL_init() {}

//J2OBJC_FIELD_SETTER(CommonDaoInitializerSQL, m_listeners_, ArrayList *)

FOUNDATION_EXPORT id<IDBSourceDefinition> CommonDaoInitializerSQL_s_dbSourceDef_;
J2OBJC_STATIC_FIELD_GETTER(CommonDaoInitializerSQL, s_dbSourceDef_, id<IDBSourceDefinition>)
//J2OBJC_STATIC_FIELD_SETTER(CommonDaoInitializerSQL, s_dbSourceDef_, id<IDBSourceDefinition>)

FOUNDATION_EXPORT CommonDaoInitializerSQL *CommonDaoInitializerSQL_s_instance_;
J2OBJC_STATIC_FIELD_GETTER(CommonDaoInitializerSQL, s_instance_, CommonDaoInitializerSQL *)
//J2OBJC_STATIC_FIELD_SETTER(CommonDaoInitializerSQL, s_instance_, CommonDaoInitializerSQL *)

typedef CommonDaoInitializerSQL ComIntelWearablePlatformTimeiqCoreInitiationCommonDaoInitializerSQL;

#endif // _CommonDaoInitializerSQL_H_
