//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/DBResponse.java
//

#ifndef _DBResponse_H_
#define _DBResponse_H_

@class RetCode;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"

@interface DBResponse : NSObject < IMappable > {
 @public
  RetCode *retCode_;
  NSString *message_;
}

- (void)setRetCodeWithRetCode:(RetCode *)retCode;

- (void)setMessageWithNSString:(NSString *)message;

- (instancetype)init;

- (instancetype)initWithRetCode:(RetCode *)retCode;

- (instancetype)initWithRetCode:(RetCode *)retCode
                       withNSString:(NSString *)objectId;

- (instancetype)initWithRetCode:(RetCode *)retCode
                       withNSString:(NSString *)objectId
                       withNSString:(NSString *)errorMessage;

- (RetCode *)getRetCode;

- (NSString *)getMessage;

- (NSString *)getMessageByRetCodeWithRetCode:(RetCode *)retCode;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (void)copyAllFieldsTo:(DBResponse *)other;

@end

__attribute__((always_inline)) inline void DBResponse_init() {}

//J2OBJC_FIELD_SETTER(DBResponse, retCode_, RetCode *)
//J2OBJC_FIELD_SETTER(DBResponse, message_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_CODE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_CODE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_MESSAGE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, MESSAGE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_SUCCESS_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_SUCCESS_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_FAILED_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_FAILED_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_ALREADY_EXISTS_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_ALREADY_EXISTS_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_NO_SUCH_ELEMENT_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_NO_SUCH_ELEMENT_, NSString *)

FOUNDATION_EXPORT NSString *DBResponse_RET_MALFORMED_JSON_;
J2OBJC_STATIC_FIELD_GETTER(DBResponse, RET_MALFORMED_JSON_, NSString *)

typedef DBResponse ComIntelWearablePlatformTimeiqDbobjectsDBResponse;

#endif // _DBResponse_H_
