//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/devicestatemanager/data/DeviceStateData.java
//

#ifndef _DeviceStateData_H_
#define _DeviceStateData_H_

#import "JB.h"

/**
 @brief Created by eleuchte on 02/08/2015.
 */
@interface DeviceStateData : NSObject {
 @public
  id m_data_;
  long64 m_timeStamp_;
}

- (instancetype)initWithId:(id)m_data
                  withLong:(long64)m_timeStamp;

- (instancetype)initWithDeviceStateData:(DeviceStateData *)other;

- (id)getData;

- (long64)getTimeStamp;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(DeviceStateData *)other;

@end

__attribute__((always_inline)) inline void DeviceStateData_init() {}

//J2OBJC_FIELD_SETTER(DeviceStateData, m_data_, id)

typedef DeviceStateData ComIntelWearablePlatformTimeiqCommonDevicestatemanagerDataDeviceStateData;

#endif // _DeviceStateData_H_
