//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/geometry/Edge.java
//

#ifndef _Edge_H_
#define _Edge_H_

@class XY;

#import "JB.h"

@interface Edge : NSObject {
 @public
  XY *p1_;
  XY *p2_;
}

- (instancetype)initWithXY:(XY *)p1
                    withXY:(XY *)p2;

- (XY *)getP1;

- (XY *)getP2;

+ (boolean)isPointInsideEdgeWithEdge:(Edge *)e
                               withXY:(XY *)ref
                               withXY:(XY *)p;

- (XY *)computeIntersectionWithXY:(XY *)s
                           withXY:(XY *)p;

- (NSString *)description;

- (void)copyAllFieldsTo:(Edge *)other;

@end

__attribute__((always_inline)) inline void Edge_init() {}

//J2OBJC_FIELD_SETTER(Edge, p1_, XY *)
//J2OBJC_FIELD_SETTER(Edge, p2_, XY *)

typedef Edge ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleGeometryEdge;

#endif // _Edge_H_
