//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/routeprovider/request/ETARequest.java
//

#ifndef _ETARequest_H_
#define _ETARequest_H_

#import "NSNumber+JavaAPI.h"
@class MotType;
@class TSOCoordinate;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"
#import "ARequest.h"

@interface ETARequest : ARequest < IMappable > {
 @public
  TSOCoordinate *origin_;
  TSOCoordinate *destination_;
  NSString *departureTimeMS_;
  MotType *motType_;
  JBBoolean *prioritize_;
}

- (void)init__WithTSOCoordinate:(TSOCoordinate *)origin
              withTSOCoordinate:(TSOCoordinate *)destination
                   withNSString:(NSString *)departureTimeMS
                withMotType:(MotType *)motType
            withJBBoolean:(JBBoolean *)prioritize OBJC_METHOD_FAMILY_NONE;

- (TSOCoordinate *)getOrigin;

- (void)setOriginWithTSOCoordinate:(TSOCoordinate *)origin;

- (TSOCoordinate *)getDestination;

- (void)setDestinationWithTSOCoordinate:(TSOCoordinate *)destination;

- (JBBoolean *)isPrioritize;

- (void)setPrioritizeWithJBBoolean:(JBBoolean *)prioritize;

- (NSString *)getDepartureTimeMS;

- (void)setDepartureTimeMSWithNSString:(NSString *)departureTimeMS;

- (MotType *)getMotType;

- (void)setMotTypeWithMotType:(MotType *)motType;

- (JBBoolean *)getPrioritize;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (NSString *)description;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (instancetype)init;

- (void)copyAllFieldsTo:(ETARequest *)other;

@end

__attribute__((always_inline)) inline void ETARequest_init() {}

//J2OBJC_FIELD_SETTER(ETARequest, origin_, TSOCoordinate *)
//J2OBJC_FIELD_SETTER(ETARequest, destination_, TSOCoordinate *)
//J2OBJC_FIELD_SETTER(ETARequest, departureTimeMS_, NSString *)
//J2OBJC_FIELD_SETTER(ETARequest, motType_, MotType *)
//J2OBJC_FIELD_SETTER(ETARequest, prioritize_, JBBoolean *)

typedef ETARequest ComIntelWearablePlatformTimeiqRouteproviderRequestETARequest;

#endif // _ETARequest_H_
