//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/extended_events/ExtendedEventsManager.java
//

#ifndef _ExtendedEventsManager_H_
#define _ExtendedEventsManager_H_

@class AReminderTemplate;
@class BeEvent;
@class BeEventTemplate;
@class ExtendedEventInstance;
@class ExtendedEventTemplate;
#import "JBArrayList.h"
@class eDayOfReminder;
@protocol IEventsEngineModule;
@protocol IExtendedEventsHandler;
@protocol IExternalMessageEngine;
@protocol IMessage;
@protocol IReminder;
@protocol IRemindersManagerModule;
@protocol ITSOLogger;
#import "JBArrayList.h"

#import "JB.h"
#import "IMessageListener.h"

#define ExtendedEventsManager_ADD_TO_CALENDAR YES

/**
 @brief Created by smoradof on 7/29/2015.
 */
@interface ExtendedEventsManager : NSObject < IMessageListener > {
 @public
  id<IEventsEngineModule> mEventsEngine_;
  id<IRemindersManagerModule> mRemindersManager_;
  ArrayList *mInstances_;
  ArrayList *mTemplates_;
  id<IExtendedEventsHandler> mTsoEventsHandler_;
  id<ITSOLogger> mLogger_;
  id<IExternalMessageEngine> messageHandler_;
}

+ (ExtendedEventsManager *)getInstance;

- (void)registerTsoEventsHandlerWithIExtendedEventsHandler:(id<IExtendedEventsHandler>)tsoEventsHandler;

- (instancetype)init;

- (boolean)addAndRegisterWithExtendedEventTemplate:(ExtendedEventTemplate *)extendedEventTemplate;

- (ExtendedEventInstance *)createAndAddInstanceWithExtendedEventTemplate:(ExtendedEventTemplate *)extendedEventTemplate;

- (boolean)addOrUpdateTemplateWithExtendedEventTemplate:(ExtendedEventTemplate *)extendedEventTemplate;

- (boolean)registerInstanceWithExtendedEventInstance:(ExtendedEventInstance *)instance;

- (id<IReminder>)createReminderWithAReminderTemplate:(AReminderTemplate *)reminderGenerator
                                            withLong:(long64)arrivalTime
                                        withNSString:(NSString *)instanceId;

- (long64)getReminderTimeWithLong:(long64)arrivalTime
          withEDayOfReminderEnum:(eDayOfReminder *)dayOfReminder
                        withLong:(long64)timeOfDay;

- (BeEvent *)createBeEventWithBeEventTemplate:(BeEventTemplate *)beEventTemplate;

- (boolean)editInstanceWithNSString:(NSString *)instanceIdToEdit
           withExtendedEventTemplate:(ExtendedEventTemplate *)newTemplate
                         withBoolean:(boolean)editAllRecurring;

- (boolean)deleteInstanceWithNSString:(NSString *)instanceIdToEdit
                           withBoolean:(boolean)deleteAllRecurring;

- (void)deleteTemplateWithExtendedEventTemplate:(ExtendedEventTemplate *)templateToDelete;

- (ExtendedEventTemplate *)getTemplateWithNSString:(NSString *)templateId;

- (ExtendedEventInstance *)getInstanceWithNSString:(NSString *)instanceId;

- (ArrayList *)getTemplates;

- (int)getNumTemplates;

- (ArrayList *)getInstances;

- (void)onReceiveWithIMessage:(id<IMessage>)message;

- (void)onEventTriggeredWithIMessage:(id<IMessage>)message;

- (ExtendedEventInstance *)findInstanceByEventIdWithNSString:(NSString *)eventId;

- (void)onReminderWithIMessage:(id<IMessage>)message;

- (void)printTemplatesToLogWithBoolean:(boolean)error
                          withNSString:(NSString *)tag
                          withNSString:(NSString *)preText;

- (ExtendedEventTemplate *)getTemplateWithInt:(int)index;

- (ArrayList*)getTemplateDescriptionList;

- (void)dispose;

- (void)copyAllFieldsTo:(ExtendedEventsManager *)other;

@end

FOUNDATION_EXPORT BOOL ExtendedEventsManager_initialized;
J2OBJC_STATIC_INIT(ExtendedEventsManager)

//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mEventsEngine_, id<IEventsEngineModule>)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mRemindersManager_, id<IRemindersManagerModule>)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mInstances_, ArrayList *)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mTemplates_, ArrayList *)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mTsoEventsHandler_, id<IExtendedEventsHandler>)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, mLogger_, id<ITSOLogger>)
//J2OBJC_FIELD_SETTER(ExtendedEventsManager, messageHandler_, id<IExternalMessageEngine>)

J2OBJC_STATIC_FIELD_GETTER(ExtendedEventsManager, ADD_TO_CALENDAR, boolean)

FOUNDATION_EXPORT ExtendedEventsManager *ExtendedEventsManager_sInstance_;
J2OBJC_STATIC_FIELD_GETTER(ExtendedEventsManager, sInstance_, ExtendedEventsManager *)
//J2OBJC_STATIC_FIELD_SETTER(ExtendedEventsManager, sInstance_, ExtendedEventsManager *)

typedef ExtendedEventsManager ComIntelWearablePlatformTimeiqExtended_eventsExtendedEventsManager;

#endif // _ExtendedEventsManager_H_
