//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/persistence/syncdb/daoimpls/memory/GenericMemoryDao.java
//

#ifndef _GenericMemoryDao_H_
#define _GenericMemoryDao_H_

@class DataBaseControl;
#import "JBClass.h"
@protocol IDBSourceDefinition;
@protocol ITSOBaseDBObject;
#import "JBFuture.h"
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#import "IGenericDaoImpl.h"

/**
 @brief Created by aeirew on 01/09/2015.
 */
@interface GenericMemoryDao : NSObject < IGenericDaoImpl > {
 @public
  DataBaseControl *m_DBControl_;
  HashMap* m_dbInMem_;
  Class m_deserializeClass_;
  id m_lock_;
}

- (instancetype)initWithIDBSourceDefinition:(id<IDBSourceDefinition>)idbSourceDefinition
                               withIOSClass:(Class )tClass;

- (ArrayList*)getAllObjectsByUserIdWithNSString:(NSString *)s;

- (id)getObjectByIdWithNSString:(NSString *)userId
                   withNSString:(NSString *)objectId;

- (id<Future>)updateObjectWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object;

- (void)checkTimeWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object;

- (id<Future>)addObjectsWithJavaUtilList:(ArrayList*)list;

- (id<Future>)addObjectWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object;

- (id<Future>)deleteObjectWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object;

- (id<Future>)deleteObjectsWithJavaUtilList:(ArrayList*)list;

- (id<Future>)deleteAllObjectsByUserIdWithNSString:(NSString *)userId;

- (id<Future>)multiTransactionWithJavaUtilList:(ArrayList*)list;

- (ArrayList*)getAllAfterTimeStampWithNSString:(NSString *)s
                                            withLong:(long64)l;

- (ArrayList*)getObjectsByIdsWithNSString:(NSString *)userId
                               withJavaUtilList:(ArrayList*)list;

- (DataBaseControl *)getDBControl;

- (Class )getDeserializeClass;

- (HashMap*)validateAndGetMapOnAddWithJavaUtilList:(ArrayList*)list;

- (boolean)validateExistWithJavaUtilList:(ArrayList*)list;

- (void)copyAllFieldsTo:(GenericMemoryDao *)other;

@end

__attribute__((always_inline)) inline void GenericMemoryDao_init() {}

//J2OBJC_FIELD_SETTER(GenericMemoryDao, m_DBControl_, DataBaseControl *)
//J2OBJC_FIELD_SETTER(GenericMemoryDao, m_dbInMem_, HashMap*)
//J2OBJC_FIELD_SETTER(GenericMemoryDao, m_deserializeClass_, Class )
//J2OBJC_FIELD_SETTER(GenericMemoryDao, m_lock_, id)

typedef GenericMemoryDao ComIntelWearablePlatformTimeiqPlacesModulesPersistenceSyncdbDaoimplsMemoryGenericMemoryDao;

#endif // _GenericMemoryDao_H_
