//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/ttlAlerts/IAlertsOnMotChangeListener.java
//

#ifndef _IAlertsOnMotChangeListener_H_
#define _IAlertsOnMotChangeListener_H_

#import "JB.h"

/**
 @brief Created by smoradof on 9/8/2015.
 */
@protocol IAlertsOnMotChangeListener < NSObject >

- (void)onMotChangeWithNSString:(NSString *)alertId;

@end

__attribute__((always_inline)) inline void IAlertsOnMotChangeListener_init() {}

#define ComIntelWearablePlatformTimeiqTtlAlertsIAlertsOnMotChangeListener IAlertsOnMotChangeListener

#endif // _IAlertsOnMotChangeListener_H_
