//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/audit/IAuditForwardStrategy.java
//

#ifndef _IAuditForwardStrategy_H_
#define _IAuditForwardStrategy_H_

@protocol IForwarder;

#import "JB.h"

/**
 @brief Created by ibeider on 28/01/2015.
 */
@protocol IAuditForwardStrategy < NSObject >

- (void)init__WithIForwarder:(id<IForwarder>)forward OBJC_METHOD_FAMILY_NONE;

- (void)forward;

@end

__attribute__((always_inline)) inline void IAuditForwardStrategy_init() {}

#define ComIntelWearablePlatformTimeiqCommonAuditIAuditForwardStrategy IAuditForwardStrategy

#endif // _IAuditForwardStrategy_H_
