//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/core/auth/IAuthorizationManager.java
//

#ifndef _IAuthorizationManager_H_
#define _IAuthorizationManager_H_

@class TSOUserInfo;

#import "JB.h"

/**
 @brief Created by orencoh2 on 23/3/15.
 */
@protocol IAuthorizationManager < NSObject >

- (void)init__WithTSOUserInfo:(TSOUserInfo *)userInfo
                       withId:(id)credentials OBJC_METHOD_FAMILY_NONE;

- (TSOUserInfo *)getUserInfo;

- (id)getCredentials;

@end

__attribute__((always_inline)) inline void IAuthorizationManager_init() {}

#define ComIntelWearablePlatformTimeiqCommonCoreAuthIAuthorizationManager IAuthorizationManager

#endif // _IAuthorizationManager_H_
