//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/db/IDbManager.java
//

#ifndef _IDbManager_H_
#define _IDbManager_H_

#import "JBArrayList.h"
@protocol ISqlDb;

#import "JB.h"

/**
 @brief Created by yaronabr on 13-Jul-15.
 */
@protocol IDbManager < NSObject >

- (void)registerDbWithNSString:(NSString *)name
                       withInt:(int)version_
         withArrayList:(ArrayList *)listeners;

- (void)unregisterAllDbs;

- (void)unregisterSpecificDbWithNSString:(NSString *)name;

- (id<ISqlDb>)getDbByNameWithNSString:(NSString *)name
                          withBoolean:(boolean)isWritable;

- (id<ISqlDb>)getDefaultDbWithBoolean:(boolean)isWritable;

- (void)setDefaultDbWithNSString:(NSString *)defaultDb;

@end

__attribute__((always_inline)) inline void IDbManager_init() {}

#define ComIntelWearablePlatformTimeiqCommonStorageDbIDbManager IDbManager

#endif // _IDbManager_H_
