//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/datatypes/place/IDetectedPlace.java
//

#ifndef _IDetectedPlace_H_
#define _IDetectedPlace_H_

@class Coord;
@class PlaceStatus;
@class Polygon;
@class SemanticTag;
@class TSOCoordinate;

#import "JB.h"

/**
 @brief Created by orencoh2 on 8/12/14.
 */
@protocol IDetectedPlace < NSObject >

- (PlaceStatus *)getStatus;

- (Coord *)getCenter;

- (boolean)isPointInPlaceWithTSOCoordinate:(TSOCoordinate *)point;

- (NSString *)getPlaceId;

- (NSString *)getAddress;

- (long64)getDiscoveryTime;

- (Polygon *)getEnvelope;

- (SemanticTag *)getSemanticTag;

@end

__attribute__((always_inline)) inline void IDetectedPlace_init() {}

#define ComIntelWearablePlatformTimeiqPlacesDatatypesPlaceIDetectedPlace IDetectedPlace

#endif // _IDetectedPlace_H_
