//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/interfaces/places/ILocationData.java
//

#ifndef _ILocationData_H_
#define _ILocationData_H_

#import "JB.h"
#import "IMappable.h"

@protocol ILocationData < IMappable, NSObject >
- (float)getDistance;

- (long64)getElapsedRealtimeNanos;

- (long64)getTime;

- (double)getAltitude;

- (double)getLongitude;

- (double)getLatitude;

- (float)getInitialBearing;

- (boolean)isHasSpeed;

- (boolean)isHasBearing;

- (boolean)isHasAltitude;

- (boolean)isHasAccuracy;

- (float)getAccuracy;

- (float)getSpeed;

- (float)getBearing;

@end

__attribute__((always_inline)) inline void ILocationData_init() {}

#define ComIntelWearablePlatformTimeiqDbobjectsInterfacesPlacesILocationData ILocationData

#endif // _ILocationData_H_
