//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/IManagersListener.java
//

#ifndef _IManagersListener_H_
#define _IManagersListener_H_

#import "JBHashSet.h"

#import "JB.h"

/**
 @brief Created by smoradof on 5/11/2015.
 */
@protocol IManagersListener < NSObject >

- (void)onTriggerWithJavaUtilCollection:(Set*)triggers;

@end

__attribute__((always_inline)) inline void IManagersListener_init() {}

#define ComIntelWearablePlatformTimeiqTriggersIManagersListener IManagersListener

#endif // _IManagersListener_H_
