//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/api/common/messageHandler/IMessageListener.java
//

#ifndef _IMessageListener_H_
#define _IMessageListener_H_

@protocol IMessage;

#import "JB.h"

/**
 @brief Listener interface through which the SDK user can get messages from the SDK infrastructure.
 After implementing this interface - the user needs to register is in the Message Handler. The messages will be received through the onReceive method.
 */
@protocol IMessageListener < NSObject >

/**
 @brief The communication channel through which the SDK messages are received.
 The user should implement the message handling logic in this function.
 @param message - The SDK message
 */
- (void)onReceiveWithIMessage:(id<IMessage>)message;

@end

__attribute__((always_inline)) inline void IMessageListener_init() {}

#define ComIntelWearablePlatformTimeiqApiCommonMessageHandlerIMessageListener IMessageListener

#endif // _IMessageListener_H_
