//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/modulesapi/IModuleApi.java
//

#ifndef _IModuleApi_H_
#define _IModuleApi_H_

#import "JBVector.h"

#import "JB.h"

/**
 @brief Created by aeirew on 08/02/2015.
 */
@protocol IModuleApi < NSObject >

- (Vector *)getAll;

- (id)findWithId:(id)refEntity;

@end

__attribute__((always_inline)) inline void IModuleApi_init() {}

#define ComIntelWearablePlatformTimeiqPlacesModulesModulesapiIModuleApi IModuleApi

#endif // _IModuleApi_H_
