//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/datatypes/IMotUpdateListener.java
//

#ifndef _IMotUpdateListener_H_
#define _IMotUpdateListener_H_

@class MotInfo;

#import "JB.h"

/**
 @brief Created by omendels on 7/23/2015.
 */
@protocol IMotUpdateListener < NSObject >

/**
 @brief If the mot-value has changed, update MOT-value, and activate all the registered listeners
 @param newMot - the new MOT value
 */
- (void)updateMotValueWithMotInfo:(MotInfo *)newMot;

@end

__attribute__((always_inline)) inline void IMotUpdateListener_init() {}

#define ComIntelWearablePlatformTimeiqPlacesDatatypesIMotUpdateListener IMotUpdateListener

#endif // _IMotUpdateListener_H_
