//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/interfaces/places/IPolicyHistoryInfo.java
//

#ifndef _IPolicyHistoryInfo_H_
#define _IPolicyHistoryInfo_H_

@class PolicyMode;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"

@protocol IPolicyHistoryInfo < IMappable, NSObject >
- (PolicyMode *)getPreviousPolicy;

- (PolicyMode *)getNewPolicy;

- (long64)getTimeStamp;

- (HashMap*)getSensorsSampleIntervals;

@end

__attribute__((always_inline)) inline void IPolicyHistoryInfo_init() {}

#define ComIntelWearablePlatformTimeiqDbobjectsInterfacesPlacesIPolicyHistoryInfo IPolicyHistoryInfo

#endif // _IPolicyHistoryInfo_H_
