//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/preferences/IPrefs.java
//

#ifndef _IPrefs_H_
#define _IPrefs_H_

@class Result;
@protocol IPrefsChangedListener;
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"

/**
 @brief Created by mleib on 29/07/2015.
 */
@protocol IPrefs < NSObject >

- (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)registerForChangeWithIPrefsChangedListener:(id<IPrefsChangedListener>)prefsChangedListener;

- (void)unregisterForChangeWithIPrefsChangedListener:(id<IPrefsChangedListener>)prefsChangedListener;

- (boolean)containsWithNSString:(NSString *)key;

- (int)getIntWithNSString:(NSString *)key;

- (long64)getLongWithNSString:(NSString *)key;

- (float)getFloatWithNSString:(NSString *)key;

- (double)getDoubleWithNSString:(NSString *)key;

- (boolean)getBooleanWithNSString:(NSString *)key;

- (NSString *)getStringWithNSString:(NSString *)key;

- (ArrayList*)getStringArrayWithNSString:(NSString *)key;

- (HashMap*)getMapWithNSString:(NSString *)key;

- (Result *)setIntWithNSString:(NSString *)key
                       withInt:(int)value;

- (Result *)setLongWithNSString:(NSString *)key
                       withLong:(long64)value;

- (Result *)setFloatWithNSString:(NSString *)key
                       withFloat:(float)value;

- (Result *)setDoubleWithNSString:(NSString *)key
                       withDouble:(double)value;

- (Result *)setBooleanWithNSString:(NSString *)key
                       withBoolean:(boolean)value;

- (Result *)setStringWithNSString:(NSString *)key
                     withNSString:(NSString *)value;

- (Result *)setStringArrayWithNSString:(NSString *)key
                      withJavaUtilList:(ArrayList*)value;

- (Result *)setMapWithNSString:(NSString *)key
               withJavaUtilMap:(HashMap*)value;

@end

__attribute__((always_inline)) inline void IPrefs_init() {}

#define ComIntelWearablePlatformTimeiqCommonPreferencesIPrefs IPrefs

#endif // _IPrefs_H_
