//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/interfaces/places/IRefPoint.java
//

#ifndef _IRefPoint_H_
#define _IRefPoint_H_

#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"

@protocol IRefPoint < IMappable, NSObject >
- (long64)getModificationTimeStamp;

- (HashMap*)getHashTable;

- (double)getSumlat;

- (double)getSumlong;

- (int)getnPoints;

@end

__attribute__((always_inline)) inline void IRefPoint_init() {}

#define ComIntelWearablePlatformTimeiqDbobjectsInterfacesPlacesIRefPoint IRefPoint

#endif // _IRefPoint_H_
