//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/engine/ISensorDataReceiver.java
//

#ifndef _ISensorDataReceiver_H_
#define _ISensorDataReceiver_H_

@class BaseSensorData;
@class ReceiverSensorsRequest;
@class SensorType;

#import "JB.h"

/**
 @brief Created by aeirew on 17/11/2014.
 */
@protocol ISensorDataReceiver < NSObject >

- (void)onDataReceivedWithBaseSensorData:(BaseSensorData *)data;

- (void)onResetReceiver;

/**
 @brief Alert of sample interval change for a given sensor type PAY ATTENTION: a receiver must register specifically to a given sensor type with indication of "should listen to change sample interval" - @@SensorModeRequest
 @param sensorType
 @param sampleInterval
 */
- (void)onSampleIntervalChangedWithSensorType:(SensorType *)sensorType
                                         withLong:(long64)sampleInterval;

/**
 @brief create the sensor request
 @return 
 */
- (ReceiverSensorsRequest *)generateReceiverSensorsRequest;

@end

__attribute__((always_inline)) inline void ISensorDataReceiver_init() {}

#define ComIntelWearablePlatformTimeiqSensorsEngineISensorDataReceiver ISensorDataReceiver

#endif // _ISensorDataReceiver_H_
