//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/internalApi/sensors/ISensorsEngine.java
//

#ifndef _ISensorsEngine_H_
#define _ISensorsEngine_H_

@class AbstractHWSensor;
@class SDKPolicy;
@class SensorState;
@class SensorType;
#import "JBArrayList.h"

#import "JB.h"

/**
 @brief Created by eleuchte on 03/02/2015.
 */
@protocol ISensorsEngine < NSObject >

- (boolean)isRunning;

- (SensorState *)getSensorStateWithSensorType:(SensorType *)sensorType;

- (SDKPolicy *)getSDKPolicy;

- (long64)getSensorSampleIntervalInMillisWithSensorType:(SensorType *)sensorType;

- (ArrayList*)getAllPlatformSensorStates;

- (ArrayList*)getAllPlatformSensorsTypes;

- (AbstractHWSensor *)getPlatformSensorByTypeWithSensorType:(SensorType *)type;

@end

__attribute__((always_inline)) inline void ISensorsEngine_init() {}

#define ComIntelWearablePlatformTimeiqInternalApiSensorsISensorsEngine ISensorsEngine

#endif // _ISensorsEngine_H_
