//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/IStateDataProvider.java
//

#ifndef _IStateDataProvider_H_
#define _IStateDataProvider_H_

@class UserStateData;
@protocol IStateDataChangeListener;

#import "JB.h"

/**
 @brief Created by gilsharo on 6/7/2015.
 */
@protocol IStateDataProvider < NSObject >

- (void)setStateDataChangeListenerWithIStateDataChangeListener:(id<IStateDataChangeListener>)listener;

- (UserStateData *)getData;

@end

__attribute__((always_inline)) inline void IStateDataProvider_init() {}

#define ComIntelWearablePlatformTimeiqUserstateIStateDataProvider IStateDataProvider

#endif // _IStateDataProvider_H_
