//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/basicstorage/IStorageManager.java
//

#ifndef _IStorageManager_H_
#define _IStorageManager_H_

@protocol IStorage;

#import "JB.h"

/**
 @brief Created by ibeider on 03/02/2015.
 */
@protocol IStorageManager < NSObject >

- (id<IStorage>)getAuditStorage;

@end

__attribute__((always_inline)) inline void IStorageManager_init() {}

#define ComIntelWearablePlatformTimeiqCommonStorageBasicstorageIStorageManager IStorageManager

#endif // _IStorageManager_H_
