//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dblayer/interfaces/ISyncEventListener.java
//

#ifndef _ISyncEventListener_H_
#define _ISyncEventListener_H_

#import "JBFuture.h"

#import "JB.h"

@protocol ISyncEventListener < NSObject >

- (void)onSyncEventWithFuture:(id<Future>)eventResp;

@end

__attribute__((always_inline)) inline void ISyncEventListener_init() {}

#define ComIntelWearablePlatformTimeiqDblayerInterfacesISyncEventListener ISyncEventListener

#endif // _ISyncEventListener_H_
