//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/time/ITimeTriggerStorage.java
//

#ifndef _ITimeTriggerStorage_H_
#define _ITimeTriggerStorage_H_

#import "JBHashSet.h"

#import "JB.h"
#import "IBaseTriggersStorage.h"

/**
 @brief Created by smoradof on 5/5/2015.
 */
@protocol ITimeTriggerStorage < IBaseTriggersStorage, NSObject >
- (Set*)getAllTriggersForTimeWithLong:(long64)time;

@end

__attribute__((always_inline)) inline void ITimeTriggerStorage_init() {}

#define ComIntelWearablePlatformTimeiqTriggersTimeITimeTriggerStorage ITimeTriggerStorage

#endif // _ITimeTriggerStorage_H_
