//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/platform/java/common/timer/IOSAlarmManagerDebug.java
//

#ifndef _IOSAlarmManagerDebug_H_
#define _IOSAlarmManagerDebug_H_

#import "JBVector.h"

#import "JB.h"
#import "IOSAlarmManager.h"

/**
 @brief Created by smoradof on 1/21/15.
 */
@interface IOSAlarmManagerDebug : IOSAlarmManager {
}

- (void)setCurrentTimeWithLong:(long64)now;

- (Vector *)getAllAlarms;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void IOSAlarmManagerDebug_init() {}

typedef IOSAlarmManagerDebug ComIntelWearablePlatformTimeiqPlatformJavaCommonTimerIOSAlarmManagerDebug;

#endif // _IOSAlarmManagerDebug_H_
