//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //java/util/concurrent/ScheduledFuture.java
//

#ifndef _ScheduledFuture_H_
#define _ScheduledFuture_H_

#import "JB.h"
#include "JBDelayed.h"
#import "JBFuture.h"

@protocol ScheduledFuture < Delayed, Future, NSObject >
@end

__attribute__((always_inline)) inline void ScheduledFuture_init() {}

#endif // _ScheduledFuture_H_
