//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/messagehandler/MessageWithValidation.java
//

#ifndef _MessageWithValidation_H_
#define _MessageWithValidation_H_

@class Enum;
@class MessageImpl;
@protocol ISentValidationListener;

#import "JB.h"

/**
 @brief Created by smoradof on 6/8/2015.
 */
@interface MessageWithValidation : NSObject {
 @public
  id<ISentValidationListener> validationListener_;
  MessageImpl *message_;
}

- (instancetype)initWithEnum:(Enum *)messageType
                              withId:(id)message
         withISentValidationListener:(id<ISentValidationListener>)sentValidationListener;

- (id<ISentValidationListener>)getSentValidationListener;

- (MessageImpl *)getMessage;

- (void)copyAllFieldsTo:(MessageWithValidation *)other;

@end

__attribute__((always_inline)) inline void MessageWithValidation_init() {}

//J2OBJC_FIELD_SETTER(MessageWithValidation, validationListener_, id<ISentValidationListener>)
//J2OBJC_FIELD_SETTER(MessageWithValidation, message_, MessageImpl *)

typedef MessageWithValidation ComIntelWearablePlatformTimeiqCommonMessagehandlerMessageWithValidation;

#endif // _MessageWithValidation_H_
