//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/devicestatemanager/data/NetworkStateInfo.java
//

#ifndef _NetworkStateInfo_H_
#define _NetworkStateInfo_H_

#import "JB.h"

/**
 @brief Created by eleuchte on 02/08/2015.
 */
@interface NetworkStateInfo : NSObject {
 @public
  boolean m_isRoaming_;
  boolean m_isSendDataOverNetwork_;
  boolean m_isNetworkOverWifi_;
  boolean m_isNetworkAvailable_;
}

- (instancetype)init;

- (instancetype)initWithBoolean:(boolean)isSendDataOverNetwork
                    withBoolean:(boolean)isRoaming
                    withBoolean:(boolean)isNetworkOverWifi
                    withBoolean:(boolean)isNetworkAvailable;

- (instancetype)initWithNetworkStateInfo:(NetworkStateInfo *)other;

- (boolean)isSendDataOverNetwork;

- (boolean)isRoaming;

- (boolean)isNetworkOverWifi;

- (boolean)isNetworkAvailable;

- (void)setIsSendDataOverNetworkWithBoolean:(boolean)isSendDataOverNetwork;

- (void)setIsRoamingWithBoolean:(boolean)isRoaming;

- (void)setIsNetworkOverWifiWithBoolean:(boolean)isNetworkOverWifi;

- (void)setIsNetworkAvailableWithBoolean:(boolean)isNetworkAvailable;

- (void)copyAllFieldsTo:(NetworkStateInfo *)other;

@end

__attribute__((always_inline)) inline void NetworkStateInfo_init() {}

typedef NetworkStateInfo ComIntelWearablePlatformTimeiqCommonDevicestatemanagerDataNetworkStateInfo;

#endif // _NetworkStateInfo_H_
