//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/replay/NullReplaySensor.java
//

#ifndef _NullReplaySensor_H_
#define _NullReplaySensor_H_

@class SensorType;

#import "JB.h"
#import "AbstractHWSensor.h"

@interface NullReplaySensor : AbstractHWSensor {
 @public
  SensorType *m_type_;
}

- (instancetype)initWithSensorType:(SensorType *)type
                              withLong:(long64)sampleIntervalInMillis;

- (boolean)startSensor;

- (boolean)stopSensor;

- (boolean)pauseSensor;

- (boolean)resumeSensor;

- (SensorType *)getSensorType;

- (void)changeSampleRateWithLong:(long64)intervalInMillis;

- (void)copyAllFieldsTo:(NullReplaySensor *)other;

@end

__attribute__((always_inline)) inline void NullReplaySensor_init() {}

//J2OBJC_FIELD_SETTER(NullReplaySensor, m_type_, SensorType *)

typedef NullReplaySensor ComIntelWearablePlatformTimeiqSensorsReplayNullReplaySensor;

#endif // _NullReplaySensor_H_
