//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dblayer/sync/decorators/PlaceSyncDaoDecorator.java
//

#ifndef _PlaceSyncDaoDecorator_H_
#define _PlaceSyncDaoDecorator_H_

@protocol IGenericDaoImpl;
@protocol ISyncPlatformHandler;
@protocol ITSOSemanticPlace;

#import "JB.h"
#import "IPlaceDao.h"
#import "GenericSyncDaoDecorator.h"

@interface PlaceSyncDaoDecorator : GenericSyncDaoDecorator < IPlaceDao > {
}

- (instancetype)initWithIGenericDaoImpl:(id<IGenericDaoImpl>)daoImpl
               withISyncPlatformHandler:(id<ISyncPlatformHandler>)syncHandler;

- (id)getUserHomeWithNSString:(NSString *)arg0;

- (id)getUserPlaceByNameWithNSString:(NSString *)arg0
                        withNSString:(NSString *)arg1;

- (id)getUserWorkWithNSString:(NSString *)arg0;

@end

__attribute__((always_inline)) inline void PlaceSyncDaoDecorator_init() {}

typedef PlaceSyncDaoDecorator ComIntelWearablePlatformTimeiqDblayerSyncDecoratorsPlaceSyncDaoDecorator;

#endif // _PlaceSyncDaoDecorator_H_
