//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/utils/PlacesUtil.java
//

#ifndef _PlacesUtil_H_
#define _PlacesUtil_H_

#import "JBFile.h"
#import "JBArrayList.h"

#import "JB.h"
#import "JBFilenameFilter.h"
#import "JBComparator.h"

/**
 @brief Created by eleuchte on 06/11/2014.
 */
@interface PlacesUtil : NSObject {
}

+ (ArrayList *)retrieveFilteredFilesWithFile:(File *)externalDir
                                              withNSString:(NSString *)filterStr
                                                   withInt:(int)maxFiles;

+ (ArrayList *)retrieveDBFilesWithFile:(File *)externalDBDir;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL PlacesUtil_initialized;
J2OBJC_STATIC_INIT(PlacesUtil)

FOUNDATION_EXPORT NSString *PlacesUtil_TAG_;
J2OBJC_STATIC_FIELD_GETTER(PlacesUtil, TAG_, NSString *)

typedef PlacesUtil ComIntelWearablePlatformTimeiqPlacesUtilsPlacesUtil;

@interface PlacesUtil_$1 : NSObject < FilenameFilter > {
 @public
  NSString *val$filterStr_;
}

- (boolean)acceptWithFile:(File *)dir
                    withNSString:(NSString *)filename;

- (instancetype)initWithNSString:(NSString *)capture$0;

@end

__attribute__((always_inline)) inline void PlacesUtil_$1_init() {}

//J2OBJC_FIELD_SETTER(PlacesUtil_$1, val$filterStr_, NSString *)

@interface PlacesUtil_$2 : NSObject < IComparator > {
}

- (int)compareWithId:(File *)f1
               withId:(File *)f2;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void PlacesUtil_$2_init() {}

#endif // _PlacesUtil_H_
