//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/audit/SensorRawDataAudit.java
//

#ifndef _SensorRawDataAudit_H_
#define _SensorRawDataAudit_H_

@class BaseSensorData;
@class ClassFactory;
@class ReceiverSensorsRequest;
@class SensorType;
@class eAuditLabels;
@protocol IAuditManager;
@protocol IDaoCommonMethods;

#import "JB.h"
#import "ISensorRawDataAudit.h"
#import "ISensorDataReceiver.h"

/**
 @brief Created by aeirew on 11/03/2015.
 */
@interface SensorRawDataAudit : NSObject < ISensorDataReceiver, ISensorRawDataAudit > {
 @public
  id<IAuditManager> m_auditManager_;
  id<IDaoCommonMethods> m_daoCommonMethods_;
}

- (instancetype)init;

- (instancetype)initWithClassFactory:(ClassFactory *)factory;

- (instancetype)initWithIAuditManager:(id<IAuditManager>)auditManager
                withIDaoCommonMethods:(id<IDaoCommonMethods>)daoCommonMethods;

- (void)onDataReceivedWithBaseSensorData:(BaseSensorData *)data;

- (void)auditDataWithBaseSensorData:(BaseSensorData *)data
               withEAuditLabelsEnum:(eAuditLabels *)label;

- (void)onResetReceiver;

- (void)onSampleIntervalChangedWithSensorType:(SensorType *)sensorType
                                         withLong:(long64)sampleInterval;

- (ReceiverSensorsRequest *)generateReceiverSensorsRequest;

- (void)copyAllFieldsTo:(SensorRawDataAudit *)other;

@end

FOUNDATION_EXPORT BOOL SensorRawDataAudit_initialized;
J2OBJC_STATIC_INIT(SensorRawDataAudit)

//J2OBJC_FIELD_SETTER(SensorRawDataAudit, m_auditManager_, id<IAuditManager>)
//J2OBJC_FIELD_SETTER(SensorRawDataAudit, m_daoCommonMethods_, id<IDaoCommonMethods>)

FOUNDATION_EXPORT NSString *SensorRawDataAudit_TAG_;
J2OBJC_STATIC_FIELD_GETTER(SensorRawDataAudit, TAG_, NSString *)

typedef SensorRawDataAudit ComIntelWearablePlatformTimeiqSensorsAuditSensorRawDataAudit;

#endif // _SensorRawDataAudit_H_
