//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/time/TimeDataHelper.java
//

#ifndef _TimeDataHelper_H_
#define _TimeDataHelper_H_

#import "JBArrayList.h"
@protocol IBaseTriggersStorage;
#import "JBHashSet.h"

#import "JB.h"

/**
 @brief Created by yaronabr on 25-May-15.
 */
@interface TimeDataHelper : NSObject {
}

+ (Set*)getAllTriggersForTimeWithIBaseTriggersStorage:(id<IBaseTriggersStorage>)storage
                                                               withLong:(long64)time
                                                  withArrayList:(ArrayList *)data;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void TimeDataHelper_init() {}

typedef TimeDataHelper ComIntelWearablePlatformTimeiqTriggersTimeTimeDataHelper;

#endif // _TimeDataHelper_H_
