//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/devicestate/TimeZoneState.java
//

#ifndef _TimeZoneState_H_
#define _TimeZoneState_H_

#import "JB.h"

/**
 @brief Created by glis on 10/13/2015.
 */
@interface TimeZoneState : NSObject {
 @public
  NSString *timeZoneId_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)timeZoneId;

- (NSString *)getTimeZoneId;

- (void)setTimeZoneIdWithNSString:(NSString *)timeZoneId;

- (NSString *)description;

- (void)copyAllFieldsTo:(TimeZoneState *)other;

@end

__attribute__((always_inline)) inline void TimeZoneState_init() {}

//J2OBJC_FIELD_SETTER(TimeZoneState, timeZoneId_, NSString *)

typedef TimeZoneState ComIntelWearablePlatformTimeiqSensorsDatatypesDevicestateTimeZoneState;

#endif // _TimeZoneState_H_
