//
//  TSO.h
//  TSO
//
//  Created by Ben Nagar on 3/15/15.
//  Copyright (c) 2015 intel. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for TSO.
FOUNDATION_EXPORT double TSOVersionNumber;

//! Project version string for TSO.
FOUNDATION_EXPORT const unsigned char TSOVersionString[];


// MARK: - JB (JavaBridge)

#import <TimeIQ/JBCalendar.h>
#import <TimeIQ/JBEnumeration.h>
#import <TimeIQ/JBTimeZone.h>
#import <TimeIQ/JBArrayList.h>
#import <TimeIQ/JBListIterator.h>
#import <TimeIQ/JBThread.h>
#import <TimeIQ/JBObjectOutputStream.h>
#import <TimeIQ/JBInputStreamReader.h>
#import <TimeIQ/JBFilenameFilter.h>
#import <TimeIQ/JBRunnable.h>
#import <TimeIQ/JBObjectInputStream.h>
#import <TimeIQ/JBFile.h>
#import <TimeIQ/JBLog.h>
#import <TimeIQ/NSException+JavaAPI.h>
#import <TimeIQ/NSMutableString+JavaApi.h>
#import <TimeIQ/JBComparator.h>
#import <TimeIQ/JBLogger.h>
#import <TimeIQ/NSArray+JavaAPI.h>
#import <TimeIQ/JBFileOutputStream.h>
#import <TimeIQ/JBBundle.h>
#import <TimeIQ/JBBufferedReader.h>
#import <TimeIQ/JBPrintWriter.h>
//#import <TimeIQ/WifiSource.h>
#import <TimeIQ/JBHashSet.h>
#import <TimeIQ/JBDataInputStream.h>
#import <TimeIQ/JBMath.h>
#import <TimeIQ/JBSystem.h>
#import <TimeIQ/JBVector.h>
#import <TimeIQ/JBOutputStreamWriter.h>
#import <TimeIQ/JBWriter.h>
#import <TimeIQ/JBIterable.h>
#import <TimeIQ/JBEnum.h>
#import <TimeIQ/JBPrintStream.h>
#import <TimeIQ/JBIntent.h>
#import <TimeIQ/JBStringTokenizer.h>
#import <TimeIQ/JBComparable.h>
#import <TimeIQ/NSCalendar+JavaAPI.h>
#import <TimeIQ/JBTimer.h>
#import <TimeIQ/JBFileReader.h>
#import <TimeIQ/JBHashtable.h>
#import <TimeIQ/JBIterator.h>
#import <TimeIQ/JBNumberFormat.h>
#import <TimeIQ/JBStringWriter.h>
#import <TimeIQ/JBArrays.h>
#import <TimeIQ/NSDate+JavaAPI.h>
#import <TimeIQ/JBDataOutputStream.h>
#import <TimeIQ/JBInputStream.h>
#import <TimeIQ/JBReader.h>
#import <TimeIQ/JBOutputStream.h>
#import <TimeIQ/JBCollections.h>
#import <TimeIQ/JBFileInputStream.h>
#import <TimeIQ/Protocol+JavaAPI.h>
#import <TimeIQ/NSObject+JavaAPI.h>
#import <TimeIQ/JBDefines.h>
#import <TimeIQ/NSNumber+JavaAPI.h>
#import <TimeIQ/NSString+JavaAPI.h>
#import <TimeIQ/JB.h>
#import <TimeIQ/JBExecutorService.h>
#import <TimeIQ/JBExecutors.h>
#import <TimeIQ/JBByteArrayInputStream.h>
#import <TimeIQ/JBEqualsBuilder.h>
#import <TimeIQ/JBByteArrayOutputStream.h>
#import <TimeIQ/NSData+JavaAPI.h>
#import <TimeIQ/JBBase64.h>
#import <TimeIQ/JBCharset.h>
#import <TimeIQ/JBCopyOnWriteArraySet.h>
#import <TimeIQ/JBDateFormatter.h>
#import <TimeIQ/JBHashCodeBuilder.h>
#import <TimeIQ/JBLocale.h>
#import <TimeIQ/JBTimeUnit.h>
#import <TimeIQ/JBToStringBuilder.h>
#import <TimeIQ/JBToStringStyle.h>
#import <TimeIQ/JBUUID.h>
#import <TimeIQ/nanotime.h>

// MARK: - Manual


#import <TimeIQ/SDKLoader.h>
#import <TimeIQ/LocationApi.h>
#import <TimeIQ/ClassFactory.h>
//#import <TimeIQ/JavaAlarmManagerDebug.h>
//#import <TimeIQ/AuthorizationUtil.h>
//#import <TimeIQ/EventsPreferencesProvider.h>

// MARK: - Platform


#import <TimeIQ/IOSBluetoothScanSensor.h>
#import <TimeIQ/IOSAuthCredentialsProvider.h>
#import <TimeIQ/IOSHttpProvider.h>

// MARK: - 3D Parties



// MARK: - SDK (Tests)
//#import <TimeIQ/AndroidInitTestFacade.h>

// MARK: - SDK (Converted)

#import "IUserStateManagerModule.h"

/*** INSERTION START ***/

/*auto generated*/ #import "ABaseRemindersPersistentStorage.h"
/*auto generated*/ #import "ABaseTriggersManager.h"
/*auto generated*/ #import "ABaseTriggersMemoryStorage.h"
/*auto generated*/ #import "ABaseTriggersPersistentStorage.h"
/*auto generated*/ #import "ADbManager.h"
/*auto generated*/ #import "AHttpTransmitter.h"
/*auto generated*/ #import "AMessageEngine.h"
/*auto generated*/ #import "AObjectFactory.h"
/*auto generated*/ #import "AP.h"
/*auto generated*/ #import "APrefs.h"
/*auto generated*/ #import "AReminderTemplate.h"
/*auto generated*/ #import "ARemindersManager.h"
/*auto generated*/ #import "ARemindersMemoryStorage.h"
/*auto generated*/ #import "ARequest.h"
/*auto generated*/ #import "ARequestDataObj.h"
/*auto generated*/ #import "AResolverResponse.h"
/*auto generated*/ #import "AResponseDataObj.h"
/*auto generated*/ #import "AResponseObject.h"
/*auto generated*/ #import "ARouteData.h"
/*auto generated*/ #import "ASensorsEnginePlatformAPI.h"
/*auto generated*/ #import "AStateDataProvider.h"
/*auto generated*/ #import "ATSOBaseDBObject.h"
/*auto generated*/ #import "ATSOLogger.h"
/*auto generated*/ #import "ATSOPlace.h"
/*auto generated*/ #import "ATSOSemanticPlace.h"
/*auto generated*/ #import "ATSOSyncDbObject.h"
/*auto generated*/ #import "AbstractHWSensor.h"
/*auto generated*/ #import "AbstractHWTestLocationSensor.h"
/*auto generated*/ #import "AbstractHWTestSensor.h"
/*auto generated*/ #import "AbstractState.h"
/*auto generated*/ #import "ActivitySensorData.h"
/*auto generated*/ #import "AddPlaceMsg.h"
/*auto generated*/ #import "AlarmData.h"
/*auto generated*/ #import "AlertBuildException.h"
/*auto generated*/ #import "AlertBuildExceptionType.h"
/*auto generated*/ #import "AlertState.h"
/*auto generated*/ #import "AlertsRepository.h"
/*auto generated*/ #import "AlertsRepositoryDebug.h"
/*auto generated*/ #import "AndroidInitFacade.h"
/*auto generated*/ #import "AndroidInitTestFacade.h"
/*auto generated*/ #import "AndroidSyncPlatformHandler.h"
/*auto generated*/ #import "ApGrid.h"
/*auto generated*/ #import "ApPosition.h"
/*auto generated*/ #import "ApPositioningAlg.h"
/*auto generated*/ #import "ApStat.h"
/*auto generated*/ #import "ApiUsageAuditObj.h"
/*auto generated*/ #import "ApiUsageDebug.h"
/*auto generated*/ #import "ApiUsageUtil.h"
/*auto generated*/ #import "AssociatedWifiSpot.h"
/*auto generated*/ #import "AssociatedWifiSpotsBuilder.h"
/*auto generated*/ #import "AttendeeMeetingData.h"
/*auto generated*/ #import "AttendeeStatus.h"
/*auto generated*/ #import "AttendeeType.h"
/*auto generated*/ #import "AuditManager.h"
/*auto generated*/ #import "AuditManagerForTests.h"
/*auto generated*/ #import "AuditMeetingResolver.h"
/*auto generated*/ #import "AuditSchedulerStrategy.h"
/*auto generated*/ #import "AuditSendTime.h"
/*auto generated*/ #import "AuditSendTimeLevel.h"
/*auto generated*/ #import "AuditSettings.h"
/*auto generated*/ #import "AuditWifiBatteryStrategy.h"
/*auto generated*/ #import "AuditWifiStrategy.h"
/*auto generated*/ #import "AuthorizationManagerImpl.h"
/*auto generated*/ #import "BackoffAlgorithmHelperBase.h"
/*auto generated*/ #import "BackoffAlgorithmType.h"
/*auto generated*/ #import "BaseEvent.h"
/*auto generated*/ #import "BasePhoneReminder.h"
/*auto generated*/ #import "BasePhoneReminderInner.h"
/*auto generated*/ #import "BaseReminder.h"
/*auto generated*/ #import "BaseReminderInner.h"
/*auto generated*/ #import "BaseSensorData.h"
/*auto generated*/ #import "BaseTrigger.h"
/*auto generated*/ #import "BaseTriggerInner.h"
/*auto generated*/ #import "BaseUserStateChangeProvider.h"
/*auto generated*/ #import "BasicRouteProviderImpl.h"
/*auto generated*/ #import "BasicRouteProviderStub.h"
/*auto generated*/ #import "BatteryLeverInfoData.h"
/*auto generated*/ #import "BatteryStateInfo.h"
/*auto generated*/ #import "BeEvent.h"
/*auto generated*/ #import "BeEventTemplate.h"
/*auto generated*/ #import "BeManager.h"
/*auto generated*/ #import "BlockingDaoFactory.h"
/*auto generated*/ #import "BluetoothDeviceInfo.h"
/*auto generated*/ #import "BluetoothDeviceSensorData.h"
/*auto generated*/ #import "BoundingBox.h"
/*auto generated*/ #import "BssidEntryMap.h"
/*auto generated*/ #import "BuildConfig.h"
/*auto generated*/ #import "BuildPrefs.h"
/*auto generated*/ #import "BuildPrefsStub.h"
/*auto generated*/ #import "CLUSTER_STATE.h"
/*auto generated*/ #import "CalendarDetails.h"
/*auto generated*/ #import "CalendarDetailsProvider.h"
/*auto generated*/ #import "CalendarEvent.h"
/*auto generated*/ #import "CalendarEventsManager.h"
/*auto generated*/ #import "CalendarOperationException.h"
/*auto generated*/ #import "CalendarPrefs.h"
/*auto generated*/ #import "CallReminder.h"
/*auto generated*/ #import "CallReminderInner.h"
/*auto generated*/ #import "CallRemindersManager.h"
/*auto generated*/ #import "CallRemindersMemoryStorage.h"
/*auto generated*/ #import "CallRemindersPersistentStorage.h"
/*auto generated*/ #import "CallType.h"
/*auto generated*/ #import "ChargeDataHelper.h"
/*auto generated*/ #import "ChargeMethod.h"
/*auto generated*/ #import "ChargeTrigger.h"
/*auto generated*/ #import "ChargeTriggerInner.h"
/*auto generated*/ #import "ChargeTriggerType.h"
/*auto generated*/ #import "ChargeTriggersManager.h"
/*auto generated*/ #import "ChargeTriggersMemoryStorage.h"
/*auto generated*/ #import "ChargeTriggersPersistentStorage.h"
/*auto generated*/ #import "ClassFactory.h"
/*auto generated*/ #import "ClassFactoryRegisterException.h"
/*auto generated*/ #import "ClassFactoryResolveException.h"
/*auto generated*/ #import "Cluster.h"
/*auto generated*/ #import "ClusterLocation.h"
/*auto generated*/ #import "ClusterParameters.h"
/*auto generated*/ #import "ClusterSensedPlace.h"
/*auto generated*/ #import "ClusterStatistics.h"
/*auto generated*/ #import "ClusteringParameters.h"
/*auto generated*/ #import "ColMatrix.h"
/*auto generated*/ #import "CommonClassPool.h"
/*auto generated*/ #import "CommonDaoInitializerFile.h"
/*auto generated*/ #import "CommonDaoInitializerMemory.h"
/*auto generated*/ #import "CommonDaoInitializerSQL.h"
/*auto generated*/ #import "CommonFactoryInitializer.h"
/*auto generated*/ #import "ConfigStorage.h"
/*auto generated*/ #import "ContactInfo.h"
/*auto generated*/ #import "ConvexHull.h"
/*auto generated*/ #import "Coord.h"
/*auto generated*/ #import "DBApStat.h"
/*auto generated*/ #import "DBConfig.h"
/*auto generated*/ #import "DBLocationData.h"
/*auto generated*/ #import "DBObjectWithOperation.h"
/*auto generated*/ #import "DBOperation.h"
/*auto generated*/ #import "DBPolicyHistoryInfo.h"
/*auto generated*/ #import "DBPolygon.h"
/*auto generated*/ #import "DBRefPoint.h"
/*auto generated*/ #import "DBRepositoryFileImpl.h"
/*auto generated*/ #import "DBResponse.h"
/*auto generated*/ #import "DBSensorDataFile.h"
/*auto generated*/ #import "DBSourceDefinition.h"
/*auto generated*/ #import "DBVisit.h"
/*auto generated*/ #import "DBWifiSignature.h"
/*auto generated*/ #import "DaoCommonMethods.h"
/*auto generated*/ #import "DaoFactory.h"
/*auto generated*/ #import "DaoSendSyncImmediatelyStrategy.h"
/*auto generated*/ #import "DaoSendSyncTimerIntervalStrategy.h"
/*auto generated*/ #import "DaoType.h"
/*auto generated*/ #import "DaoTypeToClassConvertor.h"
/*auto generated*/ #import "DataBaseControl.h"
/*auto generated*/ #import "DataObjectFactory.h"
/*auto generated*/ #import "DateFormatType.h"
/*auto generated*/ #import "DefaultSQLCreateUpdateStrategy.h"
/*auto generated*/ #import "DetectedPlace.h"
/*auto generated*/ #import "DeviceConnectionState.h"
/*auto generated*/ #import "DeviceDataAuditObj.h"
/*auto generated*/ #import "DeviceStateData.h"
/*auto generated*/ #import "DeviceStateManager.h"
/*auto generated*/ #import "DeviceStateManagerMock.h"
/*auto generated*/ #import "DeviceStateSensorData.h"
/*auto generated*/ #import "DeviceStateType.h"
/*auto generated*/ #import "DjClusterAlg.h"
/*auto generated*/ #import "DoAtTimeBeforeTemplate.h"
/*auto generated*/ #import "DoAtTimeOfDayTemplate.h"
/*auto generated*/ #import "DoReminder.h"
/*auto generated*/ #import "DoReminderInner.h"
/*auto generated*/ #import "DoRemindersManager.h"
/*auto generated*/ #import "DoRemindersMemoryStorage.h"
/*auto generated*/ #import "DoRemindersPersistentStorage.h"
/*auto generated*/ #import "ETARequest.h"
/*auto generated*/ #import "ETARequestDataObj.h"
/*auto generated*/ #import "ETARequestResponseDataObj.h"
/*auto generated*/ #import "ETAResponse.h"
/*auto generated*/ #import "ETAResponseDataObj.h"
/*auto generated*/ #import "Edge.h"
/*auto generated*/ #import "EndSuspendState.h"
/*auto generated*/ #import "EndVipState.h"
/*auto generated*/ #import "EtaRouteData.h"
/*auto generated*/ #import "EventContext.h"
/*auto generated*/ #import "EventIdInfo.h"
/*auto generated*/ #import "EventIdManager.h"
/*auto generated*/ #import "EventTriggerType.h"
/*auto generated*/ #import "EventsAudit.h"
/*auto generated*/ #import "EventsClassPool.h"
/*auto generated*/ #import "EventsEngine.h"
/*auto generated*/ #import "EventsFactoryInitializer.h"
/*auto generated*/ #import "EventsManager.h"
/*auto generated*/ #import "EventsManagerDebug.h"
/*auto generated*/ #import "EventsPersistenceUtil.h"
/*auto generated*/ #import "EventsPriorityQueue.h"
/*auto generated*/ #import "EventsUtils.h"
/*auto generated*/ #import "ExtendedEventInstance.h"
/*auto generated*/ #import "ExtendedEventTemplate.h"
/*auto generated*/ #import "ExtendedEventsManager.h"
/*auto generated*/ #import "ExternalEngine.h"
/*auto generated*/ #import "ExternalPlacesModule.h"
/*auto generated*/ #import "FakeTimer.h"
/*auto generated*/ #import "FilePlacesDao.h"
/*auto generated*/ #import "FileStreamManager.h"
/*auto generated*/ #import "FlowType.h"
/*auto generated*/ #import "FuseFilter.h"
/*auto generated*/ #import "FusePoint.h"
/*auto generated*/ #import "FuseSensorData.h"
/*auto generated*/ #import "FusedLocVisitDetector.h"
/*auto generated*/ #import "GPSSensorData.h"
/*auto generated*/ #import "GaussianMixtureModel.h"
/*auto generated*/ #import "GenericClientUserIDDaoDecorator.h"
/*auto generated*/ #import "GenericFileDao.h"
/*auto generated*/ #import "GenericMemoryDao.h"
/*auto generated*/ #import "GenericSQLDao.h"
/*auto generated*/ #import "GenericSyncDaoDecorator.h"
/*auto generated*/ #import "GeoUtil.h"
/*auto generated*/ #import "GeographicData.h"
/*auto generated*/ #import "GmmAlgo.h"
/*auto generated*/ #import "GpsState.h"
/*auto generated*/ #import "Grid.h"
/*auto generated*/ #import "GsonConvertor.h"
/*auto generated*/ #import "HomeWorkDetectionModule.h"
/*auto generated*/ #import "HttpAuditTransmitter.h"
/*auto generated*/ #import "HttpProviderNull.h"
/*auto generated*/ #import "HttpProviderSettings.h"
/*auto generated*/ #import "HttpProviderStub.h"
/*auto generated*/ #import "HttpProviderWrapper.h"
/*auto generated*/ #import "HttpProviderWrapperStub.h"
/*auto generated*/ #import "HttpSentDataInfo.h"
/*auto generated*/ #import "IAlertsOnMotChangeListener.h"
/*auto generated*/ #import "IApStat.h"
/*auto generated*/ #import "IApiUsageUtil.h"
/*auto generated*/ #import "IAuditForwardStrategy.h"
/*auto generated*/ #import "IAuditManager.h"
/*auto generated*/ #import "IAutenticacion.h"
/*auto generated*/ #import "IAuthCredentialsProvider.h"
/*auto generated*/ #import "IAuthorizationManager.h"
/*auto generated*/ #import "IBackoffAlgorithm.h"
/*auto generated*/ #import "IBase64Utils.h"
/*auto generated*/ #import "IBaseRemindersManager.h"
/*auto generated*/ #import "IBaseTriggersManager.h"
/*auto generated*/ #import "IBaseTriggersStorage.h"
/*auto generated*/ #import "IBasicRouteProvider.h"
/*auto generated*/ #import "IBeManager.h"
/*auto generated*/ #import "IBuildPrefs.h"
/*auto generated*/ #import "ICalendar.h"
/*auto generated*/ #import "ICalendarDetailsProvider.h"
/*auto generated*/ #import "ICalendarEventsManager.h"
/*auto generated*/ #import "ICalendarListener.h"
/*auto generated*/ #import "ICallRemindersManager.h"
/*auto generated*/ #import "ICallRemindersStorage.h"
/*auto generated*/ #import "IChargeTriggerStorage.h"
/*auto generated*/ #import "IChargeTriggersManager.h"
/*auto generated*/ #import "IContentValues.h"
/*auto generated*/ #import "ICreateUpdateStrategy.h"
/*auto generated*/ #import "ICursor.h"
/*auto generated*/ #import "IDBRepositoryImpl.h"
/*auto generated*/ #import "IDBSourceDefinition.h"
/*auto generated*/ #import "IDaoCommonMethods.h"
/*auto generated*/ #import "IDaoCreateUpdateConsumer.h"
/*auto generated*/ #import "IDaoDecorator.h"
/*auto generated*/ #import "IDaoSendSyncStrategy.h"
/*auto generated*/ #import "IDbManager.h"
/*auto generated*/ #import "IDbPlatformImpl.h"
/*auto generated*/ #import "IDetectedPlace.h"
/*auto generated*/ #import "IDetectionModule.h"
/*auto generated*/ #import "IDeviceInfo.h"
/*auto generated*/ #import "IDeviceStateListener.h"
/*auto generated*/ #import "IDeviceStateManager.h"
/*auto generated*/ #import "IDoRemindersManager.h"
/*auto generated*/ #import "IDoRemindersStorage.h"
/*auto generated*/ #import "IEvent.h"
/*auto generated*/ #import "IEventSyncListener.h"
/*auto generated*/ #import "IEventUpdateListener.h"
/*auto generated*/ #import "IEventsAudit.h"
/*auto generated*/ #import "IEventsEngine.h"
/*auto generated*/ #import "IEventsManager.h"
/*auto generated*/ #import "IEventsPersistenceUtil.h"
/*auto generated*/ #import "IExtendedEventsHandler.h"
/*auto generated*/ #import "IExternalMessageEngine.h"
/*auto generated*/ #import "IExternalPlaceListener.h"
/*auto generated*/ #import "IFileUtils.h"
/*auto generated*/ #import "IForwarder.h"
/*auto generated*/ #import "IGenericDaoImpl.h"
/*auto generated*/ #import "IGenericDaoQuery.h"
/*auto generated*/ #import "IHWSensorListener.h"
/*auto generated*/ #import "IHttpAuditTransmitter.h"
/*auto generated*/ #import "IHttpProvider.h"
/*auto generated*/ #import "IHttpProviderWrapper.h"
/*auto generated*/ #import "IHttpSentDataListener.h"
/*auto generated*/ #import "IInternalMessageEngine.h"
/*auto generated*/ #import "IJSONUtils.h"
/*auto generated*/ #import "ILocationAwareSensor.h"
/*auto generated*/ #import "ILocationData.h"
/*auto generated*/ #import "ILocationProvider.h"
/*auto generated*/ #import "IManagersListener.h"
/*auto generated*/ #import "IMappable.h"
/*auto generated*/ #import "IMat.h"
/*auto generated*/ #import "IMemoryRepositoryImpl.h"
/*auto generated*/ #import "IMessage.h"
/*auto generated*/ #import "IMessageHandler.h"
/*auto generated*/ #import "IMessageListener.h"
/*auto generated*/ #import "IModule.h"
/*auto generated*/ #import "IModuleApi.h"
/*auto generated*/ #import "IMotChangeListener.h"
/*auto generated*/ #import "IMotDetectionModule.h"
/*auto generated*/ #import "IMotDetector.h"
/*auto generated*/ #import "IMotRecommender.h"
/*auto generated*/ #import "IMotStateDataProvider.h"
/*auto generated*/ #import "IMotTriggerStorage.h"
/*auto generated*/ #import "IMotTriggersManager.h"
/*auto generated*/ #import "IMotUpdateListener.h"
/*auto generated*/ #import "INextNotificationCalculator.h"
/*auto generated*/ #import "INextWakeUpCalculator.h"
/*auto generated*/ #import "INotificationRemindersManager.h"
/*auto generated*/ #import "INotificationRemindersStorage.h"
/*auto generated*/ #import "IOSAuthCredentialsProvider.h"
/*auto generated*/ #import "IOSBluetoothScanSensor.h"
/*auto generated*/ #import "IOSHttpProvider.h"
/*auto generated*/ #import "IOSWakeLock.h"
/*auto generated*/ #import "IPC.h"
/*auto generated*/ #import "IPeriodicDetectionModule.h"
/*auto generated*/ #import "IPlaceDao.h"
/*auto generated*/ #import "IPlaceListener.h"
/*auto generated*/ #import "IPlaceRepo.h"
/*auto generated*/ #import "IPlacesEngine.h"
/*auto generated*/ #import "IPlacesTriggersManager.h"
/*auto generated*/ #import "IPlacesTriggersStorage.h"
/*auto generated*/ #import "IPlatformServices.h"
/*auto generated*/ #import "IPolicyHistoryInfo.h"
/*auto generated*/ #import "IPolicyListener.h"
/*auto generated*/ #import "IPrefs.h"
/*auto generated*/ #import "IPrefsChangedListener.h"
/*auto generated*/ #import "IPrefsLoader.h"
/*auto generated*/ #import "IRefPoint.h"
/*auto generated*/ #import "IReminder.h"
/*auto generated*/ #import "IReminderInner.h"
/*auto generated*/ #import "IRemindersManager.h"
/*auto generated*/ #import "IRemindersStorage.h"
/*auto generated*/ #import "IResolver.h"
/*auto generated*/ #import "IRouteData.h"
/*auto generated*/ #import "IRouteProvider.h"
/*auto generated*/ #import "IRouteProviderCache.h"
/*auto generated*/ #import "IRouteProviderInner.h"
/*auto generated*/ #import "ISdkDefaultPrefs.h"
/*auto generated*/ #import "ISegmentedRouteProvider.h"
/*auto generated*/ #import "ISensorDataReceiver.h"
/*auto generated*/ #import "ISensorDumpFileLogger.h"
/*auto generated*/ #import "ISensorRawDataAudit.h"
/*auto generated*/ #import "ISensorsEngine.h"
/*auto generated*/ #import "ISentValidationListener.h"
/*auto generated*/ #import "ISimulateListener.h"
/*auto generated*/ #import "ISnoozeOptionsProvider.h"
/*auto generated*/ #import "ISqlDb.h"
/*auto generated*/ #import "ISqlHelper.h"
/*auto generated*/ #import "IState.h"
/*auto generated*/ #import "IStateDataChangeListener.h"
/*auto generated*/ #import "IStateDataProvider.h"
/*auto generated*/ #import "IStatsFileLogger.h"
/*auto generated*/ #import "IStorage.h"
/*auto generated*/ #import "IStorageManager.h"
/*auto generated*/ #import "ISyncDao.h"
/*auto generated*/ #import "ISyncEventListener.h"
/*auto generated*/ #import "ISyncMethods.h"
/*auto generated*/ #import "ISyncPlatformHandler.h"
/*auto generated*/ #import "ISystemUtils.h"
/*auto generated*/ #import "ITSOAlarmListener.h"
/*auto generated*/ #import "ITSOAlarmManager.h"
/*auto generated*/ #import "ITSOAlertListener.h"
/*auto generated*/ #import "ITSOAlertProvider.h"
/*auto generated*/ #import "ITSOAlertsEngine.h"
/*auto generated*/ #import "ITSOAlertsMotChangeListener.h"
/*auto generated*/ #import "ITSOAlertsRepository.h"
/*auto generated*/ #import "ITSOBaseDBObject.h"
/*auto generated*/ #import "ITSOCalendarsManager.h"
/*auto generated*/ #import "ITSOEvent.h"
/*auto generated*/ #import "ITSOEventsSync.h"
/*auto generated*/ #import "ITSOLogger.h"
/*auto generated*/ #import "ITSOLoggerListener.h"
/*auto generated*/ #import "ITSOLoggerPlaces.h"
/*auto generated*/ #import "ITSOPlace.h"
/*auto generated*/ #import "ITSOSemanticPlace.h"
/*auto generated*/ #import "ITSOSyncDbObject.h"
/*auto generated*/ #import "ITSOTimeUtil.h"
/*auto generated*/ #import "ITimeTriggerStorage.h"
/*auto generated*/ #import "ITimeTriggersManager.h"
/*auto generated*/ #import "ITimeUtil_ISO8601.h"
/*auto generated*/ #import "ITransfer.h"
/*auto generated*/ #import "ITransmitter.h"
/*auto generated*/ #import "ITrigger.h"
/*auto generated*/ #import "ITriggerInner.h"
/*auto generated*/ #import "ITriggerLifeCycleAuditManager.h"
/*auto generated*/ #import "ITriggerLifeCycleListener.h"
/*auto generated*/ #import "ITriggerListener.h"
/*auto generated*/ #import "ITriggersManager.h"
/*auto generated*/ #import "ITriggersManagerInner.h"
/*auto generated*/ #import "IUserPrefs.h"
/*auto generated*/ #import "IUserStateAuditManager.h"
/*auto generated*/ #import "IUserStateChangeListener.h"
/*auto generated*/ #import "IUserStateChangeProvider.h"
/*auto generated*/ #import "IUserStateFilter.h"
/*auto generated*/ #import "IUserStateManager.h"
/*auto generated*/ #import "IUserStateMonitor.h"
/*auto generated*/ #import "IVipStateDataProvider.h"
/*auto generated*/ #import "IVisitDetectorImpl.h"
/*auto generated*/ #import "IVisitEntry.h"
/*auto generated*/ #import "IVisitInPlaceListener.h"
/*auto generated*/ #import "IVisitListener.h"
/*auto generated*/ #import "IWakeLock.h"
/*auto generated*/ #import "IWifiSignature.h"
/*auto generated*/ #import "IllegalNumberException.h"
/*auto generated*/ #import "ImportanceType.h"
/*auto generated*/ #import "InPlaceConfidence.h"
/*auto generated*/ #import "InProgressState.h"
/*auto generated*/ #import "InnerMessageType.h"
/*auto generated*/ #import "InstanceFactory.h"
/*auto generated*/ #import "InternalEngine.h"
/*auto generated*/ #import "J2SESensorsEnginePlatformImpl.h"
/*auto generated*/ #import "J2SESystemUtils.h"
/*auto generated*/ #import "JB.h"
/*auto generated*/ #import "JBArrayList.h"
/*auto generated*/ #import "JBArrays.h"
/*auto generated*/ #import "JBBase64.h"
/*auto generated*/ #import "JBBufferedInputStream.h"
/*auto generated*/ #import "JBBufferedOutputStream.h"
/*auto generated*/ #import "JBBufferedReader.h"
/*auto generated*/ #import "JBBufferedWriter.h"
/*auto generated*/ #import "JBBundle.h"
/*auto generated*/ #import "JBByteArrayInputStream.h"
/*auto generated*/ #import "JBByteArrayOutputStream.h"
/*auto generated*/ #import "JBCalendar.h"
/*auto generated*/ #import "JBCallable.h"
/*auto generated*/ #import "JBCharset.h"
/*auto generated*/ #import "JBClass.h"
/*auto generated*/ #import "JBCollections.h"
/*auto generated*/ #import "JBComparable.h"
/*auto generated*/ #import "JBComparator.h"
/*auto generated*/ #import "JBConcurrentHashMap.h"
/*auto generated*/ #import "JBCopyOnWriteArrayList.h"
/*auto generated*/ #import "JBCopyOnWriteArraySet.h"
/*auto generated*/ #import "JBDataInputStream.h"
/*auto generated*/ #import "JBDataOutputStream.h"
/*auto generated*/ #import "JBDateFormatter.h"
/*auto generated*/ #import "JBDefines.h"
/*auto generated*/ #import "JBDelayed.h"
/*auto generated*/ #import "JBEnum.h"
/*auto generated*/ #import "JBEnumSet.h"
/*auto generated*/ #import "JBEnumeration.h"
/*auto generated*/ #import "JBEqualsBuilder.h"
/*auto generated*/ #import "JBExecutorService.h"
/*auto generated*/ #import "JBExecutors.h"
/*auto generated*/ #import "JBFile.h"
/*auto generated*/ #import "JBFileChannel.h"
/*auto generated*/ #import "JBFileInputStream.h"
/*auto generated*/ #import "JBFileOutputStream.h"
/*auto generated*/ #import "JBFileReader.h"
/*auto generated*/ #import "JBFileWriter.h"
/*auto generated*/ #import "JBFilenameFilter.h"
/*auto generated*/ #import "JBFuture.h"
/*auto generated*/ #import "JBFutureTask.h"
/*auto generated*/ #import "JBGregorianCalendar.h"
/*auto generated*/ #import "JBHashCodeBuilder.h"
/*auto generated*/ #import "JBHashSet.h"
/*auto generated*/ #import "JBHashtable.h"
/*auto generated*/ #import "JBHashtableEntry.h"
/*auto generated*/ #import "JBInputStream.h"
/*auto generated*/ #import "JBInputStreamReader.h"
/*auto generated*/ #import "JBIntent.h"
/*auto generated*/ #import "JBIterable.h"
/*auto generated*/ #import "JBIterator.h"
/*auto generated*/ #import "JBListIterator.h"
/*auto generated*/ #import "JBLocale.h"
/*auto generated*/ #import "JBLog.h"
/*auto generated*/ #import "JBLogger.h"
/*auto generated*/ #import "JBMath.h"
/*auto generated*/ #import "JBNativeArray.h"
/*auto generated*/ #import "JBNumberFormat.h"
/*auto generated*/ #import "JBObjectInputStream.h"
/*auto generated*/ #import "JBObjectOutputStream.h"
/*auto generated*/ #import "JBOutputStream.h"
/*auto generated*/ #import "JBOutputStreamWriter.h"
/*auto generated*/ #import "JBPair.h"
/*auto generated*/ #import "JBPrintStream.h"
/*auto generated*/ #import "JBPrintWriter.h"
/*auto generated*/ #import "JBPriorityQueue.h"
/*auto generated*/ #import "JBQueue.h"
/*auto generated*/ #import "JBRandom.h"
/*auto generated*/ #import "JBReader.h"
/*auto generated*/ #import "JBReentrantLock.h"
/*auto generated*/ #import "JBRunnable.h"
/*auto generated*/ #import "JBScheduledFuture.h"
/*auto generated*/ #import "JBScheduledThreadPoolExecutor.h"
/*auto generated*/ #import "JBSerializable.h"
/*auto generated*/ #import "JBStack.h"
/*auto generated*/ #import "JBStringTokenizer.h"
/*auto generated*/ #import "JBStringWriter.h"
/*auto generated*/ #import "JBSystem.h"
/*auto generated*/ #import "JBThread.h"
/*auto generated*/ #import "JBTimeUnit.h"
/*auto generated*/ #import "JBTimeZone.h"
/*auto generated*/ #import "JBTimer.h"
/*auto generated*/ #import "JBTimerTask.h"
/*auto generated*/ #import "JBToStringBuilder.h"
/*auto generated*/ #import "JBToStringStyle.h"
/*auto generated*/ #import "JBUUID.h"
/*auto generated*/ #import "JBVector.h"
/*auto generated*/ #import "JBWriter.h"
/*auto generated*/ #import "JBZipEntry.h"
/*auto generated*/ #import "JBZipOutputStream.h"
/*auto generated*/ #import "JavaCalendar.h"
/*auto generated*/ #import "JavaCommonFactoryInitializer.h"
/*auto generated*/ #import "JavaTSOLogger.h"
/*auto generated*/ #import "JavaTSOPlacesFactoryInitializer.h"
/*auto generated*/ #import "JavaWakeLock.h"
/*auto generated*/ #import "LOG_LEVEL.h"
/*auto generated*/ #import "LocVisitState.h"
/*auto generated*/ #import "Location.h"
/*auto generated*/ #import "LocationApi.h"
/*auto generated*/ #import "LocationBaseSensorData.h"
/*auto generated*/ #import "LocationBuilder.h"
/*auto generated*/ #import "LocationCluster.h"
/*auto generated*/ #import "LocationClusterAgent.h"
/*auto generated*/ #import "LocationData.h"
/*auto generated*/ #import "LocationProvider.h"
/*auto generated*/ #import "LocationProviderDebug.h"
/*auto generated*/ #import "LocationServicesStateInfo.h"
/*auto generated*/ #import "LocationType.h"
/*auto generated*/ #import "LogFilePrefs.h"
/*auto generated*/ #import "ManualDetected.h"
/*auto generated*/ #import "ManualDetectedSensedPlace.h"
/*auto generated*/ #import "ManualPlace.h"
/*auto generated*/ #import "ManualPlaceSource.h"
/*auto generated*/ #import "ManualSensedPlace.h"
/*auto generated*/ #import "MapConversionUtils.h"
/*auto generated*/ #import "MapValues.h"
/*auto generated*/ #import "Mat.h"
/*auto generated*/ #import "MeetingAttendee.h"
/*auto generated*/ #import "MeetingReminder.h"
/*auto generated*/ #import "MeetingReminderType.h"
/*auto generated*/ #import "MeetingResolverType.h"
/*auto generated*/ #import "MemoryPlacesDao.h"
/*auto generated*/ #import "MemoryRepository.h"
/*auto generated*/ #import "MemoryRepositoryFileImpl.h"
/*auto generated*/ #import "MessageImpl.h"
/*auto generated*/ #import "MessageType.h"
/*auto generated*/ #import "MessageWithValidation.h"
/*auto generated*/ #import "MethodNotFoundException.h"
/*auto generated*/ #import "ModuleProduct.h"
/*auto generated*/ #import "ModuleProductType.h"
/*auto generated*/ #import "ModuleState.h"
/*auto generated*/ #import "ModuleType.h"
/*auto generated*/ #import "ModulesInitFacade.h"
/*auto generated*/ #import "Mot.h"
/*auto generated*/ #import "MotBtHelper.h"
/*auto generated*/ #import "MotDataHelper.h"
/*auto generated*/ #import "MotDetectionModule.h"
/*auto generated*/ #import "MotDetectorV2.h"
/*auto generated*/ #import "MotDetectoriPhone.h"
/*auto generated*/ #import "MotDetectoriPhoneNaive.h"
/*auto generated*/ #import "MotInfo.h"
/*auto generated*/ #import "MotLocationHelperIphone.h"
/*auto generated*/ #import "MotRecommenderImpl.h"
/*auto generated*/ #import "MotStateDataProvider.h"
/*auto generated*/ #import "MotTransition.h"
/*auto generated*/ #import "MotTrigger.h"
/*auto generated*/ #import "MotTriggerInner.h"
/*auto generated*/ #import "MotTriggersManager.h"
/*auto generated*/ #import "MotTriggersMemoryStorage.h"
/*auto generated*/ #import "MotTriggersPersistentStorage.h"
/*auto generated*/ #import "MotType.h"
/*auto generated*/ #import "MultiInstanceFactory.h"
/*auto generated*/ #import "NSArray+JavaAPI.h"
/*auto generated*/ #import "NSCalendar+JavaAPI.h"
/*auto generated*/ #import "NSData+Compression.h"
/*auto generated*/ #import "NSData+JavaAPI.h"
/*auto generated*/ #import "NSDate+JavaAPI.h"
/*auto generated*/ #import "NSException+JavaAPI.h"
/*auto generated*/ #import "NSInvocationOperation+JavaAPI.h"
/*auto generated*/ #import "NSLock+JavaAPI.h"
/*auto generated*/ #import "NSMutableString+JavaApi.h"
/*auto generated*/ #import "NSNumber+JavaAPI.h"
/*auto generated*/ #import "NSObject+JavaAPI.h"
/*auto generated*/ #import "NSObject+TrReadWriteLockAdditions.h"
/*auto generated*/ #import "NSString+JavaAPI.h"
/*auto generated*/ #import "NSThread+JavaAPI.h"
/*auto generated*/ #import "NSTimeZone+JavaAPI.h"
/*auto generated*/ #import "NavPoint.h"
/*auto generated*/ #import "NetworkConsumptionData.h"
/*auto generated*/ #import "NetworkState.h"
/*auto generated*/ #import "NetworkStateInfo.h"
/*auto generated*/ #import "NextNotificationCalculator.h"
/*auto generated*/ #import "NextNotificationCalculatorDebug.h"
/*auto generated*/ #import "NextWakeUpCalculatorNaiveImpl.h"
/*auto generated*/ #import "NextWakeUpCalculatorStub.h"
/*auto generated*/ #import "NextWakeUpPrefs.h"
/*auto generated*/ #import "NightVisitCondition.h"
/*auto generated*/ #import "NonBlockFuture.h"
/*auto generated*/ #import "NotificationReminder.h"
/*auto generated*/ #import "NotificationReminderInner.h"
/*auto generated*/ #import "NotificationRemindersManager.h"
/*auto generated*/ #import "NotificationRemindersMemoryStorage.h"
/*auto generated*/ #import "NotificationRemindersPersistentStorage.h"
/*auto generated*/ #import "NotifyAtTimeOfDayTemplate.h"
/*auto generated*/ #import "NotifyType.h"
/*auto generated*/ #import "NullReplaySensor.h"
/*auto generated*/ #import "NullSensorsEnginePlatformImpl.h"
/*auto generated*/ #import "ObserverHelper.h"
/*auto generated*/ #import "PhoneNumber.h"
/*auto generated*/ #import "PhoneStateInfo.h"
/*auto generated*/ #import "PlaceAp.h"
/*auto generated*/ #import "PlaceDataHelper.h"
/*auto generated*/ #import "PlaceDetectionModule.h"
/*auto generated*/ #import "PlaceDetector.h"
/*auto generated*/ #import "PlaceID.h"
/*auto generated*/ #import "PlaceReDetection.h"
/*auto generated*/ #import "PlaceRefPoint.h"
/*auto generated*/ #import "PlaceSignatureAlg.h"
/*auto generated*/ #import "PlaceSnoozeOption.h"
/*auto generated*/ #import "PlaceStatus.h"
/*auto generated*/ #import "PlaceSyncDaoDecorator.h"
/*auto generated*/ #import "PlaceTrigger.h"
/*auto generated*/ #import "PlaceTriggerInner.h"
/*auto generated*/ #import "PlaceTriggerType.h"
/*auto generated*/ #import "PlacesActivityType.h"
/*auto generated*/ #import "PlacesClientUserIdDaoDecorator.h"
/*auto generated*/ #import "PlacesConfig.h"
/*auto generated*/ #import "PlacesDao.h"
/*auto generated*/ #import "PlacesEngineImpl.h"
/*auto generated*/ #import "PlacesTimeFormatUtil.h"
/*auto generated*/ #import "PlacesTriggersManager.h"
/*auto generated*/ #import "PlacesTriggersMemoryStorage.h"
/*auto generated*/ #import "PlacesTriggersPersistentStorage.h"
/*auto generated*/ #import "PlacesUtil.h"
/*auto generated*/ #import "PlaybackFileManager.h"
/*auto generated*/ #import "PointGrid.h"
/*auto generated*/ #import "PointGridList.h"
/*auto generated*/ #import "PolicyChangeInfo.h"
/*auto generated*/ #import "PolicyConfig.h"
/*auto generated*/ #import "PolicyHistoryInfo.h"
/*auto generated*/ #import "PolicyMode.h"
/*auto generated*/ #import "PolicyStats.h"
/*auto generated*/ #import "Polygon.h"
/*auto generated*/ #import "PrefsFileType.h"
/*auto generated*/ #import "PrefsStorage.h"
/*auto generated*/ #import "PrivacyType.h"
/*auto generated*/ #import "ProcessedClusterData.h"
/*auto generated*/ #import "Protocol+JavaAPI.h"
/*auto generated*/ #import "ProxyTSOLogger.h"
/*auto generated*/ #import "Quad.h"
/*auto generated*/ #import "QuadTree.h"
/*auto generated*/ #import "QueryResult.h"
/*auto generated*/ #import "Reachability.h"
/*auto generated*/ #import "ReceiverSensorsDefaultRequest.h"
/*auto generated*/ #import "ReceiverSensorsRequest.h"
/*auto generated*/ #import "RecurrenceDetails.h"
/*auto generated*/ #import "RecurrencePersistenceData.h"
/*auto generated*/ #import "RecurrenceType.h"
/*auto generated*/ #import "RefPoint.h"
/*auto generated*/ #import "ReminderBuildException.h"
/*auto generated*/ #import "ReminderBuildExceptionType.h"
/*auto generated*/ #import "ReminderEndReason.h"
/*auto generated*/ #import "ReminderStatus.h"
/*auto generated*/ #import "ReminderStatusInner.h"
/*auto generated*/ #import "ReminderType.h"
/*auto generated*/ #import "RemindersFactoryInitializer.h"
/*auto generated*/ #import "RemindersManager.h"
/*auto generated*/ #import "RemindersResult.h"
/*auto generated*/ #import "ReplayMode.h"
/*auto generated*/ #import "ResmapledFuse.h"
/*auto generated*/ #import "ResolveBusinessPhoneResponse.h"
/*auto generated*/ #import "ResolveRequestV1.h"
/*auto generated*/ #import "ResolveResponseV1.h"
/*auto generated*/ #import "ResolvedLocation.h"
/*auto generated*/ #import "ResolvedLocationAttribute.h"
/*auto generated*/ #import "ResolvedLocationsResponse.h"
/*auto generated*/ #import "ResolvedPlaceV1.h"
/*auto generated*/ #import "ResolvedResultType.h"
/*auto generated*/ #import "ResolverApiType.h"
/*auto generated*/ #import "ResolverClassPool.h"
/*auto generated*/ #import "ResolverEngine.h"
/*auto generated*/ #import "ResolverFactoryInitializer.h"
/*auto generated*/ #import "ResolverImplTsoSdkConverter.h"
/*auto generated*/ #import "ResolverSdkAuditObj.h"
/*auto generated*/ #import "ResolverSdkRequestParams.h"
/*auto generated*/ #import "ResourceManager.h"
/*auto generated*/ #import "Result.h"
/*auto generated*/ #import "ResultCode.h"
/*auto generated*/ #import "ResultData.h"
/*auto generated*/ #import "ResultEnumConverter.h"
/*auto generated*/ #import "ResultStatus.h"
/*auto generated*/ #import "RetCode.h"
/*auto generated*/ #import "RouteCacheData.h"
/*auto generated*/ #import "RouteDataObjectFactory.h"
/*auto generated*/ #import "RouteDataType.h"
/*auto generated*/ #import "RouteError.h"
/*auto generated*/ #import "RouteErrorDataObj.h"
/*auto generated*/ #import "RouteErrorType.h"
/*auto generated*/ #import "RouteInfo.h"
/*auto generated*/ #import "RouteInfoDataObj.h"
/*auto generated*/ #import "RouteProviderCacheImpl.h"
/*auto generated*/ #import "RouteProviderCacheStub.h"
/*auto generated*/ #import "RouteProviderFactoryInitializer.h"
/*auto generated*/ #import "RouteProviderInnerImpl.h"
/*auto generated*/ #import "RouteSegment.h"
/*auto generated*/ #import "SDKLoader.h"
/*auto generated*/ #import "SDKPolicy.h"
/*auto generated*/ #import "SDKPreferences.h"
/*auto generated*/ #import "ScheduledTaskPersistence.h"
/*auto generated*/ #import "ScheduledTasksManager.h"
/*auto generated*/ #import "SdkDefaultPrefs.h"
/*auto generated*/ #import "SegmentType.h"
/*auto generated*/ #import "SegmentedRouteProviderImpl.h"
/*auto generated*/ #import "SegmentedRouteProviderImplDebug.h"
/*auto generated*/ #import "SemanticData.h"
/*auto generated*/ #import "SemanticDetectedPlace.h"
/*auto generated*/ #import "SemanticDetectionModule.h"
/*auto generated*/ #import "SemanticKey.h"
/*auto generated*/ #import "SemanticPlaceProbabilty.h"
/*auto generated*/ #import "SemanticSensedPlace.h"
/*auto generated*/ #import "SemanticTag.h"
/*auto generated*/ #import "SensedPlace.h"
/*auto generated*/ #import "SensorDumpFileLogger.h"
/*auto generated*/ #import "SensorModeRequest.h"
/*auto generated*/ #import "SensorPlatformMetaData.h"
/*auto generated*/ #import "SensorRawDataAudit.h"
/*auto generated*/ #import "SensorState.h"
/*auto generated*/ #import "SensorStateManager.h"
/*auto generated*/ #import "SensorStateManagerReceiver.h"
/*auto generated*/ #import "SensorStateType.h"
/*auto generated*/ #import "SensorType.h"
/*auto generated*/ #import "SensorsEngine.h"
/*auto generated*/ #import "SensorsEnginePlatformImplTest.h"
/*auto generated*/ #import "ShowAsType.h"
/*auto generated*/ #import "Similarity.h"
/*auto generated*/ #import "SimpleTimer.h"
/*auto generated*/ #import "SimulateInfoParams.h"
/*auto generated*/ #import "SimulatedSensor.h"
/*auto generated*/ #import "SimulatedTimeMode.h"
/*auto generated*/ #import "SingleSensorPolicy.h"
/*auto generated*/ #import "SingletonFactory.h"
/*auto generated*/ #import "SlidingWindow.h"
/*auto generated*/ #import "SnoozeOption.h"
/*auto generated*/ #import "SnoozeOptionsProvider.h"
/*auto generated*/ #import "SnoozeOptionsProviderMock.h"
/*auto generated*/ #import "SnoozeTimeRange.h"
/*auto generated*/ #import "SnoozeType.h"
/*auto generated*/ #import "SourceDataType.h"
/*auto generated*/ #import "SqlPlacesDao.h"
/*auto generated*/ #import "StartSuspendState.h"
/*auto generated*/ #import "StartVipState.h"
/*auto generated*/ #import "State.h"
/*auto generated*/ #import "StatsFileLogger.h"
/*auto generated*/ #import "StatsFileType.h"
/*auto generated*/ #import "StorageFSImpl.h"
/*auto generated*/ #import "StorageManager.h"
/*auto generated*/ #import "StorageType.h"
/*auto generated*/ #import "StorageTypeData.h"
/*auto generated*/ #import "StringDaoQuery.h"
/*auto generated*/ #import "StubPrefsLoader.h"
/*auto generated*/ #import "SyncComparator.h"
/*auto generated*/ #import "SyncDao.h"
/*auto generated*/ #import "SyncFileDao.h"
/*auto generated*/ #import "SyncMemoryDao.h"
/*auto generated*/ #import "SyncObject.h"
/*auto generated*/ #import "SyncSQLCreateUpdateStrategy.h"
/*auto generated*/ #import "SyncSQLDao.h"
/*auto generated*/ #import "SyncSlaveDbs.h"
/*auto generated*/ #import "SystemConfig.h"
/*auto generated*/ #import "SystemUtilsHelper.h"
/*auto generated*/ #import "TimeIQ.h"
/*auto generated*/ #import "TSOAlert.h"
/*auto generated*/ #import "TSOAlertInner.h"
/*auto generated*/ #import "TSOAlertResult.h"
/*auto generated*/ #import "TSOAlertTriggeredResult.h"
/*auto generated*/ #import "TSOAlertUpdatedResult.h"
/*auto generated*/ #import "TSOAlertsEngine.h"
/*auto generated*/ #import "TSOAlertsEngineImpl.h"
/*auto generated*/ #import "TSOAlertsMotChangeListener.h"
/*auto generated*/ #import "TSOAlertsProviderImpl.h"
/*auto generated*/ #import "TSOAlertsProviderStub.h"
/*auto generated*/ #import "TSOAuditObject.h"
/*auto generated*/ #import "TSOBeEvent.h"
/*auto generated*/ #import "TSOCalendarEvent.h"
/*auto generated*/ #import "TSOCalendarEventCache.h"
/*auto generated*/ #import "TSOCalendarMeeting.h"
/*auto generated*/ #import "TSOCalendarsManager.h"
/*auto generated*/ #import "TSOCloudResponse.h"
/*auto generated*/ #import "TSOCompositeEvent.h"
/*auto generated*/ #import "TSOCompositeLoggerPlaces.h"
/*auto generated*/ #import "TSOCoordinate.h"
/*auto generated*/ #import "TSOCoordinateDataObj.h"
/*auto generated*/ #import "TSOCoordinateUtils.h"
/*auto generated*/ #import "TSOCoreFactoryInitializer.h"
/*auto generated*/ #import "TSODBException.h"
/*auto generated*/ #import "TSOEvent.h"
/*auto generated*/ #import "TSOEventAuditObj.h"
/*auto generated*/ #import "TSOEventAuditObjectFactory.h"
/*auto generated*/ #import "TSOEventChangeType.h"
/*auto generated*/ #import "TSOEventTriggeredMsg.h"
/*auto generated*/ #import "TSOEventType.h"
/*auto generated*/ #import "TSOEventsResponse.h"
/*auto generated*/ #import "TSOEventsSync.h"
/*auto generated*/ #import "TSOLocationProviderImplBase.h"
/*auto generated*/ #import "TSOLocationProviderImplNull.h"
/*auto generated*/ #import "TSOLoggerConst.h"
/*auto generated*/ #import "TSOLoggerPlaces.h"
/*auto generated*/ #import "TSOLoggerPlacesFileImpl.h"
/*auto generated*/ #import "TSOLoggerPlacesStdoutImpl.h"
/*auto generated*/ #import "TSONullLoggerPlaces.h"
/*auto generated*/ #import "TSOPlace.h"
/*auto generated*/ #import "TSOPlaceAdapter.h"
/*auto generated*/ #import "TSOPlaceBuilder.h"
/*auto generated*/ #import "TSOPlaceGetSyncRequest.h"
/*auto generated*/ #import "TSOPlacesEngine.h"
/*auto generated*/ #import "TSOPlacesFactoryInitializer.h"
/*auto generated*/ #import "TSOPlacesGetSyncResponse.h"
/*auto generated*/ #import "TSOPlacesWriteRequest.h"
/*auto generated*/ #import "TSOPlacesWriteResponse.h"
/*auto generated*/ #import "TSOPosition.h"
/*auto generated*/ #import "TSORetCodeResponse.h"
/*auto generated*/ #import "TSOSlaveDBSyncResponse.h"
/*auto generated*/ #import "TSOSqlDbException.h"
/*auto generated*/ #import "TSOTimeUtil.h"
/*auto generated*/ #import "TSOTimeUtilDebug.h"
/*auto generated*/ #import "TSOUserIdRequest.h"
/*auto generated*/ #import "TSOUserInfo.h"
/*auto generated*/ #import "TTLRequest.h"
/*auto generated*/ #import "TTLRequestDataObj.h"
/*auto generated*/ #import "TTLRequestResponseDataObj.h"
/*auto generated*/ #import "TTLResponse.h"
/*auto generated*/ #import "TTLResponseDataObj.h"
/*auto generated*/ #import "TemporalsDetectionAlg.h"
/*auto generated*/ #import "TestDetector.h"
/*auto generated*/ #import "Time.h"
/*auto generated*/ #import "TimeConversionUtil.h"
/*auto generated*/ #import "TimeDataHelper.h"
/*auto generated*/ #import "TimeDelaySnoozeOption.h"
/*auto generated*/ #import "TimeFormatUtil.h"
/*auto generated*/ #import "TimeIQApi.h"
/*auto generated*/ #import "TimeManager.h"
/*auto generated*/ #import "TimeRangeSnoozeOption.h"
/*auto generated*/ #import "TimeTrigger.h"
/*auto generated*/ #import "TimeTriggerInner.h"
/*auto generated*/ #import "TimeTriggersManager.h"
/*auto generated*/ #import "TimeTriggersMemoryStorage.h"
/*auto generated*/ #import "TimeTriggersPersistentStorage.h"
/*auto generated*/ #import "TimeUtils.h"
/*auto generated*/ #import "TimeZoneState.h"
/*auto generated*/ #import "TrCondition.h"
/*auto generated*/ #import "TrLock+Protected.h"
/*auto generated*/ #import "TrLock.h"
/*auto generated*/ #import "TrReadWriteLock.h"
/*auto generated*/ #import "TrafficIndication.h"
/*auto generated*/ #import "TransportType.h"
/*auto generated*/ #import "TriggerAudit.h"
/*auto generated*/ #import "TriggerBuildException.h"
/*auto generated*/ #import "TriggerLifeCycleAuditManager.h"
/*auto generated*/ #import "TriggerLifeCycleAuditManagerStub.h"
/*auto generated*/ #import "TriggerStatus.h"
/*auto generated*/ #import "TriggerStatusInner.h"
/*auto generated*/ #import "TriggerType.h"
/*auto generated*/ #import "TriggeredAlertResultType.h"
/*auto generated*/ #import "TriggersListenerList.h"
/*auto generated*/ #import "TriggersManager.h"
/*auto generated*/ #import "TriggersManagerImpl.h"
/*auto generated*/ #import "TruncatedExponentialBackoffAlgorithmHelper.h"
/*auto generated*/ #import "TtlAlertsProviderFactoryInitializer.h"
/*auto generated*/ #import "TtlRouteData.h"
/*auto generated*/ #import "UUIDGenerator.h"
/*auto generated*/ #import "UniqueCalendarEvent.h"
/*auto generated*/ #import "UnknownState.h"
/*auto generated*/ #import "UpdateAlertResultType.h"
/*auto generated*/ #import "UserActionType.h"
/*auto generated*/ #import "UserInputData.h"
/*auto generated*/ #import "UserInputSensorData.h"
/*auto generated*/ #import "UserInputType.h"
/*auto generated*/ #import "UserPlaceInteraction.h"
/*auto generated*/ #import "UserPlaceInteractionType.h"
/*auto generated*/ #import "UserPrefs.h"
/*auto generated*/ #import "UserState.h"
/*auto generated*/ #import "UserStateAudit.h"
/*auto generated*/ #import "UserStateAuditManager.h"
/*auto generated*/ #import "UserStateAuditManagerStub.h"
/*auto generated*/ #import "UserStateChanges.h"
/*auto generated*/ #import "UserStateData.h"
/*auto generated*/ #import "UserStateDataChangesAudit.h"
/*auto generated*/ #import "UserStateDataMotAudit.h"
/*auto generated*/ #import "UserStateDataVisitsAudit.h"
/*auto generated*/ #import "UserStateFactoryInitializer.h"
/*auto generated*/ #import "UserStateFilter.h"
/*auto generated*/ #import "UserStateHistory.h"
/*auto generated*/ #import "UserStateMonitor.h"
/*auto generated*/ #import "UserStateType.h"
/*auto generated*/ #import "V2Params.h"
/*auto generated*/ #import "Vector2D.h"
/*auto generated*/ #import "VipEventPersistency.h"
/*auto generated*/ #import "VipState.h"
/*auto generated*/ #import "VipStateDataProvider.h"
/*auto generated*/ #import "VipStateType.h"
/*auto generated*/ #import "Visit.h"
/*auto generated*/ #import "VisitDetectionModule.h"
/*auto generated*/ #import "VisitFuseDetectorImpl.h"
/*auto generated*/ #import "VisitInPlaceModule.h"
/*auto generated*/ #import "VisitTimeofDay.h"
/*auto generated*/ #import "VisitWifiDetectorImpl.h"
/*auto generated*/ #import "VisitedPlace.h"
/*auto generated*/ #import "VisitedPlaceConfidence.h"
/*auto generated*/ #import "VisitedPlaces.h"
/*auto generated*/ #import "VisitsDetetionListener.h"
/*auto generated*/ #import "WaitTimer.h"
/*auto generated*/ #import "WeightedMovingAverage.h"
/*auto generated*/ #import "WifiBaseSensorData.h"
/*auto generated*/ #import "WifiData.h"
/*auto generated*/ #import "WifiFingerPrintBuilder.h"
/*auto generated*/ #import "WifiFingerPrintCollection.h"
/*auto generated*/ #import "WifiScan.h"
/*auto generated*/ #import "WifiScansWindow.h"
/*auto generated*/ #import "WifiSignature.h"
/*auto generated*/ #import "WifiSimilarityAlg.h"
/*auto generated*/ #import "WifiSource.h"
/*auto generated*/ #import "WifiState.h"
/*auto generated*/ #import "WorkingHoursVisitCondition.h"
/*auto generated*/ #import "XY.h"
/*auto generated*/ #import "eAuditLabels.h"
/*auto generated*/ #import "eDayOfReminder.h"
/*auto generated*/ #import "eExtendedEventReminderType.h"
/*auto generated*/ #import "eExtendedEventState.h"
/*auto generated*/ #import "eTriggerBuildExceptionType.h"
/*auto generated*/ #import "nanotime.h"
/*** INSERTION END ***/