//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/time/TimeTriggersPersistentStorage.java
//

#ifndef _TimeTriggersPersistentStorage_H_
#define _TimeTriggersPersistentStorage_H_

#import "JBClass.h"
#import "JBHashSet.h"

#import "JB.h"
#import "ABaseTriggersPersistentStorage.h"
#import "ITimeTriggerStorage.h"

/**
 @brief Created by Yaron Abramovich on 19.5.15
 */
@interface TimeTriggersPersistentStorage : ABaseTriggersPersistentStorage < ITimeTriggerStorage > {
}

- (Set*)getAllTriggersForTimeWithLong:(long64)time;

- (Class )getClassType;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void TimeTriggersPersistentStorage_init() {}

typedef TimeTriggersPersistentStorage ComIntelWearablePlatformTimeiqTriggersTimeTimeTriggersPersistentStorage;

#endif // _TimeTriggersPersistentStorage_H_
