//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/ttlAlerts/TSOAlertsProviderImpl.java
//

#ifndef _TSOAlertsProviderImpl_H_
#define _TSOAlertsProviderImpl_H_

@class AlertState;
#import "NSNumber+JavaAPI.h"
@class ResultData;
@class TSOAlert;
@class TSOAlertInner;
@class TSOAlertsProviderImpl_CalcAlertData;
@class TSOCoordinate;
@class UpdateAlertResultType;
@protocol ILocationProvider;
@protocol INextNotificationCalculator;
@protocol INextWakeUpCalculator;
@protocol IRouteProviderInner;
@protocol ITSOAlarmManager;
@protocol ITSOAlertListener;
@protocol ITSOAlertsMotChangeListener;
@protocol ITSOAlertsRepository;
@protocol ITSOLogger;
@protocol ITSOTimeUtil;
@protocol IUserStateManagerModule;
#import "JBExecutorService.h"
#import "JBArrayList.h"

#import "JB.h"
#import "ITSOAlarmListener.h"
#import "IAlertsOnMotChangeListener.h"
#import "ITSOAlertProvider.h"
#import "JBRunnable.h"

/**
 @brief Created by smoradof on 12/16/2014.
 */
@interface TSOAlertsProviderImpl : NSObject < ITSOAlertProvider, ITSOAlarmListener, IAlertsOnMotChangeListener > {
 @public
  id<ITSOAlertsRepository> m_alertRepository_;
  id<ITSOAlarmManager> m_alarmManager_;
  id<ITSOLogger> m_logger_;
  id<ITSOTimeUtil> m_timeUtil_;
  id<INextNotificationCalculator> m_nextAlertCalculator_;
  id<INextWakeUpCalculator> m_nextWakeUpCalculator_;
  id<IRouteProviderInner> m_routeProvider_;
  id<IUserStateManagerModule> m_userStateManager_;
  id<ITSOAlertsMotChangeListener> m_alertsMotChangeListener_;
  id<ILocationProvider> m_locationProvider_;
  id<ITSOAlertListener> m_tsoAlertsListener_;
}

- (instancetype)init;

- (instancetype)initWithITSOAlertsRepository:(id<ITSOAlertsRepository>)alertRepository
                        withITSOAlarmManager:(id<ITSOAlarmManager>)alarmManager
                              withITSOLogger:(id<ITSOLogger>)logger
                            withITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil
             withINextNotificationCalculator:(id<INextNotificationCalculator>)nextAlertCalculator
                   withINextWakeUpCalculator:(id<INextWakeUpCalculator>)nextWakeUpCalculator
                     withIRouteProviderInner:(id<IRouteProviderInner>)routeProvider
                 withIUserStateManagerModule:(id<IUserStateManagerModule>)userStateManager
             withITSOAlertsMotChangeListener:(id<ITSOAlertsMotChangeListener>)alertsMotChangeListener
                       withILocationProvider:(id<ILocationProvider>)locationProvider;

- (void)init__WithITSOAlertListener:(id<ITSOAlertListener>)listener OBJC_METHOD_FAMILY_NONE;

- (void)addAlertWithTSOAlert:(TSOAlert *)tsoAlert;

- (void)onMotChangeWithNSString:(NSString *)alertId;

- (void)calcAlertInThreadPoolWithNSString:(NSString *)alertId;

- (void)calcAlertWithNSString:(NSString *)alertId;

- (boolean)calcAlertBeforeStartTimeWithNSString:(NSString *)alertId
                               withTSOAlertInner:(TSOAlertInner *)tsoAlertInner
         withTSOAlertsProviderImpl_CalcAlertData:(TSOAlertsProviderImpl_CalcAlertData *)calcAlertData;

- (void)calcAlertAfterStartTimeWithNSString:(NSString *)alertId
                          withTSOAlertInner:(TSOAlertInner *)tsoAlertInner
    withTSOAlertsProviderImpl_CalcAlertData:(TSOAlertsProviderImpl_CalcAlertData *)calcAlertData;

- (UpdateAlertResultType *)setNextNotifyWithLong:(long64)nextAlertTime
                                        withNSString:(NSString *)alertId
                       withUpdateAlertResultType:(UpdateAlertResultType *)updateAlertResultType;

- (ResultData *)getAndSetRouteWithTSOAlert:(TSOAlert *)tsoAlert
                         withTSOCoordinate:(TSOCoordinate *)userLocation;

- (Long *)setNextWakeUpWithResultData:(ResultData *)nextWakeUpTime
                           withAlertState:(AlertState *)alertState
                                 withNSString:(NSString *)alertId;

- (UpdateAlertResultType *)retryOrEndAlertIfNeededWithTSOAlertInner:(TSOAlertInner *)tsoAlertInner
                                                      withTSOCoordinate:(TSOCoordinate *)userLocation
                                                         withResultData:(ResultData *)nextAlertTime
                                                         withResultData:(ResultData *)nextWakeUpTime
                                          withUpdateAlertResultType:(UpdateAlertResultType *)updateAlertResultType;

- (void)sendAlertUpdateWithTSOAlertInner:(TSOAlertInner *)tsoAlertInner
           withUpdateAlertResultType:(UpdateAlertResultType *)updateAlertResultType
                        withLong:(Long *)nextAlertTimeAsLong
                        withLong:(Long *)nextWakeUpTimeAsLong;

- (ResultData *)getUserLocation;

- (void)setAlarmWithNSString:(NSString *)alertId
                withNSString:(NSString *)action
                    withLong:(long64)delay;

- (void)onAlarmWithNSString:(NSString *)action
               withNSString:(NSString *)id_
               withNSString:(NSString *)data;

- (void)notifyInThreadPoolWithNSString:(NSString *)alertId;

- (void)notifyAlertWithNSString:(NSString *)alertId;

- (ArrayList*)getAllAlerts;

- (TSOAlert *)getAlertWithIdWithNSString:(NSString *)alertId;

- (boolean)removeAlertWithNSString:(NSString *)alertId;

- (boolean)removeAllAlerts;

- (void)cancelAlarmWithNSString:(NSString *)alertId;

- (void)cancelWakeUpAlarmWithNSString:(NSString *)alertId;

- (void)onDestroy;

- (Long *)getNextReminderTimeDiffWithNSString:(NSString *)alertId;

- (void)copyAllFieldsTo:(TSOAlertsProviderImpl *)other;

@end

FOUNDATION_EXPORT BOOL TSOAlertsProviderImpl_initialized;
J2OBJC_STATIC_INIT(TSOAlertsProviderImpl)

//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_alertRepository_, id<ITSOAlertsRepository>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_alarmManager_, id<ITSOAlarmManager>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_logger_, id<ITSOLogger>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_timeUtil_, id<ITSOTimeUtil>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_nextAlertCalculator_, id<INextNotificationCalculator>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_nextWakeUpCalculator_, id<INextWakeUpCalculator>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_routeProvider_, id<IRouteProviderInner>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_userStateManager_, id<IUserStateManagerModule>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_alertsMotChangeListener_, id<ITSOAlertsMotChangeListener>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_locationProvider_, id<ILocationProvider>)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl, m_tsoAlertsListener_, id<ITSOAlertListener>)

FOUNDATION_EXPORT NSString *TSOAlertsProviderImpl_TAG_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertsProviderImpl, TAG_, NSString *)

FOUNDATION_EXPORT NSString *TSOAlertsProviderImpl_WAKE_UP_ACTION_NOTIFY_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertsProviderImpl, WAKE_UP_ACTION_NOTIFY_, NSString *)

FOUNDATION_EXPORT NSString *TSOAlertsProviderImpl_WAKE_UP_ACTION_WAKE_UP_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertsProviderImpl, WAKE_UP_ACTION_WAKE_UP_, NSString *)

FOUNDATION_EXPORT NSString *TSOAlertsProviderImpl_WAKE_UP_ACTION_RETRY_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertsProviderImpl, WAKE_UP_ACTION_RETRY_, NSString *)

FOUNDATION_EXPORT id<ExecutorService> TSOAlertsProviderImpl_m_threadPool_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertsProviderImpl, m_threadPool_, id<ExecutorService>)

typedef TSOAlertsProviderImpl ComIntelWearablePlatformTimeiqTtlAlertsTSOAlertsProviderImpl;

@interface TSOAlertsProviderImpl_calcAlertRunnable : NSObject < Runnable > {
 @public
  TSOAlertsProviderImpl *this$0_;
  NSString *m_alertId_;
}

- (instancetype)initWithTSOAlertsProviderImpl:(TSOAlertsProviderImpl *)outer$
                                 withNSString:(NSString *)alertId;

- (void)run;

- (void)copyAllFieldsTo:(TSOAlertsProviderImpl_calcAlertRunnable *)other;

@end

__attribute__((always_inline)) inline void TSOAlertsProviderImpl_calcAlertRunnable_init() {}

//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_calcAlertRunnable, this$0_, TSOAlertsProviderImpl *)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_calcAlertRunnable, m_alertId_, NSString *)

@interface TSOAlertsProviderImpl_notifyRunnable : NSObject < Runnable > {
 @public
  TSOAlertsProviderImpl *this$0_;
  NSString *m_alertId_;
}

- (instancetype)initWithTSOAlertsProviderImpl:(TSOAlertsProviderImpl *)outer$
                                 withNSString:(NSString *)alertId;

- (void)run;

- (void)copyAllFieldsTo:(TSOAlertsProviderImpl_notifyRunnable *)other;

@end

__attribute__((always_inline)) inline void TSOAlertsProviderImpl_notifyRunnable_init() {}

//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_notifyRunnable, this$0_, TSOAlertsProviderImpl *)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_notifyRunnable, m_alertId_, NSString *)

@interface TSOAlertsProviderImpl_CalcAlertData : NSObject {
 @public
  UpdateAlertResultType *updateAlertResultType_;
  Long *nextAlertTimeAsLong_;
  Long *nextWakeUpTimeAsLong_;
}

- (instancetype)init;

- (instancetype)initWithUpdateAlertResultType:(UpdateAlertResultType *)updateAlertResultType
                                 withLong:(Long *)nextAlertTimeAsLong
                                 withLong:(Long *)nextWakeUpTimeAsLong;

- (void)copyAllFieldsTo:(TSOAlertsProviderImpl_CalcAlertData *)other;

@end

__attribute__((always_inline)) inline void TSOAlertsProviderImpl_CalcAlertData_init() {}

//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_CalcAlertData, updateAlertResultType_, UpdateAlertResultType *)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_CalcAlertData, nextAlertTimeAsLong_, Long *)
//J2OBJC_FIELD_SETTER(TSOAlertsProviderImpl_CalcAlertData, nextWakeUpTimeAsLong_, Long *)

#endif // _TSOAlertsProviderImpl_H_
