//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/events/TSOCalendarEvent.java
//

#ifndef _TSOCalendarEvent_H_
#define _TSOCalendarEvent_H_

#import "NSNumber+JavaAPI.h"
@class TSOCalendarEvent_TSOCalendarEventBuilder;
@class TSOPlace;
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#import "TSOEvent.h"

/**
 @brief Created by eskoran on 20/05/2015.
 */
@interface TSOCalendarEvent : TSOEvent {
 @public
  boolean isFromBe__;
  NSString *meetingLocationField_;
  ArrayList* attendees_;
  NSString *organizerEmail_;
  JBBoolean *organizer_;
  JBBoolean *allDayEvent_;
  JBBoolean *recurrent_;
}

/**
 @brief for json use only!!!!!
 */
- (instancetype)init;

- (instancetype)initWithTSOCalendarEvent_TSOCalendarEventBuilder:(TSOCalendarEvent_TSOCalendarEventBuilder *)builder;

- (boolean)isFromBe;

- (NSString *)getMeetingLocationField;

- (void)setResolvedLocationWithTSOPlace:(TSOPlace *)resolvedLocation;

- (ArrayList*)getAttendees;

- (NSString *)getOrganizerEmail;

- (JBBoolean *)isOrganizer;

- (JBBoolean *)isAllDayEvent;

- (JBBoolean *)isRecurrent;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSString *)description;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(TSOCalendarEvent *)other;

@end

__attribute__((always_inline)) inline void TSOCalendarEvent_init() {}

//J2OBJC_FIELD_SETTER(TSOCalendarEvent, meetingLocationField_, NSString *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent, attendees_, ArrayList*)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent, organizerEmail_, NSString *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent, organizer_, JBBoolean *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent, allDayEvent_, JBBoolean *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent, recurrent_, JBBoolean *)

typedef TSOCalendarEvent ComIntelWearablePlatformTimeiqEventsTSOCalendarEvent;

@interface TSOCalendarEvent_TSOCalendarEventBuilder : TSOEvent_TSOEventBuilder {
 @public
  boolean isFromBe__;
  NSString *meetingLocationField__;
  ArrayList* attendees__;
  NSString *organizerEmail__;
  JBBoolean *isOrganizer__;
  JBBoolean *allDayEvent__;
  JBBoolean *recurrent__;
}

- (instancetype)initWithTSOPlace:(TSOPlace *)location
                        withLong:(long64)arrivalTime;

- (instancetype)initWithTSOCalendarEvent:(TSOCalendarEvent *)calendarEvent;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)isFromBeWithBoolean:(boolean)isFromBe;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)meetingLocationFieldWithNSString:(NSString *)meetingLocationField;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)attendeesWithJavaUtilList:(ArrayList*)attendees;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)organizerEmailWithNSString:(NSString *)organizerEmail;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)isOrganizerWithJBBoolean:(JBBoolean *)isOrganizer;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)allDayEventWithJBBoolean:(JBBoolean *)allDayEvent;

- (TSOCalendarEvent_TSOCalendarEventBuilder *)recurrentWithJBBoolean:(JBBoolean *)recurrent;

- (TSOCalendarEvent *)build;

- (void)copyAllFieldsTo:(TSOCalendarEvent_TSOCalendarEventBuilder *)other;

@end

__attribute__((always_inline)) inline void TSOCalendarEvent_TSOCalendarEventBuilder_init() {}

//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, meetingLocationField__, NSString *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, attendees__, ArrayList*)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, organizerEmail__, NSString *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, isOrganizer__, JBBoolean *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, allDayEvent__, JBBoolean *)
//J2OBJC_FIELD_SETTER(TSOCalendarEvent_TSOCalendarEventBuilder, recurrent__, JBBoolean *)

#endif // _TSOCalendarEvent_H_
