//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/events/TSOEventsSync.java
//

#ifndef _TSOEventsSync_H_
#define _TSOEventsSync_H_

@class EventContext;
@class TSOEventChangeType;
@class TSOEventType;
@protocol IEventSyncListener;
@protocol ITSOEvent;
#import "JBHashtable.h"
#import "JBHashSet.h"

#import "JB.h"
#import "JBRunnable.h"

/**
 @brief Created by stzour on 11/05/2015.
 */
@interface TSOEventsSync : NSObject {
 @public
  HashMap* listenersMap_;
}

- (void)registerForNotificationsWithTSOEventType:(TSOEventType *)listenerOf
                              withIEventSyncListener:(id<IEventSyncListener>)listener;

- (void)notifyChangeWithITSOEvent:(id<ITSOEvent>)changedEvent
       withTSOEventChangeType:(TSOEventChangeType *)changeType
                 withEventContext:(EventContext *)eventContext;

- (void)notifyChangeWithJavaUtilSet:(Set*)changedEvents
         withTSOEventChangeType:(TSOEventChangeType *)changeType
                   withEventContext:(EventContext *)eventContext;

- (NSString *)getSyncTypeWithITSOEvent:(id<ITSOEvent>)changedEvent;

- (instancetype)init;

- (void)copyAllFieldsTo:(TSOEventsSync *)other;

@end

FOUNDATION_EXPORT BOOL TSOEventsSync_initialized;
J2OBJC_STATIC_INIT(TSOEventsSync)

//J2OBJC_FIELD_SETTER(TSOEventsSync, listenersMap_, HashMap*)

FOUNDATION_EXPORT NSString *TSOEventsSync_BE_IN_CALENDAR_;
J2OBJC_STATIC_FIELD_GETTER(TSOEventsSync, BE_IN_CALENDAR_, NSString *)

FOUNDATION_EXPORT NSString *TSOEventsSync_CALENDAR_FROM_BE_;
J2OBJC_STATIC_FIELD_GETTER(TSOEventsSync, CALENDAR_FROM_BE_, NSString *)

FOUNDATION_EXPORT HashMap* TSOEventsSync_updateRelations_;
J2OBJC_STATIC_FIELD_GETTER(TSOEventsSync, updateRelations_, HashMap*)
//J2OBJC_STATIC_FIELD_SETTER(TSOEventsSync, updateRelations_, HashMap*)

typedef TSOEventsSync ComIntelWearablePlatformTimeiqEventsTSOEventsSync;

@interface TSOEventsSync_$1 : NSObject < Runnable > {
 @public
  id<IEventSyncListener> val$listenerTOUpdate_;
  Set* val$changedEvents_;
  TSOEventChangeType *val$changeType_;
  EventContext *val$eventContext_;
}

- (void)run;

- (instancetype)initWithIEventSyncListener:(id<IEventSyncListener>)capture$0
                           withJavaUtilSet:(Set*)capture$1
                withTSOEventChangeType:(TSOEventChangeType *)capture$2
                          withEventContext:(EventContext *)capture$3;

@end

__attribute__((always_inline)) inline void TSOEventsSync_$1_init() {}

//J2OBJC_FIELD_SETTER(TSOEventsSync_$1, val$listenerTOUpdate_, id<IEventSyncListener>)
//J2OBJC_FIELD_SETTER(TSOEventsSync_$1, val$changedEvents_, Set*)
//J2OBJC_FIELD_SETTER(TSOEventsSync_$1, val$changeType_, TSOEventChangeType *)
//J2OBJC_FIELD_SETTER(TSOEventsSync_$1, val$eventContext_, EventContext *)

#endif // _TSOEventsSync_H_
