//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/api/events/TSOEventTriggeredMsg.java
//

#ifndef _TSOEventTriggeredMsg_H_
#define _TSOEventTriggeredMsg_H_

@class ResultCode;
@protocol IEvent;
@protocol IRouteData;

#import "JB.h"

/**
 @brief This is the message that is sent as a trigger for a specific event.
 It contains the event itself and data regarding the route to the event location.
 */
@interface TSOEventTriggeredMsg : NSObject {
 @public
  id<IEvent> event_;
  id<IRouteData> routeData_;
  ResultCode *status_;
}

/**
 @brief Returns information regarding the route from the user's current location to the event location
 @return IRouteData which describes optimised route between the user's current location to the event location
 */
- (id<IRouteData>)getRouteData;

/**
 @brief Sets information regarding the route from the user's current location to the event location
 @param routeData  IRouteData which describes optimised route between the user's current location to the event location
 */
- (void)setRouteDataWithIRouteData:(id<IRouteData>)routeData;

/**
 @brief Returns the event which is triggered
 @return event which is triggered
 */
- (id<IEvent>)getEvent;

/**
 @brief Sets the event which is triggered
 @param event the event which is triggered
 */
- (void)setEventWithIEvent:(id<IEvent>)event;

/**
 @brief Sets IRouteData related requests status
 @param status eResultCode which describes IRouteData related requests status
 */
- (void)setStatusWithResultCode:(ResultCode *)status;

- (instancetype)init;

- (void)copyAllFieldsTo:(TSOEventTriggeredMsg *)other;

@end

__attribute__((always_inline)) inline void TSOEventTriggeredMsg_init() {}

//J2OBJC_FIELD_SETTER(TSOEventTriggeredMsg, event_, id<IEvent>)
//J2OBJC_FIELD_SETTER(TSOEventTriggeredMsg, routeData_, id<IRouteData>)
//J2OBJC_FIELD_SETTER(TSOEventTriggeredMsg, status_, ResultCode *)

typedef TSOEventTriggeredMsg ComIntelWearablePlatformTimeiqApiEventsTSOEventTriggeredMsg;

#endif // _TSOEventTriggeredMsg_H_
