//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/visitinplacemodule/VisitedPlace.java
//

#ifndef _VisitedPlace_H_
#define _VisitedPlace_H_

@class PlaceID;
@class State;
@class TSOCoordinate;
@class VisitedPlaceConfidence;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"
#import "ATSOBaseDBObject.h"

/**
 @brief Created by ylempert on 13-May-15.
 */
@interface VisitedPlace : ATSOBaseDBObject < IMappable > {
 @public
  TSOCoordinate *coord_;
  VisitedPlaceConfidence *confidence_;
  PlaceID *placeId_;
  NSString *detectedId_;
  NSString *manualId_;
  long64 timestamp_;
  NSString *interactionId_;
  State *state_;
}

- (instancetype)init;

/**
 @brief Constructor
 @param coord
 @param confidence
 @param placeId
 @param timeStamp
 @param interactionId
 @param state
 */
- (instancetype)initWithTSOCoordinate:(TSOCoordinate *)coord
       withVisitedPlaceConfidence:(VisitedPlaceConfidence *)confidence
                          withPlaceID:(PlaceID *)placeId
                         withNSString:(NSString *)manualId
                         withNSString:(NSString *)detectedId
                             withLong:(long64)timeStamp
                         withNSString:(NSString *)interactionId
                        withState:(State *)state;

- (instancetype)initWithPlaceID:(PlaceID *)placeId;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (State *)getState;

- (NSString *)getInteractionId;

- (void)setInteractionIdWithNSString:(NSString *)interactionId;

- (TSOCoordinate *)getLocation;

- (VisitedPlaceConfidence *)getConfidence;

- (PlaceID *)getPlaceId;

- (long64)getTimeStamp;

- (void)setTimeStampWithLong:(long64)timeStamp;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (NSString *)description;

- (void)print;

- (void)updateStateWithTSOCoordinate:(TSOCoordinate *)coord
      withVisitedPlaceConfidence:(VisitedPlaceConfidence *)confidence
                            withLong:(long64)timestamp
                       withState:(State *)state;

- (NSString *)getManualPlaceId;

- (NSString *)getDetectedPlaceId;

- (void)copyAllFieldsTo:(VisitedPlace *)other;

@end

__attribute__((always_inline)) inline void VisitedPlace_init() {}

//J2OBJC_FIELD_SETTER(VisitedPlace, coord_, TSOCoordinate *)
//J2OBJC_FIELD_SETTER(VisitedPlace, confidence_, VisitedPlaceConfidence *)
//J2OBJC_FIELD_SETTER(VisitedPlace, placeId_, PlaceID *)
//J2OBJC_FIELD_SETTER(VisitedPlace, detectedId_, NSString *)
//J2OBJC_FIELD_SETTER(VisitedPlace, manualId_, NSString *)
//J2OBJC_FIELD_SETTER(VisitedPlace, interactionId_, NSString *)
//J2OBJC_FIELD_SETTER(VisitedPlace, state_, State *)

FOUNDATION_EXPORT NSString *VisitedPlace_COORD_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, COORD_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_CONFIDENCE_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, CONFIDENCE_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_PLACE_ID_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, PLACE_ID_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_DETECTED_ID_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, DETECTED_ID_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_MANUAL_ID_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, MANUAL_ID_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_TIMESTAMP_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, TIMESTAMP_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_INTERACTION_ID_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, INTERACTION_ID_, NSString *)

FOUNDATION_EXPORT NSString *VisitedPlace_STATE_;
J2OBJC_STATIC_FIELD_GETTER(VisitedPlace, STATE_, NSString *)

typedef VisitedPlace ComIntelWearablePlatformTimeiqPlacesModulesVisitinplacemoduleVisitedPlace;

#endif // _VisitedPlace_H_
