//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/ABaseTriggersPersistentStorage.java
//

#ifndef _ABaseTriggersPersistentStorage_H_
#define _ABaseTriggersPersistentStorage_H_

@class BaseTriggerInner;
#import "JBClass.h"
@protocol IGenericDaoImpl;
#import "JBHashSet.h"

#import "JB.h"
#include "ABaseTriggersMemoryStorage.h"

/**
 @brief Created by Yaron Abramovich on 25.5.15
 */
@interface ABaseTriggersPersistentStorage : ABaseTriggersMemoryStorage {
 @public
  Class m_type_;
  id<IGenericDaoImpl> m_db_;
}

- (Class )getClassType;

- (instancetype)init;

- (boolean)addTriggerWithITriggerInner:(BaseTriggerInner *)trigger;

- (boolean)removeTriggerWithITriggerInner:(BaseTriggerInner *)trigger;

- (boolean)removeTriggersWithJavaUtilCollection:(Set*)toRemove;

- (boolean)removeAllTriggersWithNSString:(NSString *)listenerId;

- (boolean)updateWithBaseTriggerInner:(BaseTriggerInner *)trigger;

/**
 @brief Get the trigger from the actual persistent storage and not the memory
 */
- (id)getTriggerDebugWithNSString:(NSString *)triggerId;

- (void)copyAllFieldsTo:(ABaseTriggersPersistentStorage *)other;

@end

__attribute__((always_inline)) inline void ABaseTriggersPersistentStorage_init() {}

//J2OBJC_FIELD_SETTER(ABaseTriggersPersistentStorage, m_type_, Class )
//J2OBJC_FIELD_SETTER(ABaseTriggersPersistentStorage, m_db_, id<IGenericDaoImpl>)

typedef ABaseTriggersPersistentStorage ComIntelWearablePlatformTimeiqTriggersABaseTriggersPersistentStorage;

#endif // _ABaseTriggersPersistentStorage_H_
