//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/activity/ActivitySensorData.java
//

#ifndef _ActivitySensorData_H_
#define _ActivitySensorData_H_

#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "BaseSensorData.h"

#define ActivitySensorData_kInVehicle 0
#define ActivitySensorData_kOnBicycle 1
#define ActivitySensorData_kOnFoot 2
#define ActivitySensorData_kRunning 8
#define ActivitySensorData_kStill 3
#define ActivitySensorData_kTilting 5
#define ActivitySensorData_kUnknown 4
#define ActivitySensorData_kWalking 7

/**
 @brief Created by aeirew on 17/12/2014.
 */
@interface ActivitySensorData : BaseSensorData {
 @public
  ArrayList* m_probableActivities_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)summary
                        withLong:(long64)timeStamp
                withJavaUtilList:(ArrayList*)probableActivities;

- (ArrayList*)getProbableActivities;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(ActivitySensorData *)other;

@end

__attribute__((always_inline)) inline void ActivitySensorData_init() {}

//J2OBJC_FIELD_SETTER(ActivitySensorData, m_probableActivities_, ArrayList*)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kInVehicle, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kOnBicycle, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kOnFoot, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kStill, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kUnknown, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kTilting, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kWalking, int)

J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, kRunning, int)

FOUNDATION_EXPORT NSString *ActivitySensorData_PROBABLE_ACTIVITIES_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ActivitySensorData, PROBABLE_ACTIVITIES_FIELD_, NSString *)

typedef ActivitySensorData ComIntelWearablePlatformTimeiqSensorsDatatypesActivityActivitySensorData;

#endif // _ActivitySensorData_H_
