//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/ttlAlerts/repository/AlertsRepository.java
//

#ifndef _AlertsRepository_H_
#define _AlertsRepository_H_

@class AlertState;
#import "NSNumber+JavaAPI.h"
@class ResultData;
@class TSOAlert;
@class TSOAlertInner;
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "ITSOAlertsRepository.h"

/**
 @brief Created by smoradof on 12/16/2014.
 <BR> In any case an alert ID is no longer valid, the request is ignored without throwing an exception, and the return value will be null where applicable.
 */
@interface AlertsRepository : NSObject < ITSOAlertsRepository > {
 @public
  HashMap* m_alertsMap_;
}

- (TSOAlertInner *)addAlertWithTSOAlert:(TSOAlert *)tsoAlert;

- (TSOAlertInner *)getAlertDataWithTSOAlert:(TSOAlert *)tsoAlert;

- (TSOAlert *)getAlertWithIdWithNSString:(NSString *)tsoAlertId;

- (TSOAlertInner *)getAlertDataWithIdWithNSString:(NSString *)alertId;

- (boolean)deleteAlertWithNSString:(NSString *)tsoAlertId;

- (void)deleteAll;

- (ArrayList*)getAllAlertsData;

- (ArrayList*)getAllAlertsDataSortedByCreationTime;

/**
 @brief Set a new state for an alert
 @param tsoAlertId the ID of the alert that will be changed
 @param newState the new state of the alert (may throw IllegalArgumentException if null)
 */
- (void)setAlertStateWithNSString:(NSString *)tsoAlertId
               withAlertState:(AlertState *)newState;

/**
 @brief this private method MUST be called from a synchronized code !!
 @param tsoAlertInner
 @param newState
 */
- (void)setAlertStateWithTSOAlertInner:(TSOAlertInner *)tsoAlertInner
                    withAlertState:(AlertState *)newState;

- (void)setAlertWakeUpWithNSString:(NSString *)tsoAlertId
                          withLong:(long64)wakeUpTime
                withAlertState:(AlertState *)newState;

- (void)setLastRouteDataWithNSString:(NSString *)tsoAlertId
                      withResultData:(ResultData *)ttlRouteDataResult;

- (ArrayList*)getAllAlerts;

- (ArrayList*)getAllAlertsSortedByCreationTime;

- (Long *)getNextReminderTimeDiffWithNSString:(NSString *)tsoAlertId;

/**
 @return false if there is no other reminder to move to
 */
- (boolean)moveToNextReminderWithNSString:(NSString *)tsoAlertId;

/**
 @param tsoAlertId
 @return false if there is no other reminder to move to
 */
- (boolean)hasNextReminderWithNSString:(NSString *)tsoAlertId;

- (instancetype)init;

- (void)copyAllFieldsTo:(AlertsRepository *)other;

@end

FOUNDATION_EXPORT BOOL AlertsRepository_initialized;
J2OBJC_STATIC_INIT(AlertsRepository)

//J2OBJC_FIELD_SETTER(AlertsRepository, m_alertsMap_, HashMap*)

FOUNDATION_EXPORT id AlertsRepository_m_syncLock_;
J2OBJC_STATIC_FIELD_GETTER(AlertsRepository, m_syncLock_, id)

typedef AlertsRepository ComIntelWearablePlatformTimeiqTtlAlertsRepositoryAlertsRepository;

#endif // _AlertsRepository_H_
