//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/wifi/ApStat.java
//

#ifndef _ApStat_H_
#define _ApStat_H_

@class AssociatedWifiSpot;
#import "NSNumber+JavaAPI.h"
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

@interface ApStat : NSObject < IMappable > {
 @public
  ArrayList* rssList_;
  Integer *median_;
  double sigmaOfSquares_;
  double sigma_;
  double variance_;
  NSString *id__;
}

- (void)addApWithAssociatedWifiSpot:(AssociatedWifiSpot *)ap;

- (NSString *)print;

- (double)getStdErr;

- (int)getElements;

- (int)getMedian;

- (void)updateMedian;

- (NSString *)getId;

- (NSString *)description;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (instancetype)init;

- (void)copyAllFieldsTo:(ApStat *)other;

@end

__attribute__((always_inline)) inline void ApStat_init() {}

//J2OBJC_FIELD_SETTER(ApStat, rssList_, ArrayList*)
//J2OBJC_FIELD_SETTER(ApStat, median_, Integer *)
//J2OBJC_FIELD_SETTER(ApStat, id__, NSString *)

typedef ApStat ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleWifiApStat;

#endif // _ApStat_H_
