//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/extended_events/templates/AReminderTemplate.java
//

#ifndef _AReminderTemplate_H_
#define _AReminderTemplate_H_

@class eExtendedEventReminderType;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by smoradof on 7/28/2015.
 */
@interface AReminderTemplate : NSObject < IMappable > {
 @public
  eExtendedEventReminderType *mType_;
  boolean mIsActive_;
  NSString *mUiControllerId_;
}

- (instancetype)init;

- (instancetype)initWithEExtendedEventReminderType:(eExtendedEventReminderType *)type
                                           withBoolean:(boolean)isActive
                                          withNSString:(NSString *)uiControllerId;

- (AReminderTemplate *)clone;

- (eExtendedEventReminderType *)getType;

- (boolean)isActive;

- (void)setIsActiveWithBoolean:(boolean)m_isActive;

- (NSString *)getUiControllerId;

- (void)setUiControllerIdWithNSString:(NSString *)uiControllerId;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSString *)description;

- (void)copyAllFieldsTo:(AReminderTemplate *)other;

@end

__attribute__((always_inline)) inline void AReminderTemplate_init() {}

//J2OBJC_FIELD_SETTER(AReminderTemplate, mType_, eExtendedEventReminderType *)
//J2OBJC_FIELD_SETTER(AReminderTemplate, mUiControllerId_, NSString *)

FOUNDATION_EXPORT NSString *AReminderTemplate_TYPE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(AReminderTemplate, TYPE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *AReminderTemplate_IS_ACTIVE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(AReminderTemplate, IS_ACTIVE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *AReminderTemplate_UI_CONTROLLER_ID_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(AReminderTemplate, UI_CONTROLLER_ID_FIELD_, NSString *)

typedef AReminderTemplate ComIntelWearablePlatformTimeiqExtended_eventsTemplatesAReminderTemplate;

#endif // _AReminderTemplate_H_
