//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/abstracts/ATSOPlace.java
//

#ifndef _ATSOPlace_H_
#define _ATSOPlace_H_

@class Coord;
#import "JBHashtable.h"

#import "JB.h"
#include "ATSOSyncDbObject.h"
#include "ITSOPlace.h"

@interface ATSOPlace : ATSOSyncDbObject < ITSOPlace > {
 @public
  Coord *center_;
  NSString *address_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)userId;

- (instancetype)initWithNSString:(NSString *)objectId
                    withNSString:(NSString *)userId
                       withCoord:(Coord *)center
                        withLong:(long64)modificationTime;

- (instancetype)initWithNSString:(NSString *)userId
                       withCoord:(Coord *)center
                    withNSString:(NSString *)address;

- (instancetype)initWithNSString:(NSString *)objectId
                    withNSString:(NSString *)userId
                        withLong:(long64)modificationTimeInNano
                       withCoord:(Coord *)center
                    withNSString:(NSString *)address;

- (instancetype)initWithATSOPlace:(ATSOPlace *)other;

- (Coord *)getCenter;

- (void)setCenterWithCoord:(Coord *)center;

- (NSString *)getAddress;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (void)copyAllFieldsTo:(ATSOPlace *)other;

@end

__attribute__((always_inline)) inline void ATSOPlace_init() {}

//J2OBJC_FIELD_SETTER(ATSOPlace, center_, Coord *)
//J2OBJC_FIELD_SETTER(ATSOPlace, address_, NSString *)

FOUNDATION_EXPORT NSString *ATSOPlace_PLACE_TYPE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ATSOPlace, PLACE_TYPE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *ATSOPlace_CENTER_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ATSOPlace, CENTER_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *ATSOPlace_ADDRESS_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ATSOPlace, ADDRESS_FIELD_, NSString *)

typedef ATSOPlace ComIntelWearablePlatformTimeiqDbobjectsAbstractsATSOPlace;

#endif // _ATSOPlace_H_
