//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/audit/AuditSendTime.java
//

#ifndef _AuditSendTime_H_
#define _AuditSendTime_H_

#import "JBHashtable.h"

#import "JB.h"
#import "ATSOBaseDBObject.h"

/**
 @brief Created by slevin
 */
@interface AuditSendTime : ATSOBaseDBObject {
 @public
  long64 lastSendTime_;
}

- (instancetype)init;

- (long64)getLastSendTime;

- (void)setLastSendTimeWithLong:(long64)lastSendTime;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (NSString *)description;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(AuditSendTime *)other;

@end

__attribute__((always_inline)) inline void AuditSendTime_init() {}

FOUNDATION_EXPORT NSString *AuditSendTime_OBJECT_ID_;
J2OBJC_STATIC_FIELD_GETTER(AuditSendTime, OBJECT_ID_, NSString *)

typedef AuditSendTime ComIntelWearablePlatformTimeiqCommonAuditAuditSendTime;

#endif // _AuditSendTime_H_
