//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/devicestatemanager/data/BatteryStateInfo.java
//

#ifndef _BatteryStateInfo_H_
#define _BatteryStateInfo_H_

@class ChargeMethod;

#import "JB.h"

/**
 @brief Created by eleuchte on 02/08/2015.
 */
@interface BatteryStateInfo : NSObject {
 @public
  int m_batteryLevel_;
  ChargeMethod *m_chargeMethod_;
}

- (instancetype)init;

- (instancetype)initWithInt:(int)m_batteryLevel
       withChargeMethod:(ChargeMethod *)m_chargeMethod;

- (instancetype)initWithBatteryStateInfo:(BatteryStateInfo *)other;

- (int)getBatteryLevel;

- (ChargeMethod *)getChargeMethod;

- (void)setBatteryLevelWithInt:(int)batteryLevel;

- (void)setChargeMethodWithChargeMethod:(ChargeMethod *)chargeMethod;

- (void)copyAllFieldsTo:(BatteryStateInfo *)other;

@end

__attribute__((always_inline)) inline void BatteryStateInfo_init() {}

//J2OBJC_FIELD_SETTER(BatteryStateInfo, m_chargeMethod_, ChargeMethod *)

typedef BatteryStateInfo ComIntelWearablePlatformTimeiqCommonDevicestatemanagerDataBatteryStateInfo;

#endif // _BatteryStateInfo_H_
