//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //sdk/tso/intel/com/platform_lib/BuildConfig.java
//

#ifndef _BuildConfig_H_
#define _BuildConfig_H_

#import "NSNumber+JavaAPI.h"

#import "JB.h"

/**
 @brief Automatically generated file.
 DO NOT MODIFY
 */

#define BuildConfig_DEBUG NO
#define BuildConfig_VERSION_CODE 1

@interface BuildConfig : NSObject {
}

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL BuildConfig_initialized;
J2OBJC_STATIC_INIT(BuildConfig)

J2OBJC_STATIC_FIELD_GETTER(BuildConfig, DEBUG, boolean)

FOUNDATION_EXPORT NSString *BuildConfig_APPLICATION_ID_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, APPLICATION_ID_, NSString *)

FOUNDATION_EXPORT NSString *BuildConfig_BUILD_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, BUILD_TYPE_, NSString *)

FOUNDATION_EXPORT NSString *BuildConfig_FLAVOR_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, FLAVOR_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(BuildConfig, VERSION_CODE, int)

FOUNDATION_EXPORT NSString *BuildConfig_VERSION_NAME_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, VERSION_NAME_, NSString *)

FOUNDATION_EXPORT NSString *BuildConfig_BUILD_DATE_FULL_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, BUILD_DATE_FULL_, NSString *)

FOUNDATION_EXPORT NSString *BuildConfig_BUILD_DATE_SHORT_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, BUILD_DATE_SHORT_, NSString *)

FOUNDATION_EXPORT JBBoolean *BuildConfig_USE_CSW_NETWORKING_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, USE_CSW_NETWORKING_, JBBoolean *)

FOUNDATION_EXPORT JBBoolean *BuildConfig_USE_INTERNAL_STORAGE_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, USE_INTERNAL_STORAGE_, JBBoolean *)

FOUNDATION_EXPORT JBBoolean *BuildConfig_USE_LEGACY_FOLDER_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, USE_LEGACY_FOLDER_, JBBoolean *)

FOUNDATION_EXPORT NSString *BuildConfig_BRANCH_NAME_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, BRANCH_NAME_, NSString *)

FOUNDATION_EXPORT NSString *BuildConfig_CONVERSION_REF_DATE_;
J2OBJC_STATIC_FIELD_GETTER(BuildConfig, CONVERSION_REF_DATE_, NSString *)

typedef BuildConfig SdkTsoIntelComPlatform_libBuildConfig;

#endif // _BuildConfig_H_
