//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/calendar/CalendarDetailsProvider.java
//

#ifndef _CalendarDetailsProvider_H_
#define _CalendarDetailsProvider_H_

@class Result;
@class ResultData;
@protocol IApiUsageUtil;
@protocol ITSOCalendarsManager;
@protocol IUserPrefs;
#import "JBArrayList.h"

#import "JB.h"
#include "ICalendarDetailsProvider.h"

/**
 @brief Created by eskoran on 29/10/2015.
 */
@interface CalendarDetailsProvider : NSObject < ICalendarDetailsProvider > {
 @public
  id<IUserPrefs> userPrefs_;
  id<ITSOCalendarsManager> calendarsManager_;
  id<IApiUsageUtil> apiUsageUtil_;
}

- (instancetype)init;

- (instancetype)initWithIUserPrefs:(id<IUserPrefs>)userPrefs
          withITSOCalendarsManager:(id<ITSOCalendarsManager>)calendarsManager
                 withIApiUsageUtil:(id<IApiUsageUtil>)apiUsageUtil;

- (ResultData *)getAvailableCalendars;

- (ResultData *)getWriteCalendar;

- (Result *)setWriteCalendarWithNSString:(NSString *)calendarId;

- (ResultData *)getReadCalendars;

- (Result *)setReadCalendarsWithJavaUtilList:(ArrayList*)calendarIds;

- (void)copyAllFieldsTo:(CalendarDetailsProvider *)other;

@end

__attribute__((always_inline)) inline void CalendarDetailsProvider_init() {}

//J2OBJC_FIELD_SETTER(CalendarDetailsProvider, userPrefs_, id<IUserPrefs>)
//J2OBJC_FIELD_SETTER(CalendarDetailsProvider, calendarsManager_, id<ITSOCalendarsManager>)
//J2OBJC_FIELD_SETTER(CalendarDetailsProvider, apiUsageUtil_, id<IApiUsageUtil>)

typedef CalendarDetailsProvider ComIntelWearablePlatformTimeiqCommonCalendarCalendarDetailsProvider;

#endif // _CalendarDetailsProvider_H_
