//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/phoneBasedReminder/callReminder/CallRemindersPersistentStorage.java
//

#ifndef _CallRemindersPersistentStorage_H_
#define _CallRemindersPersistentStorage_H_

#import "JBClass.h"

#import "JB.h"
#include "ABaseRemindersPersistentStorage.h"
#include "ICallRemindersStorage.h"

/**
 @brief Created by Yaron Abramovich on 25.5.15.
 */
@interface CallRemindersPersistentStorage : ABaseRemindersPersistentStorage < ICallRemindersStorage > {
}

- (Class )getReminderClass;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void CallRemindersPersistentStorage_init() {}

typedef CallRemindersPersistentStorage ComIntelWearablePlatformTimeiqRemindersPhoneBasedReminderCallReminderCallRemindersPersistentStorage;

#endif // _CallRemindersPersistentStorage_H_
