//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/phoneBasedReminder/callReminder/CallReminderInner.java
//

#ifndef _CallReminderInner_H_
#define _CallReminderInner_H_

@class CallReminder;
@protocol IReminder;
@protocol ITSOTimeUtil;

#import "JB.h"
#import "BasePhoneReminderInner.h"

/**
 @brief Created by mleib on 26/04/2015.
 */
@interface CallReminderInner : BasePhoneReminderInner {
}

- (instancetype)init;

- (instancetype)initWithCallReminder:(CallReminder *)callReminder;

- (instancetype)initWithCallReminder:(CallReminder *)callReminder
                    withITSOTimeUtil:(id<ITSOTimeUtil>)tsoTimeUtil;

- (id<IReminder>)createReminder;

@end

__attribute__((always_inline)) inline void CallReminderInner_init() {}

typedef CallReminderInner ComIntelWearablePlatformTimeiqRemindersPhoneBasedReminderCallReminderCallReminderInner;

#endif // _CallReminderInner_H_
