//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/visitinplacemodule/ClusterSensedPlace.java
//

#ifndef _ClusterSensedPlace_H_
#define _ClusterSensedPlace_H_

@class Coord;
@class DetectedPlace;
@class SourceDataType;
@class TSOCoordinate;
@class VisitedPlace;
@class WifiScan;

#import "JB.h"
#include "SensedPlace.h"

@interface ClusterSensedPlace : SensedPlace {
 @public
  DetectedPlace *cluster_;
}

/**
 @brief Constructor
 @param cluster
 */
- (instancetype)initWithDetectedPlace:(DetectedPlace *)cluster;

/**
 @brief Constructor
 @param cluster
 @param placeId
 */
- (instancetype)initWithDetectedPlace:(DetectedPlace *)cluster
                         withNSString:(NSString *)placeId
               withSourceDataType:(SourceDataType *)sourceType;

- (long64)distanceToEnvelopeWithCoord:(Coord *)coord;

- (DetectedPlace *)getCluster;

- (long64)distanceToCenterWithCoord:(Coord *)coord;

- (boolean)hasEnvelpe;

- (NSString *)mkidWithVisitedPlace:(VisitedPlace *)vp;

- (TSOCoordinate *)getCenter;

- (int)getWifSignaureNum;

- (int)calcMatchingSignatureWithWifiScan:(WifiScan *)wifiScan;

- (NSString *)getDetectedId;

- (void)copyAllFieldsTo:(ClusterSensedPlace *)other;

@end

__attribute__((always_inline)) inline void ClusterSensedPlace_init() {}

//J2OBJC_FIELD_SETTER(ClusterSensedPlace, cluster_, DetectedPlace *)

typedef ClusterSensedPlace ComIntelWearablePlatformTimeiqPlacesModulesVisitinplacemoduleClusterSensedPlace;

#endif // _ClusterSensedPlace_H_
