//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/djcluster/Cluster.java
//

#ifndef _Cluster_H_
#define _Cluster_H_

@class ClusterStatistics;
@class Coord;
@class DetectedPlace;
#import "JBVector.h"
@class PlaceStatus;
@class Polygon;
@class SemanticTag;
@class TSOCoordinate;
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "IDetectedPlace.h"

@interface Cluster : NSObject < IDetectedPlace > {
 @public
  ArrayList* points_;
  DetectedPlace *dbCluster_;
}

- (instancetype)initWithNSString:(NSString *)objId;

- (instancetype)initWithDetectedPlace:(DetectedPlace *)place;

- (instancetype)initWithNSString:(NSString *)placeId
                withJavaUtilList:(ArrayList*)points;

- (void)addPointsWithJavaUtilList:(ArrayList*)points;

- (void)addPointWithCoord:(Coord *)q;

- (ArrayList*)getPoints;

- (void)calcCenter;

- (void)calcRadius;

- (Polygon *)getEnvelope;

- (void)calcEnvelope;

- (boolean)isPointInPolygonWithCoord:(Coord *)p;

- (ClusterStatistics *)getStats;

- (NSString *)description;

- (void)postProcessingWithJavaUtilMap:(HashMap*)coordLocations;

- (void)calcStatisticsWithJavaUtilMap:(HashMap*)coordLocations;

- (int)getRadius;

- (PlaceStatus *)getStatus;

- (Coord *)getCenter;

- (boolean)isPointInPlaceWithTSOCoordinate:(TSOCoordinate *)point;

- (NSString *)getPlaceId;

- (NSString *)getAddress;

- (long64)getDiscoveryTime;

- (Vector *)getAllPlaceVisits;

- (SemanticTag *)getSemanticTag;

- (void)setSemanticTagWithSemanticTag:(SemanticTag *)tag;

- (NSString *)getObjectId;

- (void)setObjectIdWithNSString:(NSString *)newId;

- (DetectedPlace *)getDbCluster;

- (void)setDbClusterWithDetectedPlace:(DetectedPlace *)dbCluster;

+ (NSString *)coordKeyWithDouble:(double)latitude
                      withDouble:(double)longitude;

- (void)resetPoints;

- (NSString *)getUserId;

- (void)setUserIdWithNSString:(NSString *)userId;

+ (NSString *)genenerateIdWithInt:(int)index;

- (NSString *)info;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (TSOCoordinate *)getLocation;

- (NSString *)getNormalizedPlaceDescription;

- (NSString *)getPlaceDescription;

- (void)copyAllFieldsTo:(Cluster *)other;

@end

__attribute__((always_inline)) inline void Cluster_init() {}

//J2OBJC_FIELD_SETTER(Cluster, points_, ArrayList*)
//J2OBJC_FIELD_SETTER(Cluster, dbCluster_, DetectedPlace *)

FOUNDATION_EXPORT NSString *Cluster_UNKKOWN_;
J2OBJC_STATIC_FIELD_GETTER(Cluster, UNKKOWN_, NSString *)

typedef Cluster ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleDjclusterCluster;

#endif // _Cluster_H_
