//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/semantic/ClusterLocation.java
//

#ifndef _ClusterLocation_H_
#define _ClusterLocation_H_

@protocol ILocationData;

#import "JB.h"

@interface ClusterLocation : NSObject {
 @public
  id<ILocationData> locationData_;
  ClusterLocation *previous_;
}

- (instancetype)initWithILocationData:(id<ILocationData>)locationData
                  withClusterLocation:(ClusterLocation *)previous;

- (id<ILocationData>)getLocationData;

- (ClusterLocation *)getPrevious;

- (void)copyAllFieldsTo:(ClusterLocation *)other;

@end

__attribute__((always_inline)) inline void ClusterLocation_init() {}

//J2OBJC_FIELD_SETTER(ClusterLocation, locationData_, id<ILocationData>)
//J2OBJC_FIELD_SETTER(ClusterLocation, previous_, ClusterLocation *)

typedef ClusterLocation ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleSemanticClusterLocation;

#endif // _ClusterLocation_H_
