//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/factory/CommonClassPool.java
//

#ifndef _CommonClassPool_H_
#define _CommonClassPool_H_

@protocol ITSOLogger;

#import "JB.h"

/**
 @brief Created by smoradof on 1/26/15.
 */
@interface CommonClassPool : NSObject {
}

+ (id<ITSOLogger>)getTSOLogger;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void CommonClassPool_init() {}

typedef CommonClassPool ComIntelWearablePlatformTimeiqCommonFactoryCommonClassPool;

#endif // _CommonClassPool_H_
