//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/DBObjectWithOperation.java
//

#ifndef _DBObjectWithOperation_H_
#define _DBObjectWithOperation_H_

@class DBOperation;
@protocol ITSOBaseDBObject;

#import "JB.h"

@interface DBObjectWithOperation : NSObject {
 @public
  id<ITSOBaseDBObject> object_;
  DBOperation *operation_;
}

- (instancetype)initWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object
                     withDBOperation:(DBOperation *)operation;

- (id)getObject;

- (void)setObjectWithITSOBaseDBObject:(id<ITSOBaseDBObject>)object;

- (DBOperation *)getOperation;

- (void)setOperationWithDBOperation:(DBOperation *)operation;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (void)copyAllFieldsTo:(DBObjectWithOperation *)other;

@end

__attribute__((always_inline)) inline void DBObjectWithOperation_init() {}

//J2OBJC_FIELD_SETTER(DBObjectWithOperation, object_, id)
//J2OBJC_FIELD_SETTER(DBObjectWithOperation, operation_, DBOperation *)

typedef DBObjectWithOperation ComIntelWearablePlatformTimeiqDbobjectsDBObjectWithOperation;

#endif // _DBObjectWithOperation_H_
