//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/logger/DBSensorDataFile.java
//

#ifndef _DBSensorDataFile_H_
#define _DBSensorDataFile_H_

@class BaseSensorData;
@class ReceiverSensorsRequest;
@class SensorType;

#import "JB.h"
#include "ISensorDataReceiver.h"

/**
 @brief Created by aeirew on 04/01/2015.
 */
@interface DBSensorDataFile : NSObject < ISensorDataReceiver > {
}

- (void)onDataReceivedWithBaseSensorData:(BaseSensorData *)data;

- (void)onResetReceiver;

- (void)onResumeReceiver;

- (void)onSampleIntervalChangedWithSensorType:(SensorType *)sensorType
                                         withLong:(long64)sampleInterval;

- (ReceiverSensorsRequest *)generateReceiverSensorsRequest;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void DBSensorDataFile_init() {}

typedef DBSensorDataFile ComIntelWearablePlatformTimeiqSensorsLoggerDBSensorDataFile;

#endif // _DBSensorDataFile_H_
