//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/devicestate/DeviceStateSensorData.java
//

#ifndef _DeviceStateSensorData_H_
#define _DeviceStateSensorData_H_

@class GpsState;
@class NetworkState;
@class TimeZoneState;
@class WifiState;
#import "JBHashtable.h"

#import "JB.h"
#include "BaseSensorData.h"

/**
 @brief Created by aeirew on 25/01/2015.
 */
@interface DeviceStateSensorData : BaseSensorData {
 @public
  WifiState *m_wifiState_;
  NetworkState *m_networkState_;
  GpsState *m_gpsState_;
  TimeZoneState *m_timeZoneState_;
}

- (instancetype)init;

- (instancetype)initWithLong:(long64)timeStamp
                withNSString:(NSString *)summary
        withNetworkState:(NetworkState *)networkState;

- (instancetype)initWithLong:(long64)timeStamp
                withNSString:(NSString *)summary
           withWifiState:(WifiState *)wifiState;

- (instancetype)initWithLong:(long64)timeStamp
                withNSString:(NSString *)summary
            withGpsState:(GpsState *)gpsState;

- (instancetype)initWithLong:(long64)timeStamp
                withNSString:(NSString *)summary
           withTimeZoneState:(TimeZoneState *)timeZoneState;

- (WifiState *)getWifiState;

- (NetworkState *)getNetworkState;

- (GpsState *)getGpsState;

- (TimeZoneState *)getTimeZoneState;

- (void)setWifiStateWithWifiState:(WifiState *)wifiState;

- (void)setNetworkStateWithNetworkState:(NetworkState *)networkState;

- (void)setGpsStateWithGpsState:(GpsState *)gpsState;

- (void)setTimeZoneStateWithTimeZoneState:(TimeZoneState *)timeZoneState;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(DeviceStateSensorData *)other;

@end

__attribute__((always_inline)) inline void DeviceStateSensorData_init() {}

//J2OBJC_FIELD_SETTER(DeviceStateSensorData, m_wifiState_, WifiState *)
//J2OBJC_FIELD_SETTER(DeviceStateSensorData, m_networkState_, NetworkState *)
//J2OBJC_FIELD_SETTER(DeviceStateSensorData, m_gpsState_, GpsState *)
//J2OBJC_FIELD_SETTER(DeviceStateSensorData, m_timeZoneState_, TimeZoneState *)

FOUNDATION_EXPORT NSString *DeviceStateSensorData_WIFI_STATE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DeviceStateSensorData, WIFI_STATE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DeviceStateSensorData_NETWORK_STATE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DeviceStateSensorData, NETWORK_STATE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DeviceStateSensorData_GPS_STATE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DeviceStateSensorData, GPS_STATE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DeviceStateSensorData_TIMEZONE_STATE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DeviceStateSensorData, TIMEZONE_STATE_FIELD_, NSString *)

typedef DeviceStateSensorData ComIntelWearablePlatformTimeiqSensorsDatatypesDevicestateDeviceStateSensorData;

#endif // _DeviceStateSensorData_H_
