//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/djcluster/DjClusterAlg.java
//

#ifndef _DjClusterAlg_H_
#define _DjClusterAlg_H_

@class Cluster;
@class Coord;
@class QuadTree;
#import "JBArrayList.h"

#import "JB.h"
#import "JBComparator.h"

/**
 @brief Algorithm to find clusters of visited locations.
 These clusters are assume to be significant user places.
 @author ylempert
 */
@interface DjClusterAlg : NSObject {
 @public
  double eps_;
  int minPoints_;
  double decayLamda_;
  QuadTree *quadTree_;
  ArrayList* points_;
  ArrayList* clusters_;
  boolean verbose_;
}

- (instancetype)initWithDouble:(double)eps
                       withInt:(int)minPoins;

- (ArrayList*)findClusters;

- (int)countDecayingPointsWithJavaUtilList:(ArrayList*)nearsetPoints
                                   withLong:(long64)lastDay;

+ (void)calcClustersStatisticsWithJavaUtilList:(ArrayList*)clusters
                              withJavaUtilList:(ArrayList*)allFuseSensorData
                                       withInt:(int)accuracyThreshold
                                    withDouble:(double)speedShreshold;

- (void)addPointsWithJavaUtilList:(ArrayList*)points;

- (QuadTree *)getQuadTree;

- (ArrayList*)getBoundingBox;

- (double)calcDaysRange;

- (double)dynamicEpsSelection;

- (int)dynamicMinPtsSelection;

- (void)initParamsWithDouble:(double)eps
                     withInt:(int)minPts
                  withDouble:(double)decayLamda OBJC_METHOD_FAMILY_NONE;

+ (ArrayList*)mergeWithJavaUtilList:(ArrayList*)clusters
                         withJavaUtilList:(ArrayList*)prev;

+ (double)calcRadiusOverlapWithCluster:(Cluster *)c1
                            withCluster:(Cluster *)c2;

+ (void)useAncestorIdWithJavaUtilList:(ArrayList*)clusters
                          withCluster:(Cluster *)current
                          withCluster:(Cluster *)prev;

- (ArrayList*)filterByBigEatSmallWithJavaUtilList:(ArrayList*)clusters;

- (Cluster *)bigEatSmallWithCluster:(Cluster *)c1
                        withCluster:(Cluster *)c2;

- (void)assignClusterId;

- (boolean)closeEnvelopesWithCluster:(Cluster *)c1
                          withCluster:(Cluster *)c2;

- (void)copyAllFieldsTo:(DjClusterAlg *)other;

@end

__attribute__((always_inline)) inline void DjClusterAlg_init() {}

//J2OBJC_FIELD_SETTER(DjClusterAlg, quadTree_, QuadTree *)
//J2OBJC_FIELD_SETTER(DjClusterAlg, points_, ArrayList*)
//J2OBJC_FIELD_SETTER(DjClusterAlg, clusters_, ArrayList*)

typedef DjClusterAlg ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleDjclusterDjClusterAlg;

@interface DjClusterAlg_$1 : NSObject < IComparator > {
}

- (int)compareWithId:(Coord *)o1
               withId:(Coord *)o2;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void DjClusterAlg_$1_init() {}

#endif // _DjClusterAlg_H_
