//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/extended_events/templates/DoAtTimeOfDayTemplate.java
//

#ifndef _DoAtTimeOfDayTemplate_H_
#define _DoAtTimeOfDayTemplate_H_

@class eDayOfReminder;
#import "JBHashtable.h"

#import "JB.h"
#import "AReminderTemplate.h"

/**
 @brief Created by smoradof on 7/28/2015.
 */
@interface DoAtTimeOfDayTemplate : AReminderTemplate {
 @public
  long64 mTime_;
  eDayOfReminder *mDayOfReminder_;
  NSString *mDoAction_;
}

- (instancetype)init;

- (instancetype)initWithBoolean:(boolean)isActive
                   withNSString:(NSString *)uiControllerId
         withEDayOfReminderEnum:(eDayOfReminder *)dayOfReminder
                       withLong:(long64)time
                   withNSString:(NSString *)doAction;

- (AReminderTemplate *)clone;

- (long64)getTime;

- (eDayOfReminder *)getDayOfReminder;

- (NSString *)getDoAction;

- (void)setTimeWithLong:(long64)m_time;

- (void)setDayOfReminderWithEDayOfReminderEnum:(eDayOfReminder *)m_dayOfReminder;

- (void)setDoActionWithNSString:(NSString *)m_doAction;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSString *)description;

- (void)copyAllFieldsTo:(DoAtTimeOfDayTemplate *)other;

@end

__attribute__((always_inline)) inline void DoAtTimeOfDayTemplate_init() {}

//J2OBJC_FIELD_SETTER(DoAtTimeOfDayTemplate, mDayOfReminder_, eDayOfReminder *)
//J2OBJC_FIELD_SETTER(DoAtTimeOfDayTemplate, mDoAction_, NSString *)

FOUNDATION_EXPORT NSString *DoAtTimeOfDayTemplate_TIME_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DoAtTimeOfDayTemplate, TIME_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DoAtTimeOfDayTemplate_DAY_OF_REMINDER_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DoAtTimeOfDayTemplate, DAY_OF_REMINDER_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *DoAtTimeOfDayTemplate_DO_ACTION_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(DoAtTimeOfDayTemplate, DO_ACTION_FIELD_, NSString *)

typedef DoAtTimeOfDayTemplate ComIntelWearablePlatformTimeiqExtended_eventsTemplatesDoAtTimeOfDayTemplate;

#endif // _DoAtTimeOfDayTemplate_H_
