//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/api/reminders/doReminder/DoReminder.java
//

#ifndef _DoReminder_H_
#define _DoReminder_H_

@class DoReminder_DoReminderBuilder;
@class ReminderStatus;
@class ReminderType;
@protocol ITrigger;

#import "JB.h"
#include "BaseReminder.h"

/**
 @brief This class represents a reminder to do a certain action described as a user defined string
 */
@interface DoReminder : BaseReminder {
 @public
  NSString *m_doAction_;
}

/**
 @brief Create the DoReminder using a builder
 @param doReminderBuilder the builder that has the input parameters for the reminder
 @throws ReminderBuildException will be thrown when input is missing or invalid (see ReminderBuildExceptionType for reasons)
 */
- (instancetype)initWithDoReminder_DoReminderBuilder:(DoReminder_DoReminderBuilder *)doReminderBuilder;

/**
 @brief Create the DoReminder using parameters (the builder should be used in most cases)
 @param id the unique ID of the reminder
 @param reminderType the type of the reminder ( ReminderType#DO for DoReminder , ReminderType#CALL for BasedReminder.callReminder.CallReminder or ReminderType#NOTIFY for BasedReminder.notificationReminder.NotificationReminder )
 @param trigger the trigger that will make the reminder notify
 @param doAction the action that will be reminded to the user
 @param status the status of the reminder
 @param triggeredTime the time that the reminder was triggered, or -1 if not triggered yet
 @param addedTime the time that the reminder was added, or -1 if not added yet
 @throws ReminderBuildException will be thrown when input is missing or invalid (see ReminderBuildExceptionType for reasons)
 */
- (instancetype)initWithNSString:(NSString *)id_
            withReminderType:(ReminderType *)reminderType
                    withITrigger:(id<ITrigger>)trigger
                    withNSString:(NSString *)doAction
          withReminderStatus:(ReminderStatus *)status
                        withLong:(long64)triggeredTime
                        withLong:(long64)addedTime;

/**
 @brief Gets the action that will be reminded to the user
 @return the action that will be reminded to the user
 */
- (NSString *)getDoAction;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(DoReminder *)other;

@end

__attribute__((always_inline)) inline void DoReminder_init() {}

//J2OBJC_FIELD_SETTER(DoReminder, m_doAction_, NSString *)

typedef DoReminder ComIntelWearablePlatformTimeiqApiRemindersDoReminderDoReminder;

/**
 @brief Builder class used to construct the DoReminder class
 */
@interface DoReminder_DoReminderBuilder : BaseReminder_BaseReminderBuilder {
 @public
  NSString *doAction_;
}

/**
 @brief Create a builder for creating the DoReminder
 @param trigger the trigger that will make the reminder notify
 @param doAction the action that will be reminded to the user
 */
- (instancetype)initWithITrigger:(id<ITrigger>)trigger
                    withNSString:(NSString *)doAction;

/**
 @brief Create the DoReminder
 @return the DoReminder
 @throws ReminderBuildException will be thrown when input is missing or invalid (see ReminderBuildExceptionType for reasons)
 */
- (DoReminder *)build;

- (void)copyAllFieldsTo:(DoReminder_DoReminderBuilder *)other;

@end

__attribute__((always_inline)) inline void DoReminder_DoReminderBuilder_init() {}

//J2OBJC_FIELD_SETTER(DoReminder_DoReminderBuilder, doAction_, NSString *)

#endif // _DoReminder_H_
