//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/routeprovider/audit/dataobjects/request/ETARequestDataObj.java
//

#ifndef _ETARequestDataObj_H_
#define _ETARequestDataObj_H_

#import "NSNumber+JavaAPI.h"
@class MotType;
@class TSOCoordinateDataObj;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"
#import "ARequestDataObj.h"

@interface ETARequestDataObj : ARequestDataObj < IMappable > {
 @public
  TSOCoordinateDataObj *origin_;
  TSOCoordinateDataObj *destination_;
  NSString *departureTimeMS_;
  MotType *motType_;
  JBBoolean *prioritize_;
}

- (instancetype)initWithNSString:(NSString *)clientTimestamp
        withTSOCoordinateDataObj:(TSOCoordinateDataObj *)origin
        withTSOCoordinateDataObj:(TSOCoordinateDataObj *)destination
                    withNSString:(NSString *)departureTimeMS
                 withMotType:(MotType *)motType
             withJBBoolean:(JBBoolean *)prioritize;

- (instancetype)init;

- (TSOCoordinateDataObj *)getOrigin;

- (TSOCoordinateDataObj *)getDestination;

- (NSString *)getDepartureTimeMS;

- (MotType *)getMotType;

- (JBBoolean *)getPrioritize;

- (void)setOriginWithTSOCoordinateDataObj:(TSOCoordinateDataObj *)origin;

- (void)setDestinationWithTSOCoordinateDataObj:(TSOCoordinateDataObj *)destination;

- (void)setDepartureTimeMSWithNSString:(NSString *)departureTimeMS;

- (void)setMotTypeWithMotType:(MotType *)motType;

- (void)setPrioritizeWithJBBoolean:(JBBoolean *)prioritize;

- (NSString *)description;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(ETARequestDataObj *)other;

@end

__attribute__((always_inline)) inline void ETARequestDataObj_init() {}

//J2OBJC_FIELD_SETTER(ETARequestDataObj, origin_, TSOCoordinateDataObj *)
//J2OBJC_FIELD_SETTER(ETARequestDataObj, destination_, TSOCoordinateDataObj *)
//J2OBJC_FIELD_SETTER(ETARequestDataObj, departureTimeMS_, NSString *)
//J2OBJC_FIELD_SETTER(ETARequestDataObj, motType_, MotType *)
//J2OBJC_FIELD_SETTER(ETARequestDataObj, prioritize_, JBBoolean *)

typedef ETARequestDataObj ComIntelWearablePlatformTimeiqRouteproviderAuditDataobjectsRequestETARequestDataObj;

#endif // _ETARequestDataObj_H_
