//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/routeprovider/audit/dataobjects/response/ETAResponseDataObj.java
//

#ifndef _ETAResponseDataObj_H_
#define _ETAResponseDataObj_H_

@class RouteErrorDataObj;
@class RouteInfoDataObj;
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"
#import "AResponseDataObj.h"

@interface ETAResponseDataObj : AResponseDataObj < IMappable > {
 @public
  RouteInfoDataObj *routeInfo_;
}

- (instancetype)initWithRouteErrorDataObj:(RouteErrorDataObj *)error
                     withRouteInfoDataObj:(RouteInfoDataObj *)routeInfo;

- (instancetype)init;

- (RouteInfoDataObj *)getRouteInfo;

- (void)setRouteInfoWithRouteInfoDataObj:(RouteInfoDataObj *)routeInfo;

- (NSString *)description;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(ETAResponseDataObj *)other;

@end

__attribute__((always_inline)) inline void ETAResponseDataObj_init() {}

//J2OBJC_FIELD_SETTER(ETAResponseDataObj, routeInfo_, RouteInfoDataObj *)

typedef ETAResponseDataObj ComIntelWearablePlatformTimeiqRouteproviderAuditDataobjectsResponseETAResponseDataObj;

#endif // _ETAResponseDataObj_H_
