//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/events/EventsEngineDebug.java
//

#ifndef _EventsEngineDebug_H_
#define _EventsEngineDebug_H_

@class BeManager;
@class CalendarEventsManager;
@class EventIdManager;
@class EventsAudit;
@class EventsManager;
@class EventsPersistenceUtil;
@class ResultData;
@class TSOAlertUpdatedResult;
@class TSOEventsSync;
@class TSOPosition;
@protocol IApiUsageUtil;
@protocol ICalendarDetailsProvider;
@protocol IExternalMessageEngine;
@protocol IInternalMessageEngine;
@protocol ISdkDefaultPrefs;
@protocol ITSOLogger;
@protocol ITSOTimeUtil;
@protocol ITriggersManager;

#import "JB.h"
#include "EventsEngine.h"

/**
 @brief Created by eskoran on 31/05/2015.
 */
@interface EventsEngineDebug : EventsEngine {
}

- (instancetype)init;

- (instancetype)initWithBeManager:(BeManager *)beManager
        withCalendarEventsManager:(CalendarEventsManager *)calendarEventsManager
                withEventsManager:(EventsManager *)eventsManager
                withTSOEventsSync:(TSOEventsSync *)tsoEventsSync
                  withEventsAudit:(EventsAudit *)eventsAudit
               withEventIdManager:(EventIdManager *)eventIdManager
        withEventsPersistenceUtil:(EventsPersistenceUtil *)eventsPersistenceUtil
     withICalendarDetailsProvider:(id<ICalendarDetailsProvider>)calendarDetailsProvider
             withITriggersManager:(id<ITriggersManager>)triggersManager
       withIExternalMessageEngine:(id<IExternalMessageEngine>)messageEngine
       withIInternalMessageEngine:(id<IInternalMessageEngine>)internalMessageEngine
             withISdkDefaultPrefs:(id<ISdkDefaultPrefs>)sdkDefaultPrefs
                 withITSOTimeUtil:(id<ITSOTimeUtil>)timerUtil
                   withITSOLogger:(id<ITSOLogger>)tsoLogger
                withIApiUsageUtil:(id<IApiUsageUtil>)apiUsageUtil;

- (TSOAlertUpdatedResult *)getLastKnownTTLForBeEventWithNSString:(NSString *)beEventId;

- (ResultData *)getCurrentTTLForBeEventWithNSString:(NSString *)beEventId
                                    withTSOPosition:(TSOPosition *)userPosition;

- (ResultData *)getCurrentETAForBeEventWithNSString:(NSString *)beEventId
                                    withTSOPosition:(TSOPosition *)userPosition;

- (TSOAlertUpdatedResult *)getLastKnownTTLForCalendarEventWithNSString:(NSString *)calEventId;

- (ResultData *)getCurrentTTLForCalendarEventWithNSString:(NSString *)calEventId
                                          withTSOPosition:(TSOPosition *)userPosition;

- (ResultData *)getCurrentETAForCalendarEventWithNSString:(NSString *)calEventId
                                          withTSOPosition:(TSOPosition *)userPosition;

- (void)deleteAll;

@end

__attribute__((always_inline)) inline void EventsEngineDebug_init() {}

typedef EventsEngineDebug ComIntelWearablePlatformTimeiqEventsEventsEngineDebug;

#endif // _EventsEngineDebug_H_
