//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/messagehandler/ExternalEngine.java
//

#ifndef _ExternalEngine_H_
#define _ExternalEngine_H_

@protocol IMessage;
@protocol ISentValidationListener;

#import "JB.h"
#include "AMessageEngine.h"
#include "IExternalMessageEngine.h"

/**
 @brief Created by stzour on 15/10/2015.
 */
@interface ExternalEngine : AMessageEngine < IExternalMessageEngine > {
}

- (void)addMessageWithIMessage:(id<IMessage>)msg
   withISentValidationListener:(id<ISentValidationListener>)sentValidationListener;

- (void)addMessageWithIMessage:(id<IMessage>)msg;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ExternalEngine_init() {}

typedef ExternalEngine ComIntelWearablePlatformTimeiqCommonMessagehandlerExternalEngine;

#endif // _ExternalEngine_H_
