//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/replay/FakeTimer.java
//

#ifndef _FakeTimer_H_
#define _FakeTimer_H_

@protocol ITSOAlarmListener;
#import "JBHashtable.h"

#import "JB.h"
#include "ITSOAlarmManager.h"

/**
 @brief Created by omendels on 7/23/2015.
 Replaces a timer on simulation runs. Ensures that all alarms are on the right order, but is not synchronized (in the time sense of the word...) To use this class you must use TSOTimeUtilDebug for ITSOTimeUtil implementation
 */
@interface FakeTimer : NSObject < ITSOAlarmManager > {
 @public
  HashMap* m_alarms_;
}

- (void)setApproximateAlarmWithITSOAlarmListener:(id<ITSOAlarmListener>)listener
                                    withNSString:(NSString *)action
                                    withNSString:(NSString *)intentId
                                    withNSString:(NSString *)data
                                        withLong:(long64)delay;

- (void)setExactAlarmWithITSOAlarmListener:(id<ITSOAlarmListener>)listener
                              withNSString:(NSString *)action
                              withNSString:(NSString *)intentId
                              withNSString:(NSString *)data
                                  withLong:(long64)delay;

- (void)cancelAlarmWithITSOAlarmListener:(id<ITSOAlarmListener>)listener
                            withNSString:(NSString *)intentId;

- (void)cancelAllAlarms;

- (void)unRegisterAlarmListenerWithITSOAlarmListener:(id<ITSOAlarmListener>)listener;

/**
 @brief execute next chronological alarm if it happens before specified timestamp
 @return true if alarm was executed, false otherwise
 */
- (boolean)execNextAlarmWithLong:(long64)timeToExecUntil;

/**
 @brief execute all alarms that should happen before specified timestamp
 */
- (void)executeAlarmsUptoTimestampWithLong:(long64)timeToExecUntil;

- (instancetype)init;

- (void)copyAllFieldsTo:(FakeTimer *)other;

@end

__attribute__((always_inline)) inline void FakeTimer_init() {}

//J2OBJC_FIELD_SETTER(FakeTimer, m_alarms_, HashMap*)

typedef FakeTimer ComIntelWearablePlatformTimeiqSensorsReplayFakeTimer;

/**
 @brief class representing a single alarm data
 */
@interface FakeTimer_AlarmData : NSObject {
 @public
  id<ITSOAlarmListener> m_listener_;
  NSString *m_action_;
  NSString *m_intentId_;
  NSString *m_data_;
  long64 m_alarmTime_;
}

- (instancetype)initWithFakeTimer:(FakeTimer *)outer$;

- (void)copyAllFieldsTo:(FakeTimer_AlarmData *)other;

@end

__attribute__((always_inline)) inline void FakeTimer_AlarmData_init() {}

//J2OBJC_FIELD_SETTER(FakeTimer_AlarmData, m_listener_, id<ITSOAlarmListener>)
//J2OBJC_FIELD_SETTER(FakeTimer_AlarmData, m_action_, NSString *)
//J2OBJC_FIELD_SETTER(FakeTimer_AlarmData, m_intentId_, NSString *)
//J2OBJC_FIELD_SETTER(FakeTimer_AlarmData, m_data_, NSString *)

#endif // _FakeTimer_H_
