//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/file/FileStreamManager.java
//

#ifndef _FileStreamManager_H_
#define _FileStreamManager_H_

#import "NSArray+JavaAPI.h"
#import "JBFile.h"
#import "JBFileInputStream.h"
#import "JBFileOutputStream.h"

#import "JB.h"
#import "JBFilenameFilter.h"
#import "JBComparator.h"

/**
 @brief Created by eleuchte on 12/25/2014.
 */
@interface FileStreamManager : NSObject {
 @public
  NSString *m_dirName_;
  NSString *m_fileName_;
  FileInputStream *fileInputStream_;
  FileOutputStream *fileOutputStream_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)dirName
                    withNSString:(NSString *)fileName;

- (NSString *)getDirName;

- (NSString *)getFileName;

- (void)setDirNameWithNSString:(NSString *)dirName;

- (void)setFileNameWithNSString:(NSString *)fileName;

- (FileInputStream *)getFileInputStream;

- (FileOutputStream *)getFileOutputStream;

- (long64)getFileSizeInBytes;

- (void)deleteFile;

- (boolean)zipFile;

- (void)closeOutputStream;

- (void)writeWithNSString:(NSString *)msg;

- (File *)getInputFileWithNSString:(NSString *)dirName
                            withNSString:(NSString *)fileName;

- (File *)getOutputFileWithNSString:(NSString *)dirName
                             withNSString:(NSString *)fileName;

+ (Array *)getExternalFolderFilesListWithNSString:(NSString *)ExternalFolderName
                                              withNSString:(NSString *)filterFileName;

- (void)copyAllFieldsTo:(FileStreamManager *)other;

@end

FOUNDATION_EXPORT BOOL FileStreamManager_initialized;
J2OBJC_STATIC_INIT(FileStreamManager)

//J2OBJC_FIELD_SETTER(FileStreamManager, m_dirName_, NSString *)
//J2OBJC_FIELD_SETTER(FileStreamManager, m_fileName_, NSString *)
//J2OBJC_FIELD_SETTER(FileStreamManager, fileInputStream_, FileInputStream *)
//J2OBJC_FIELD_SETTER(FileStreamManager, fileOutputStream_, FileOutputStream *)

FOUNDATION_EXPORT NSString *FileStreamManager_TAG_;
J2OBJC_STATIC_FIELD_GETTER(FileStreamManager, TAG_, NSString *)

typedef FileStreamManager ComIntelWearablePlatformTimeiqCommonStorageFileFileStreamManager;

@interface FileStreamManager_$1 : NSObject < FilenameFilter > {
 @public
  NSString *val$filterFileName_;
}

- (boolean)acceptWithFile:(File *)dir
                    withNSString:(NSString *)filename;

- (instancetype)initWithNSString:(NSString *)capture$0;

@end

__attribute__((always_inline)) inline void FileStreamManager_$1_init() {}

//J2OBJC_FIELD_SETTER(FileStreamManager_$1, val$filterFileName_, NSString *)

@interface FileStreamManager_$2 : NSObject < IComparator > {
}

- (int)compareWithId:(File *)f1
               withId:(File *)f2;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void FileStreamManager_$2_init() {}

#endif // _FileStreamManager_H_
