//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/persistence/syncdb/daoimpls/file/FilePlacesDao.java
//

#ifndef _FilePlacesDao_H_
#define _FilePlacesDao_H_

#import "JBClass.h"
@protocol IDBSourceDefinition;
@protocol ITSOSemanticPlace;

#import "JB.h"
#include "IPlaceDao.h"
#include "GenericFileDao.h"

/**
 @brief Created by aeirew on 25/06/2015.
 */
@interface FilePlacesDao : GenericFileDao < IPlaceDao > {
 @public
  id<IPlaceDao> m_placeDao_;
}

- (instancetype)initWithIDBSourceDefinition:(id<IDBSourceDefinition>)idbSourceDefinition
                               withIOSClass:(Class )deserializeClassName;

- (id)getUserPlaceByNameWithNSString:(NSString *)userId
                        withNSString:(NSString *)placeName;

- (id)getUserHomeWithNSString:(NSString *)userId;

- (id)getUserWorkWithNSString:(NSString *)userId;

- (void)copyAllFieldsTo:(FilePlacesDao *)other;

@end

__attribute__((always_inline)) inline void FilePlacesDao_init() {}

//J2OBJC_FIELD_SETTER(FilePlacesDao, m_placeDao_, id<IPlaceDao>)

typedef FilePlacesDao ComIntelWearablePlatformTimeiqPlacesModulesPersistenceSyncdbDaoimplsFileFilePlacesDao;

#endif // _FilePlacesDao_H_
