//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/placesmodule/fusefilters/FuseFilter.java
//

#ifndef _FuseFilter_H_
#define _FuseFilter_H_

#import "JBArrayList.h"

#import "JB.h"

@interface FuseFilter : NSObject {
}

+ (ArrayList*)filterByDaysWindowWithJavaUtilList:(ArrayList*)fuseLocations
                                               withInt:(int)daysWindow;

+ (ArrayList*)filterByDensityWithJavaUtilList:(ArrayList*)fuseLocations
                                            withInt:(int)minutesBetweenSamples;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void FuseFilter_init() {}

typedef FuseFilter ComIntelWearablePlatformTimeiqPlacesModulesPlacesmoduleFusefiltersFuseFilter;

#endif // _FuseFilter_H_
