//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/platform/java/common/network/http/HttpProviderStub.java
//

#ifndef _HttpProviderStub_H_
#define _HttpProviderStub_H_

@class InputStream;
@class ResultData;
@protocol IHttpSentDataListener;
@protocol JavaLangReflectType;

#import "JB.h"
#import "IHttpProvider.h"

@interface HttpProviderStub : NSObject < IHttpProvider > {
 @public
  ResultData *resultData_;
}

- (void)setResultDataWithResultData:(ResultData *)resultData;

- (ResultData *)sendAndReceiveWithId:(id)request
             withReflectType:(JavaLangReflectType)typeOf
                        withNSString:(NSString *)url;

- (ResultData *)sendAndReceiveWithId:(id)request
             withReflectType:(JavaLangReflectType)typeOf
                        withNSString:(NSString *)url
                             withInt:(int)readTimeOut
                             withInt:(int)connectionTimeOut;

- (ResultData *)sendAndReceiveWithInputStream:(InputStream *)inputStream
                            withReflectType:(JavaLangReflectType)typeOf
                                       withNSString:(NSString *)url;

- (void)registerListenerWithIHttpSentDataListener:(id<IHttpSentDataListener>)httpSentDataListener;

- (void)unRegisterListenerWithIHttpSentDataListener:(id<IHttpSentDataListener>)httpSentDataListener;

- (void)setNetworkCredentialsWithId:(id)credentials;

- (instancetype)init;

- (void)copyAllFieldsTo:(HttpProviderStub *)other;

@end

__attribute__((always_inline)) inline void HttpProviderStub_init() {}

//J2OBJC_FIELD_SETTER(HttpProviderStub, resultData_, ResultData *)

typedef HttpProviderStub ComIntelWearablePlatformTimeiqPlatformJavaCommonNetworkHttpHttpProviderStub;

#endif // _HttpProviderStub_H_
