//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/network/http/HttpSentDataInfo.java
//

#ifndef _HttpSentDataInfo_H_
#define _HttpSentDataInfo_H_

#import "JB.h"

/**
 @brief Created by eleuchte on 9/15/2015.
 */
@interface HttpSentDataInfo : NSObject {
 @public
  long64 m_timeStamp_;
  NSString *m_url_;
  long64 m_transmittedDataSize_;
  long64 m_receivedDataSize_;
  NSString *m_resultCode_;
  NSString *m_extraData_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)url
                        withLong:(long64)transmittedDataSize
                        withLong:(long64)receivedDataSize
                    withNSString:(NSString *)resultCode
                    withNSString:(NSString *)extraData;

- (NSString *)getUrl;

- (long64)getTimeStamp;

- (long64)getTransmittedDataSize;

- (long64)getReceivedDataSize;

- (NSString *)getResultCode;

- (NSString *)getExtraData;

- (void)copyAllFieldsTo:(HttpSentDataInfo *)other;

@end

__attribute__((always_inline)) inline void HttpSentDataInfo_init() {}

//J2OBJC_FIELD_SETTER(HttpSentDataInfo, m_url_, NSString *)
//J2OBJC_FIELD_SETTER(HttpSentDataInfo, m_resultCode_, NSString *)
//J2OBJC_FIELD_SETTER(HttpSentDataInfo, m_extraData_, NSString *)

typedef HttpSentDataInfo ComIntelWearablePlatformTimeiqCommonNetworkHttpHttpSentDataInfo;

#endif // _HttpSentDataInfo_H_
