//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/platform/java/common/network/http/HttpProviderNull.java
//

#ifndef _HttpProviderNull_H_
#define _HttpProviderNull_H_

@class InputStream;
@class ResultData;
@protocol IHttpSentDataListener;
@protocol JavaLangReflectType;

#import "JB.h"
#include "IHttpProvider.h"

/**
 @brief Created by ibeider on 28/01/2015.
 */
@interface HttpProviderNull : NSObject < IHttpProvider > {
}

- (instancetype)init;

- (ResultData *)sendAndReceiveWithId:(id)request
             withReflectType:(JavaLangReflectType)typeOf
                        withNSString:(NSString *)url;

- (ResultData *)sendAndReceiveWithId:(id)request
             withReflectType:(JavaLangReflectType)typeOf
                        withNSString:(NSString *)url
                             withInt:(int)readTimeOut
                             withInt:(int)connectionTimeOut;

- (ResultData *)sendAndReceiveWithInputStream:(InputStream *)inputStream
                            withReflectType:(JavaLangReflectType)typeOf
                                       withNSString:(NSString *)url;

- (void)registerListenerWithIHttpSentDataListener:(id<IHttpSentDataListener>)httpSentDataListener;

- (void)unRegisterListenerWithIHttpSentDataListener:(id<IHttpSentDataListener>)httpSentDataListener;

- (void)setNetworkCredentialsWithId:(id)credentials;

@end

__attribute__((always_inline)) inline void HttpProviderNull_init() {}

typedef HttpProviderNull ComIntelWearablePlatformTimeiqPlatformJavaCommonNetworkHttpHttpProviderNull;

#endif // _HttpProviderNull_H_
