//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/audit/HttpAuditTransmitter.java
//

#ifndef _HttpAuditTransmitter_H_
#define _HttpAuditTransmitter_H_

@protocol IHttpProvider;
@protocol ITSOLogger;

#import "JB.h"
#include "AHttpTransmitter.h"
#include "IHttpAuditTransmitter.h"

/**
 @brief Created by ibeider on 28/01/2015.
 */
@interface HttpAuditTransmitter : AHttpTransmitter < IHttpAuditTransmitter > {
}

- (instancetype)init;

- (instancetype)initWithITSOLogger:(id<ITSOLogger>)logger
                 withIHttpProvider:(id<IHttpProvider>)httpProvider;

- (void)init__ OBJC_METHOD_FAMILY_NONE;

@end

__attribute__((always_inline)) inline void HttpAuditTransmitter_init() {}

typedef HttpAuditTransmitter ComIntelWearablePlatformTimeiqCommonAuditHttpAuditTransmitter;

#endif // _HttpAuditTransmitter_H_
