//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/db/IContentValues.java
//

#ifndef _IContentValues_H_
#define _IContentValues_H_

#import "JB.h"

/**
 @brief Created by yaronabr on 02-Jul-15.
 */
@protocol IContentValues < NSObject >

- (void)putWithNSString:(NSString *)key
                withInt:(int)val;

- (void)putWithNSString:(NSString *)key
           withNSString:(NSString *)val;

- (void)putWithNSString:(NSString *)key
            withBoolean:(boolean)val;

- (id)getWithNSString:(NSString *)key;

- (void)removeWithNSString:(NSString *)key;

@end

__attribute__((always_inline)) inline void IContentValues_init() {}

#define ComIntelWearablePlatformTimeiqCommonStorageDbIContentValues IContentValues

#endif // _IContentValues_H_
