//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dblayer/interfaces/IDaoDecorator.java
//

#ifndef _IDaoDecorator_H_
#define _IDaoDecorator_H_

@protocol IGenericDaoImpl;

#import "JB.h"

@protocol IDaoDecorator < NSObject >

- (id<IGenericDaoImpl>)getDecoratedDao;

@end

__attribute__((always_inline)) inline void IDaoDecorator_init() {}

#define ComIntelWearablePlatformTimeiqDblayerInterfacesIDaoDecorator IDaoDecorator

#endif // _IDaoDecorator_H_
