//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/persistence/memory/IMemoryRepositoryImpl.java
//

#ifndef _IMemoryRepositoryImpl_H_
#define _IMemoryRepositoryImpl_H_

#import "JBClass.h"
#import "JBHashtable.h"

#import "JB.h"

/**
 @brief Created by aeirew on 28/01/2015.
 */
@protocol IMemoryRepositoryImpl < NSObject >

- (void)storeMemoryObjectWithJavaUtilMap:(HashMap*)obj
                            withIOSClass:(Class )clazz;

- (HashMap*)restoreMemoryObjectWithClass :(Class )clazz;

@end

__attribute__((always_inline)) inline void IMemoryRepositoryImpl_init() {}

#define ComIntelWearablePlatformTimeiqPlacesModulesPersistenceMemoryIMemoryRepositoryImpl IMemoryRepositoryImpl

#endif // _IMemoryRepositoryImpl_H_
