//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/IMotStateDataProvider.java
//

#ifndef _IMotStateDataProvider_H_
#define _IMotStateDataProvider_H_

#import "JB.h"
#include "IStateDataProvider.h"

/**
 @brief Created by gilsharo on 6/8/2015.
 */
@protocol IMotStateDataProvider < IStateDataProvider, NSObject >
@end

__attribute__((always_inline)) inline void IMotStateDataProvider_init() {}

#define ComIntelWearablePlatformTimeiqUserstateIMotStateDataProvider IMotStateDataProvider

#endif // _IMotStateDataProvider_H_
