//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/phoneBasedReminder/notificationReminder/INotificationRemindersManager.java
//

#ifndef _INotificationRemindersManager_H_
#define _INotificationRemindersManager_H_

#import "JB.h"
#include "IBaseRemindersManager.h"

/**
 @brief Created by mleib on 04/05/2015.
 */
@protocol INotificationRemindersManager < IBaseRemindersManager, NSObject >
@end

__attribute__((always_inline)) inline void INotificationRemindersManager_init() {}

#define ComIntelWearablePlatformTimeiqRemindersPhoneBasedReminderNotificationReminderINotificationRemindersManager INotificationRemindersManager

#endif // _INotificationRemindersManager_H_
