//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/IRemindersStorage.java
//

#ifndef _IRemindersStorage_H_
#define _IRemindersStorage_H_

#import "JBEnumSet.h"
@class ReminderEndReason;
@protocol IReminderInner;
@protocol ITrigger;
#import "JBHashSet.h"

#import "JB.h"

/**
 @brief Created by mleib on 30/04/2015.
 */
@protocol IRemindersStorage < NSObject >

- (boolean)addReminderWithIReminderInner:(id<IReminderInner>)reminder;

- (boolean)removeReminderWithIReminderInner:(id<IReminderInner>)reminder;

- (boolean)removeRemindersWithJavaUtilCollection:(Set*)remindersToRemove;

- (boolean)removeAllReminders;

- (Set*)getRemindersOfTriggersWithJavaUtilCollection:(Set*)triggers;

- (id)getReminderWithNSString:(NSString *)reminderId;

- (Set*)getRemindersWithEnumSet:(EnumSet *)reminderStatuses;

- (boolean)setReminderAsEndedWithIReminderInner:(id<IReminderInner>)reminder
                       withReminderEndReason:(ReminderEndReason *)reminderEndReason;

- (boolean)setReminderAsTriggeredWithIReminderInner:(id<IReminderInner>)reminder;

- (boolean)setReminderAsSnoozedWithIReminderInner:(id<IReminderInner>)reminder
                                      withITrigger:(id<ITrigger>)newTrigger;

/**
 @brief For debug only
 */
- (Set*)getAllReminders;

@end

__attribute__((always_inline)) inline void IRemindersStorage_init() {}

#define ComIntelWearablePlatformTimeiqRemindersIRemindersStorage IRemindersStorage

#endif // _IRemindersStorage_H_
