//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/preferences/ISdkDefaultPrefs.java
//

#ifndef _ISdkDefaultPrefs_H_
#define _ISdkDefaultPrefs_H_

#import "JB.h"
#import "IPrefs.h"

/**
 @brief Created by mleib on 03/08/2015.
 */
@protocol ISdkDefaultPrefs < IPrefs, NSObject >
@end

__attribute__((always_inline)) inline void ISdkDefaultPrefs_init() {}

#define ComIntelWearablePlatformTimeiqCommonPreferencesISdkDefaultPrefs ISdkDefaultPrefs

#endif // _ISdkDefaultPrefs_H_
