//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/logger/ISensorDumpFileLogger.java
//

#ifndef _ISensorDumpFileLogger_H_
#define _ISensorDumpFileLogger_H_

#import "JB.h"

/**
 @brief Created by eleuchte on 07/10/2015.
 */
@protocol ISensorDumpFileLogger < NSObject >

- (void)writeWithNSString:(NSString *)msg;

- (void)close;

@end

__attribute__((always_inline)) inline void ISensorDumpFileLogger_init() {}

#define ComIntelWearablePlatformTimeiqSensorsLoggerISensorDumpFileLogger ISensorDumpFileLogger

#endif // _ISensorDumpFileLogger_H_
