//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/db/ISqlHelper.java
//

#ifndef _ISqlHelper_H_
#define _ISqlHelper_H_

@protocol ISqlDb;

#import "JB.h"

/**
 @brief Created by yaronabr on 16-Jul-15.
 */
@protocol ISqlHelper < NSObject >

- (id<ISqlDb>)getDbWithBoolean:(boolean)isWritable;

- (void)closeDb;

- (NSString *)getDbName;

@end

__attribute__((always_inline)) inline void ISqlHelper_init() {}

#define ComIntelWearablePlatformTimeiqCommonStorageDbISqlHelper ISqlHelper

#endif // _ISqlHelper_H_
