//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/storage/basicstorage/IStorage.java
//

#ifndef _IStorage_H_
#define _IStorage_H_

@protocol ITransfer;
#import "JBArrayList.h"

#import "JB.h"

/**
 @brief Created by ibeider on 03/02/2015.
 */
@protocol IStorage < NSObject >

- (void)appendWithId:(id)object;

- (void)moveWithITransfer:(id<ITransfer>)transferInstance;

- (ArrayList*)getAllObjects;

@end

__attribute__((always_inline)) inline void IStorage_init() {}

#define ComIntelWearablePlatformTimeiqCommonStorageBasicstorageIStorage IStorage

#endif // _IStorage_H_
