//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/externallibs/ITimeUtil_ISO8601.java
//

#ifndef _ITimeUtil_ISO8601_H_
#define _ITimeUtil_ISO8601_H_

#import "JB.h"

/**
 @brief Created by smoradof on 4/14/15.
 */
@protocol ITimeUtil_ISO8601 < NSObject >

- (NSString *)nowAsISO;

- (NSString *)addMinutesToNowWithInt:(int)minutes;

- (NSString *)minusMinutesFromNowWithInt:(int)minutes;

- (NSString *)MillisAsISOWithLong:(long64)time;

- (long64)getMillisFromIsoWithNSString:(NSString *)timeAsIso;

@end

__attribute__((always_inline)) inline void ITimeUtil_ISO8601_init() {}

#define ComIntelWearablePlatformTimeiqCommonExternallibsITimeUtil_ISO8601 ITimeUtil_ISO8601

#endif // _ITimeUtil_ISO8601_H_
