//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/ITriggersManagerInner.java
//

#ifndef _ITriggersManagerInner_H_
#define _ITriggersManagerInner_H_

@protocol ITriggerLifeCycleListener;

#import "JB.h"
#include "ITriggersManager.h"

/**
 @brief Created by mleib on 06/07/2015.
 */
@protocol ITriggersManagerInner < ITriggersManager, NSObject >
- (boolean)endTriggerWithNSString:(NSString *)triggerId;

- (void)registerForTriggerLifeCycleWithITriggerLifeCycleListener:(id<ITriggerLifeCycleListener>)triggerLifeCycleListener;

- (void)unregisterForTriggerLifeCycleWithITriggerLifeCycleListener:(id<ITriggerLifeCycleListener>)triggerLifeCycleListener;

@end

__attribute__((always_inline)) inline void ITriggersManagerInner_init() {}

#define ComIntelWearablePlatformTimeiqTriggersITriggersManagerInner ITriggersManagerInner

#endif // _ITriggersManagerInner_H_
