//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/interfaces/ITSOBaseDBObject.java
//

#ifndef _ITSOBaseDBObject_H_
#define _ITSOBaseDBObject_H_

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by aeirew on 09/02/2015.
 */
@protocol ITSOBaseDBObject < IMappable, NSObject >
- (NSString *)getObjectId;

- (void)setObjectIdWithNSString:(NSString *)newId;

- (long64)getCreationTime;

- (long64)getLastUserInteractionTime;

- (void)setLastUserInteractionTimeWithLong:(long64)lastUserInteractionTime;

@end

__attribute__((always_inline)) inline void ITSOBaseDBObject_init() {}

#define ComIntelWearablePlatformTimeiqDbobjectsInterfacesITSOBaseDBObject ITSOBaseDBObject

#endif // _ITSOBaseDBObject_H_
