//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/logger/placeslogger/ITSOLoggerPlaces.java
//

#ifndef _ITSOLoggerPlaces_H_
#define _ITSOLoggerPlaces_H_

#import "NSArray+JavaAPI.h"
#import "NSException+JavaAPI.h"
@class LOG_LEVEL;

#import "JB.h"

/**
 @brief Created by eleuchte on 01/01/2015.
 */
@protocol ITSOLoggerPlaces < NSObject >

- (void)addToLogWithLOG_LEVEL:(LOG_LEVEL *)level
                     withNSString:(NSString *)tag
                     withNSString:(NSString *)log;

- (void)addToLogWithLOG_LEVEL:(LOG_LEVEL *)level
                     withNSString:(NSString *)tag
                     withNSString:(NSString *)log
            withThrowable:(Throwable *)ex;

- (void)printStringCollectionToLogWithLOG_LEVEL:(LOG_LEVEL *)level
                                       withNSString:(NSString *)tag
                                       withNSString:(NSString *)prefix
                                  withNSStringArray:(Array *)stringArray;

- (void)resetLog;

@end

__attribute__((always_inline)) inline void ITSOLoggerPlaces_init() {}

#define ComIntelWearablePlatformTimeiqCommonLoggerPlacesloggerITSOLoggerPlaces ITSOLoggerPlaces

#endif // _ITSOLoggerPlaces_H_
