//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/interfaces/ITSOPlace.java
//

#ifndef _ITSOPlace_H_
#define _ITSOPlace_H_

@class Coord;

#import "JB.h"
#include "ITSOSyncDbObject.h"

@protocol ITSOPlace < ITSOSyncDbObject, NSObject >
- (Coord *)getCenter;

- (void)setCenterWithCoord:(Coord *)center;

- (NSString *)getAddress;

@end

__attribute__((always_inline)) inline void ITSOPlace_init() {}

#define ComIntelWearablePlatformTimeiqDbobjectsInterfacesITSOPlace ITSOPlace

#endif // _ITSOPlace_H_
