//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/utils/time/ITSOTimeUtil.java
//

#ifndef _ITSOTimeUtil_H_
#define _ITSOTimeUtil_H_

#import "JB.h"

/**
 @brief Created by smoradof on 2/26/15.
 */
@protocol ITSOTimeUtil < NSObject >

- (long64)getCurrentTimeMillis;

- (boolean)timeIsInTheFutureWithLong:(long64)timeInMillis;

- (NSString *)getTimeZoneId;

@end

__attribute__((always_inline)) inline void ITSOTimeUtil_init() {}

#define ComIntelWearablePlatformTimeiqCommonUtilsTimeITSOTimeUtil ITSOTimeUtil

#endif // _ITSOTimeUtil_H_
