//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/barilevi/development/j2objc_convertor/res/all_sources/org/apache/commons/lang3/builder/EqualsBuilder.java
//

#import "JB.h"

#if !EqualsBuilder_RESTRICT
#define EqualsBuilder_INCLUDE_ALL 1
#endif
#undef EqualsBuilder_RESTRICT

#if !defined (_EqualsBuilder_) && (EqualsBuilder_INCLUDE_ALL || EqualsBuilder_INCLUDE)
#define _EqualsBuilder_

@interface EqualsBuilder : NSObject
{
    boolean isEquals;
}

- (EqualsBuilder *)appendWithNSString:(NSString *)clientTimestamp
                         withNSString:(NSString *)clientTimestamp2;

- (boolean)isEquals;

- (EqualsBuilder *)appendWithId:(id)obj1
                         withId:(id)obj2;

- (EqualsBuilder *)appendWithArray:(NSArray*)obj1
                         withArray:(NSArray*)obj2;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void EqualsBuilder_init() {}

typedef EqualsBuilder OrgApacheCommonsLang3BuilderEqualsBuilder;
#endif

