//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/location/LocationData.java
//

#ifndef _LocationData_H_
#define _LocationData_H_

#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"
#import "ILocationData.h"

/**
 @brief Created by aeirew on 17/11/2014.
 */
@interface LocationData : NSObject < IMappable, ILocationData > {
 @public
  float m_distance_;
  long64 m_elapsedRealtimeNanos_;
  long64 m_time_;
  double m_altitude_;
  double m_longitude_;
  double m_latitude_;
  float m_initialBearing_;
  boolean m_hasSpeed_;
  boolean m_hasBearing_;
  boolean m_hasAltitude_;
  boolean m_hasAccuracy_;
  float m_Accuracy_;
  float m_speed_;
  float m_bearing_;
}

- (instancetype)init;

- (instancetype)initWithLong:(long64)time
                  withDouble:(double)latitude
                  withDouble:(double)longitude
                   withFloat:(float)accuracy
                   withFloat:(float)speed;

- (instancetype)initWithFloat:(float)distance
                     withLong:(long64)elapsedRealtimeNanos
                     withLong:(long64)time
                   withDouble:(double)altitude
                   withDouble:(double)longitude
                   withDouble:(double)latitude
                    withFloat:(float)initialBearing
                  withBoolean:(boolean)hasSpeed
                  withBoolean:(boolean)hasBearing
                  withBoolean:(boolean)hasAltitude
                  withBoolean:(boolean)hasAccuracy
                    withFloat:(float)accuracy
                    withFloat:(float)speed
                    withFloat:(float)bearing;

- (instancetype)initWithILocationData:(id<ILocationData>)locationData
                             withLong:(long64)timestamp;

- (float)getDistance;

- (long64)getElapsedRealtimeNanos;

- (long64)getTime;

- (double)getAltitude;

- (double)getLongitude;

- (double)getLatitude;

- (float)getInitialBearing;

- (boolean)isHasSpeed;

- (boolean)isHasBearing;

- (boolean)isHasAltitude;

- (boolean)isHasAccuracy;

- (float)getAccuracy;

- (float)getSpeed;

- (float)getBearing;

- (NSString *)description;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(LocationData *)other;

@end

__attribute__((always_inline)) inline void LocationData_init() {}

FOUNDATION_EXPORT NSString *LocationData_DISTANCE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, DISTANCE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_ELPASED_TIME_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, ELPASED_TIME_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_TIME_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, TIME_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_ALTITUDE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, ALTITUDE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_LONGITUDE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, LONGITUDE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_LATITUDE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, LATITUDE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_INITIAL_BEARING_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, INITIAL_BEARING_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_HAS_SPEED_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, HAS_SPEED_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_HAS_BEARING_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, HAS_BEARING_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_HAS_ALTITUDE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, HAS_ALTITUDE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_HAS_ACCURACY_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, HAS_ACCURACY_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_ACCURACY_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, ACCURACY_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_SPEED_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, SPEED_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *LocationData_BEARING_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationData, BEARING_FIELD_, NSString *)

typedef LocationData ComIntelWearablePlatformTimeiqSensorsDatatypesLocationLocationData;

#endif // _LocationData_H_
