//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/location/LocationBaseSensorData.java
//

#ifndef _LocationBaseSensorData_H_
#define _LocationBaseSensorData_H_

@class DBLocationData;
@class SensorType;
@protocol ILocationData;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"
#include "BaseSensorData.h"
#import "JBSerializable.h"

/**
 @brief Created by aeirew on 17/11/2014.
 */
@interface LocationBaseSensorData : BaseSensorData < IMappable, Serializable > {
 @public
  DBLocationData *m_locationData_;
}

- (instancetype)init;

- (instancetype)initWithSensorType:(SensorType *)sensorType
                          withNSString:(NSString *)summary
                              withLong:(long64)timeStamp
                     withILocationData:(id<ILocationData>)locationData;

- (DBLocationData *)convertToDBLocationDataWithILocationData:(id<ILocationData>)locationData;

- (id<ILocationData>)getLocationData;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)objMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(LocationBaseSensorData *)other;

@end

__attribute__((always_inline)) inline void LocationBaseSensorData_init() {}

//J2OBJC_FIELD_SETTER(LocationBaseSensorData, m_locationData_, DBLocationData *)

FOUNDATION_EXPORT NSString *LocationBaseSensorData_LOCATION_DATA_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(LocationBaseSensorData, LOCATION_DATA_FIELD_, NSString *)

typedef LocationBaseSensorData ComIntelWearablePlatformTimeiqSensorsDatatypesLocationLocationBaseSensorData;

#endif // _LocationBaseSensorData_H_
