//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/exception/MethodNotFoundException.java
//

#ifndef _MethodNotFoundException_H_
#define _MethodNotFoundException_H_

#import "JB.h"
#import "NSException+JavaAPI.h"

#define MethodNotFoundException_serialVersionUID -9012700918440560245LL

@interface MethodNotFoundException : Exception {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void MethodNotFoundException_init() {}

J2OBJC_STATIC_FIELD_GETTER(MethodNotFoundException, serialVersionUID, long64)

typedef MethodNotFoundException ComIntelWearablePlatformTimeiqExceptionMethodNotFoundException;

#endif // _MethodNotFoundException_H_
