//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/datatypes/ModuleProduct.java
//

#ifndef _ModuleProduct_H_
#define _ModuleProduct_H_

#import "JBClass.h"
@class ModuleProductType;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by eleuchte on 14/01/2015.
 */
@interface ModuleProduct : NSObject < IMappable > {
 @public
  ModuleProductType *m_type_;
  NSString *m_content_;
}

- (instancetype)init;

- (instancetype)initWithModuleProductType:(ModuleProductType *)type
                                 withNSString:(NSString *)content;

- (ModuleProductType *)getType;

- (NSString *)getContent;

+ (Class )getClassOfTypeWithModuleProductType:(ModuleProductType *)type;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(ModuleProduct *)other;

@end

__attribute__((always_inline)) inline void ModuleProduct_init() {}

//J2OBJC_FIELD_SETTER(ModuleProduct, m_type_, ModuleProductType *)
//J2OBJC_FIELD_SETTER(ModuleProduct, m_content_, NSString *)

FOUNDATION_EXPORT NSString *ModuleProduct_MODULE_PRODUCT_TYPE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ModuleProduct, MODULE_PRODUCT_TYPE_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *ModuleProduct_CONTENT_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(ModuleProduct, CONTENT_FIELD_, NSString *)

typedef ModuleProduct ComIntelWearablePlatformTimeiqPlacesModulesDatatypesModuleProduct;

#endif // _ModuleProduct_H_
