//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/motmodule/algs/MotDetectoriPhoneNaive.java
//

#ifndef _MotDetectoriPhoneNaive_H_
#define _MotDetectoriPhoneNaive_H_

@class ActivitySensorData;
@class BluetoothDeviceSensorData;
@class LocationBaseSensorData;
@class Mot;
@class MotInfo;
@class PlacesActivityType;

#import "JB.h"
#include "IMotDetector.h"

#define MotDetectoriPhoneNaive_AR_HIGH_CONFIDENCE 3
#define MotDetectoriPhoneNaive_AR_NO_CONFIDENCE 0

/**
 @brief MOT Detector for iPhone
 */
@interface MotDetectoriPhoneNaive : NSObject < IMotDetector > {
}

- (MotInfo *)onLocationReceivedWithLocationBaseSensorData:(LocationBaseSensorData *)fuseLocation;

/**
 @brief naive implementation for iPhone use only activities reported with ar-high-confidence
 @return new MOT if known, null otherwise
 */
- (MotInfo *)onActivityReceivedWithActivitySensorData:(ActivitySensorData *)activityData;

/**
 @brief Choose the activity with highest confidence. prefer InVehicle if equal in confidence
 */
- (PlacesActivityType *)getMostProbableActivityWithActivitySensorData:(ActivitySensorData *)activityData;

/**
 @brief detect MOT based on BT connections when a car BT device connects return DRIVING when a car BT device disconnects return STATIONARY
 */
- (MotInfo *)onBluetoothDataReceivedWithBluetoothDeviceSensorData:(BluetoothDeviceSensorData *)bluetoothData;

- (void)store;

- (void)restore;

/**
 @brief convert ActivityType int to Mot enum
 */
+ (Mot *)getMotForActivityWithInt:(int)activityType;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void MotDetectoriPhoneNaive_init() {}

J2OBJC_STATIC_FIELD_GETTER(MotDetectoriPhoneNaive, AR_NO_CONFIDENCE, int)

J2OBJC_STATIC_FIELD_GETTER(MotDetectoriPhoneNaive, AR_HIGH_CONFIDENCE, int)

typedef MotDetectoriPhoneNaive ComIntelWearablePlatformTimeiqPlacesModulesMotmoduleAlgsMotDetectoriPhoneNaive;

#endif // _MotDetectoriPhoneNaive_H_
