//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/mot/MotDataHelper.java
//

#ifndef _MotDataHelper_H_
#define _MotDataHelper_H_

#import "JBArrayList.h"
@class MotType;
@protocol IBaseTriggersStorage;
#import "JBHashSet.h"

#import "JB.h"

/**
 @brief Created by yaronabr on 25-May-15.
 */
@interface MotDataHelper : NSObject {
}

+ (Set*)getTriggersWithTypeWithIBaseTriggersStorage:(id<IBaseTriggersStorage>)storage
                                                      withMotType:(MotType *)newType
                                                      withMotType:(MotType *)oldType
                                                withArrayList:(ArrayList *)data;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void MotDataHelper_init() {}

typedef MotDataHelper ComIntelWearablePlatformTimeiqTriggersMotMotDataHelper;

#endif // _MotDataHelper_H_
