//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/route/MotRecommenderImpl.java
//

#ifndef _MotRecommenderImpl_H_
#define _MotRecommenderImpl_H_

@class ClassFactory;
@class MotType;
@class Result;
@class ResultData;
@class TSOCoordinate;
@class TransportType;
@protocol IRouteData;
@protocol ISegmentedRouteProvider;
@protocol ITSOLogger;
@protocol ITSOTimeUtil;

#import "JB.h"
#include "IMotRecommender.h"

#define MotRecommenderImpl_MAX_WALKING_DISTANCE_IN_METERS_FOR_NO_TRANSPORT_TYPE 1800.0
#define MotRecommenderImpl_MAX_WALKING_DISTANCE_IN_METERS_FOR_WALK_TRANSPORT_TYPE 5000.0

/**
 @brief Created by smoradof on 6/28/2015.
 */
@interface MotRecommenderImpl : NSObject < IMotRecommender > {
 @public
  id<ITSOLogger> m_logger_;
  id<ITSOTimeUtil> m_timeUtil_;
  id<ISegmentedRouteProvider> m_segmentedRouteProvider_;
}

- (instancetype)init;

- (instancetype)initWithClassFactory:(ClassFactory *)classFactory;

- (instancetype)initWithITSOLogger:(id<ITSOLogger>)logger
                  withITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil
       withISegmentedRouteProvider:(id<ISegmentedRouteProvider>)segmentedRouteProvider;

- (ResultData *)getMotRecommendationForTTLWithTSOCoordinate:(TSOCoordinate *)origin
                                          withTSOCoordinate:(TSOCoordinate *)destination
                                                   withLong:(long64)arrivalTime
                                      withTransportType:(TransportType *)preferredTransportType
                                            withMotType:(MotType *)userMot;

- (ResultData *)getMotRecommendationForETAWithTSOCoordinate:(TSOCoordinate *)origin
                                          withTSOCoordinate:(TSOCoordinate *)destination
                                                   withLong:(long64)departureTime
                                      withTransportType:(TransportType *)preferredTransportType
                                            withMotType:(MotType *)userMot;

- (ResultData *)getMotRecommendationWithTSOCoordinate:(TSOCoordinate *)origin
                                    withTSOCoordinate:(TSOCoordinate *)destination
                                             withLong:(long64)time
                                withTransportType:(TransportType *)preferredTransportType
                                      withMotType:(MotType *)userMot
                                          withBoolean:(boolean)isTtl;

- (ResultData *)getMotRecommendationAccordingToMaxDistanceAndMaxTimeWithTSOCoordinate:(TSOCoordinate *)origin
                                                                    withTSOCoordinate:(TSOCoordinate *)destination
                                                                             withLong:(long64)time
                                                                      withMotType:(MotType *)userMot
                                                                          withBoolean:(boolean)isTtl
                                                                           withDouble:(double)maxWalkingDistanceInMeters
                                                                             withLong:(long64)maxWalkingTimeInMillis;

- (MotType *)walkRouteResultAnalysisWithIRouteData:(id<IRouteData>)walkRouteData
                                              withLong:(long64)maxTimeToWalkInMillis;

- (Result *)checkRequestValidationWithBoolean:(boolean)isTTL
                            withTSOCoordinate:(TSOCoordinate *)origin
                            withTSOCoordinate:(TSOCoordinate *)destination
                                     withLong:(long64)time;

- (void)copyAllFieldsTo:(MotRecommenderImpl *)other;

@end

FOUNDATION_EXPORT BOOL MotRecommenderImpl_initialized;
J2OBJC_STATIC_INIT(MotRecommenderImpl)

//J2OBJC_FIELD_SETTER(MotRecommenderImpl, m_logger_, id<ITSOLogger>)
//J2OBJC_FIELD_SETTER(MotRecommenderImpl, m_timeUtil_, id<ITSOTimeUtil>)
//J2OBJC_FIELD_SETTER(MotRecommenderImpl, m_segmentedRouteProvider_, id<ISegmentedRouteProvider>)

FOUNDATION_EXPORT NSString *MotRecommenderImpl_TAG_;
J2OBJC_STATIC_FIELD_GETTER(MotRecommenderImpl, TAG_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(MotRecommenderImpl, MAX_WALKING_DISTANCE_IN_METERS_FOR_WALK_TRANSPORT_TYPE, double)

J2OBJC_STATIC_FIELD_GETTER(MotRecommenderImpl, MAX_WALKING_DISTANCE_IN_METERS_FOR_NO_TRANSPORT_TYPE, double)

FOUNDATION_EXPORT long64 MotRecommenderImpl_MAX_WALKING_TIME_IN_MILLIS_FOR_WALK_TRANSPORT_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(MotRecommenderImpl, MAX_WALKING_TIME_IN_MILLIS_FOR_WALK_TRANSPORT_TYPE_, long64)

FOUNDATION_EXPORT long64 MotRecommenderImpl_MAX_WALKING_TIME_IN_MILLIS_FOR_NO_TRANSPORT_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(MotRecommenderImpl, MAX_WALKING_TIME_IN_MILLIS_FOR_NO_TRANSPORT_TYPE_, long64)

typedef MotRecommenderImpl ComIntelWearablePlatformTimeiqRouteMotRecommenderImpl;

#endif // _MotRecommenderImpl_H_
