//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/MotStateDataProvider.java
//

#ifndef _MotStateDataProvider_H_
#define _MotStateDataProvider_H_

@class ClassFactory;
@class MotInfo;
@protocol IPlacesEngine;
@protocol ITSOLogger;
@protocol ITSOTimeUtil;

#import "JB.h"
#include "IMotChangeListener.h"
#include "AStateDataProvider.h"
#include "IMotStateDataProvider.h"

/**
 @brief Created by gilsharo on 6/7/2015.
 */
@interface MotStateDataProvider : AStateDataProvider < IMotStateDataProvider, IMotChangeListener > {
 @public
  id<ITSOLogger> m_logger_;
  id<ITSOTimeUtil> m_timeUtil_;
  id<IPlacesEngine> m_placesEngine_;
}

- (instancetype)init;

- (instancetype)initWithClassFactory:(ClassFactory *)classFactory;

- (instancetype)initWithITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil
                      withITSOLogger:(id<ITSOLogger>)tsoLogger
                   withIPlacesEngine:(id<IPlacesEngine>)placesEngine;

- (void)updateData;

- (void)onMotChangeWithMotInfo:(MotInfo *)newMot;

- (void)copyAllFieldsTo:(MotStateDataProvider *)other;

@end

FOUNDATION_EXPORT BOOL MotStateDataProvider_initialized;
J2OBJC_STATIC_INIT(MotStateDataProvider)

//J2OBJC_FIELD_SETTER(MotStateDataProvider, m_logger_, id<ITSOLogger>)
//J2OBJC_FIELD_SETTER(MotStateDataProvider, m_timeUtil_, id<ITSOTimeUtil>)
//J2OBJC_FIELD_SETTER(MotStateDataProvider, m_placesEngine_, id<IPlacesEngine>)

FOUNDATION_EXPORT NSString *MotStateDataProvider_TAG_;
J2OBJC_STATIC_FIELD_GETTER(MotStateDataProvider, TAG_, NSString *)

typedef MotStateDataProvider ComIntelWearablePlatformTimeiqUserstateMotStateDataProvider;

#endif // _MotStateDataProvider_H_
