//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/ttlAlerts/nextWakeUpCalculator/NextWakeUpCalculatorStub.java
//

#ifndef _NextWakeUpCalculatorStub_H_
#define _NextWakeUpCalculatorStub_H_

@class ResultData;
@class TSOAlertInner;
@protocol ITSOTimeUtil;

#import "JB.h"
#import "INextWakeUpCalculator.h"

/**
 @brief Created by smoradof on 1/19/15.
 */
@interface NextWakeUpCalculatorStub : NSObject < INextWakeUpCalculator > {
 @public
  id<ITSOTimeUtil> m_timeUtil_;
  long64 m_nextWakeUpDelay_;
}

- (instancetype)init;

- (instancetype)initWithITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil;

- (ResultData *)calcNextWakeUpTimeWithTSOAlertInner:(TSOAlertInner *)tsoAlertInner
                                     withResultData:(ResultData *)routeDataRes
                                     withResultData:(ResultData *)nextAlertTime;

- (ResultData *)calcFirstWakeUpTimeWithTSOAlertInner:(TSOAlertInner *)tsoAlertInner;

- (void)setNextWakeUpDelayWithLong:(long64)delay;

- (void)copyAllFieldsTo:(NextWakeUpCalculatorStub *)other;

@end

__attribute__((always_inline)) inline void NextWakeUpCalculatorStub_init() {}

//J2OBJC_FIELD_SETTER(NextWakeUpCalculatorStub, m_timeUtil_, id<ITSOTimeUtil>)

typedef NextWakeUpCalculatorStub ComIntelWearablePlatformTimeiqTtlAlertsNextWakeUpCalculatorNextWakeUpCalculatorStub;

#endif // _NextWakeUpCalculatorStub_H_
