//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/phoneBasedReminder/notificationReminder/NotificationReminderInner.java
//

#ifndef _NotificationReminderInner_H_
#define _NotificationReminderInner_H_

@class NotificationReminder;
@protocol IReminder;
@protocol ITSOTimeUtil;
#import "JBHashtable.h"

#import "JB.h"
#include "BasePhoneReminderInner.h"

/**
 @brief Created by mleib on 26/04/2015.
 */
@interface NotificationReminderInner : BasePhoneReminderInner {
 @public
  NSString *m_message_;
}

- (instancetype)init;

- (instancetype)initWithNotificationReminder:(NotificationReminder *)notificationReminder;

- (instancetype)initWithNotificationReminder:(NotificationReminder *)notificationReminder
                            withITSOTimeUtil:(id<ITSOTimeUtil>)tsoTimeUtil;

- (NSString *)getNotificationMessage;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (id<IReminder>)createReminder;

- (void)copyAllFieldsTo:(NotificationReminderInner *)other;

@end

__attribute__((always_inline)) inline void NotificationReminderInner_init() {}

//J2OBJC_FIELD_SETTER(NotificationReminderInner, m_message_, NSString *)

FOUNDATION_EXPORT NSString *NotificationReminderInner_MESSAGE_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(NotificationReminderInner, MESSAGE_FIELD_, NSString *)

typedef NotificationReminderInner ComIntelWearablePlatformTimeiqRemindersPhoneBasedReminderNotificationReminderNotificationReminderInner;

#endif // _NotificationReminderInner_H_
