//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/api/common/protocol/datatypes/places/PlaceID.java
//

#ifndef _PlaceID_H_
#define _PlaceID_H_

@class SemanticKey;
@class SourceDataType;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by orencoh2 on 7/13/15.
 */
@interface PlaceID : NSObject < IMappable > {
 @public
  NSString *identifier_;
  SourceDataType *sourceDataType_;
  SemanticKey *semanticKey_;
}

/**
 @brief Constructor
 */
- (instancetype)init;

/**
 @brief Constructor
 @param identifier
 @param sourceDataType
 @param semanticKey
 */
- (instancetype)initWithNSString:(NSString *)identifier
          withSourceDataType:(SourceDataType *)sourceDataType
                 withSemanticKey:(SemanticKey *)semanticKey;

/**
 @brief Constructor
 @param identifier
 @param sourceDataType
 */
- (instancetype)initWithNSString:(NSString *)identifier
          withSourceDataType:(SourceDataType *)sourceDataType;

/**
 @brief Constructor
 @param semanticKey
 */
- (instancetype)initWithSemanticKey:(SemanticKey *)semanticKey;

- (SourceDataType *)getSourceDataType;

- (NSString *)getIdentifier;

- (SemanticKey *)getSemanticKey;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (boolean)semanticlyEqualsWithPlaceID:(PlaceID *)o;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSString *)description;

/**
 @brief Only for MappableSyntaxValidation - IMappable validation test
 */
- (void)setIdentifierWithNSString:(NSString *)identifier;

- (void)setSourceDataTypeWithSourceDataType:(SourceDataType *)sourceDataType;

- (void)setSemanticKeyWithSemanticKey:(SemanticKey *)semanticKey;

- (void)copyAllFieldsTo:(PlaceID *)other;

@end

__attribute__((always_inline)) inline void PlaceID_init() {}

//J2OBJC_FIELD_SETTER(PlaceID, identifier_, NSString *)
//J2OBJC_FIELD_SETTER(PlaceID, sourceDataType_, SourceDataType *)
//J2OBJC_FIELD_SETTER(PlaceID, semanticKey_, SemanticKey *)

FOUNDATION_EXPORT NSString *PlaceID_IDENTIFIER_;
J2OBJC_STATIC_FIELD_GETTER(PlaceID, IDENTIFIER_, NSString *)

FOUNDATION_EXPORT NSString *PlaceID_SOURCE_DATA_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(PlaceID, SOURCE_DATA_TYPE_, NSString *)

FOUNDATION_EXPORT NSString *PlaceID_SEMANTIC_KEY_;
J2OBJC_STATIC_FIELD_GETTER(PlaceID, SEMANTIC_KEY_, NSString *)

typedef PlaceID ComIntelWearablePlatformTimeiqApiCommonProtocolDatatypesPlacesPlaceID;

#endif // _PlaceID_H_
