//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/persistence/syncdb/daoimpls/modules/PlacesDao.java
//

#ifndef _PlacesDao_H_
#define _PlacesDao_H_

@protocol IGenericDaoImpl;
@protocol ITSOSemanticPlace;

#import "JB.h"
#import "IPlaceDao.h"

/**
 @brief Created by aeirew on 25/06/2015.
 */
@interface PlacesDao : NSObject < IPlaceDao > {
 @public
  id<IGenericDaoImpl> m_genericDao_;
}

- (instancetype)initWithIGenericDaoImpl:(id<IGenericDaoImpl>)genericDao;

- (id)getUserPlaceByNameWithNSString:(NSString *)userId
                        withNSString:(NSString *)placeName;

- (id)getUserHomeWithNSString:(NSString *)userId;

- (id)getUserWorkWithNSString:(NSString *)userId;

- (void)copyAllFieldsTo:(PlacesDao *)other;

@end

__attribute__((always_inline)) inline void PlacesDao_init() {}

//J2OBJC_FIELD_SETTER(PlacesDao, m_genericDao_, id<IGenericDaoImpl>)

FOUNDATION_EXPORT NSString *PlacesDao_HOME_;
J2OBJC_STATIC_FIELD_GETTER(PlacesDao, HOME_, NSString *)

FOUNDATION_EXPORT NSString *PlacesDao_WORK_;
J2OBJC_STATIC_FIELD_GETTER(PlacesDao, WORK_, NSString *)

typedef PlacesDao ComIntelWearablePlatformTimeiqPlacesModulesPersistenceSyncdbDaoimplsModulesPlacesDao;

#endif // _PlacesDao_H_
