//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/resourcemanager/ReceiverSensorsDefaultRequest.java
//

#ifndef _ReceiverSensorsDefaultRequest_H_
#define _ReceiverSensorsDefaultRequest_H_

#import "JB.h"
#import "ReceiverSensorsRequest.h"

/**
 @brief Created by eleuchte on 04/02/2015.
 */
@interface ReceiverSensorsDefaultRequest : ReceiverSensorsRequest {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ReceiverSensorsDefaultRequest_init() {}

typedef ReceiverSensorsDefaultRequest ComIntelWearablePlatformTimeiqSensorsResourcemanagerReceiverSensorsDefaultRequest;

#endif // _ReceiverSensorsDefaultRequest_H_
