//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/reminders/RemindersManagerFactory.java
//

#ifndef _RemindersManagerFactory_H_
#define _RemindersManagerFactory_H_

@protocol IRemindersManagerModule;

#import "JB.h"

/**
 @brief Created by mleib on 26/04/2015.
 */
@interface RemindersManagerFactory : NSObject {
}

/**
 @brief TODO: Miki advised to remove usage of this class completely.
 @return the instance of the IRemindersManagerModule
 */
+ (id<IRemindersManagerModule>)getRemindersManager;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void RemindersManagerFactory_init() {}

typedef RemindersManagerFactory ComIntelWearablePlatformTimeiqRemindersRemindersManagerFactory;

#endif // _RemindersManagerFactory_H_
