//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/resourcemanager/ResourceManager.java
//

#ifndef _ResourceManager_H_
#define _ResourceManager_H_

@class BaseSensorData;
@class ChargeMethod;
@class DeviceStateData;
@class ReceiverSensorsRequest;
@class SDKPolicy;
@class SemanticKey;
@class SensorModeRequest;
@class SensorType;
@protocol IPlaceRepoModule;
@protocol IPolicyListener;
#import "JBHashSet.h"
#import "JBArrayList.h"

#import "JB.h"
#import "IDeviceStateListener.h"
#import "IVisitInPlaceListener.h"
#import "ISensorDataReceiver.h"

/**
 @brief Created by eleuchte on 02/02/2015.
 */
@interface ResourceManager : NSObject < ISensorDataReceiver, IDeviceStateListener, IVisitInPlaceListener > {
 @public
  SDKPolicy *m_currentPolicy_;
  ArrayList* m_policyListeners_;
  boolean m_isActivityStill_;
  long64 m_activityStillStartTimeStamp_;
  long64 m_currentTimeStamp_;
  boolean m_stillMode_;
  int m_batteryLevel_;
  ChargeMethod *m_chargeMethod_;
  boolean m_isLocationHighAccuracySampling_;
  long64 m_stopLocationHighAccuracySampling_;
  long64 RETRY_LOCATION_HIGH_ACCURACY_SAMPLE_;
  boolean m_isNetworkWifiAvailable_;
  id<IPlaceRepoModule> m_placesRepo_;
}

- (instancetype)init;

+ (ResourceManager *)getInstance;

+ (void)init__ OBJC_METHOD_FAMILY_NONE;

- (void)initialRegistration OBJC_METHOD_FAMILY_NONE;

+ (void)dispose;

- (SDKPolicy *)getCurrentPolicy;

- (void)onDataReceivedWithBaseSensorData:(BaseSensorData *)data;

- (void)decideOnPolicyChange;

- (void)defineStillMode;

- (void)changePolicyWithSDKPolicy:(SDKPolicy *)newPolicy;

/**
 @brief The following method: - persists to DB repository PolicyHistoryInfo - creates policyChangeInfo which is dispatched to all policy listeners
 @param previous
 @return 
 */
- (void)handlePolicyChangeWithSDKPolicy:(SDKPolicy *)previous;

- (void)persistPolicyHistoryWithSDKPolicy:(SDKPolicy *)previous;

- (void)forcePolicyChangeWithSDKPolicy:(SDKPolicy *)newPolicy;

- (void)onResetReceiver;

- (void)onSampleIntervalChangedWithSensorType:(SensorType *)sensorType
                                         withLong:(long64)sampleInterval;

- (void)registerListenerWithIPolicyListener:(id<IPolicyListener>)policyListener;

- (void)unRegisterListenerWithIPolicyListener:(id<IPolicyListener>)policyListener;

/**
 @brief Reviews and approve/decline sensor mode changes (currently only sample interval)
 @param sensorType
 @param sensorModeRequest
 @return 
 */
- (boolean)isValidChangeRequestWithSensorType:(SensorType *)sensorType
                             withSensorModeRequest:(SensorModeRequest *)sensorModeRequest;

- (ReceiverSensorsRequest *)generateReceiverSensorsRequest;

- (void)onDeviceStateChangeWithDeviceStateData:(DeviceStateData *)deviceStateData
                              withJavaUtilList:(ArrayList*)deviceStateTypeChanges;

- (void)dispatchLocationAccuracyLevelChange;

- (void)onVisitInPlaceStartWithJavaUtilCollection:(Set*)visits;

- (void)onVisitInPlaceEndWithJavaUtilCollection:(Set*)visits;

- (boolean)isRelevantVipWithSemanticKey:(SemanticKey *)semanticKey;

- (void)copyAllFieldsTo:(ResourceManager *)other;

@end

FOUNDATION_EXPORT BOOL ResourceManager_initialized;
J2OBJC_STATIC_INIT(ResourceManager)

//J2OBJC_FIELD_SETTER(ResourceManager, m_currentPolicy_, SDKPolicy *)
//J2OBJC_FIELD_SETTER(ResourceManager, m_policyListeners_, ArrayList*)
//J2OBJC_FIELD_SETTER(ResourceManager, m_chargeMethod_, ChargeMethod *)
//J2OBJC_FIELD_SETTER(ResourceManager, m_placesRepo_, id<IPlaceRepoModule>)

FOUNDATION_EXPORT NSString *ResourceManager_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ResourceManager, TAG_, NSString *)

FOUNDATION_EXPORT ResourceManager *ResourceManager_s_instance_;
J2OBJC_STATIC_FIELD_GETTER(ResourceManager, s_instance_, ResourceManager *)
//J2OBJC_STATIC_FIELD_SETTER(ResourceManager, s_instance_, ResourceManager *)

FOUNDATION_EXPORT id ResourceManager_m_lock_;
J2OBJC_STATIC_FIELD_GETTER(ResourceManager, m_lock_, id)
//J2OBJC_STATIC_FIELD_SETTER(ResourceManager, m_lock_, id)

typedef ResourceManager ComIntelWearablePlatformTimeiqSensorsResourcemanagerResourceManager;

#endif // _ResourceManager_H_
