//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/resolver/factory/ResolverClassPool.java
//

#ifndef _ResolverClassPool_H_
#define _ResolverClassPool_H_

@protocol IResolverModule;

#import "JB.h"

/**
 @brief Created by stzour on 12/02/2015.
 */
@interface ResolverClassPool : NSObject {
}

+ (id<IResolverModule>)getResolver;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ResolverClassPool_init() {}

typedef ResolverClassPool ComIntelWearablePlatformTimeiqResolverFactoryResolverClassPool;

#endif // _ResolverClassPool_H_
