//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/resolver/ResolverImpl.java
//

#ifndef _ResolverImpl_H_
#define _ResolverImpl_H_

@class FlowType;
#import "NSNumber+JavaAPI.h"
@class ResolveRequestV1;
@class ResolveResponseV1;
@class ResolvedLocation;
@class ResolvedLocationsResponse;
@class ResultData;
@class TSOPlace;
@class UniqueCalendarEvent;
@protocol IApiUsageUtil;
#import "JBArrayList.h"

#import "JB.h"
#include "IResolver.h"

#define ResolverImpl_DEFAULT_MAX_RESULTS 20
#define ResolverImpl_PHONE_DEFINED_RESULTS 1

/**
 @brief Created by stzour on 09/02/2015.
 */
@interface ResolverImpl : NSObject < IResolver > {
 @public
  id<IApiUsageUtil> apiUsageUtil_;
}

- (instancetype)init;

- (instancetype)initWithIApiUsageUtil:(id<IApiUsageUtil>)apiUsageUtil;

- (ResultData *)resolveMeetingWithNSString:(NSString *)searchTerm
                              withTSOPlace:(TSOPlace *)location
                              withNSString:(NSString *)subject
                                  withLong:(long64)startTime
                                  withLong:(long64)endTime
                              withNSString:(NSString *)organizerEmail
                          withJavaUtilList:(ArrayList*)attendees
                       withJBBoolean:(JBBoolean *)organizer
                       withJBBoolean:(JBBoolean *)allDayEvent
                       withJBBoolean:(JBBoolean *)recurrent;

- (ResultData *)resolveMeetingWithNSString:(NSString *)searchTerm
                              withTSOPlace:(TSOPlace *)location
                              withNSString:(NSString *)subject
                                  withLong:(long64)startTime
                                  withLong:(long64)endTime
                              withNSString:(NSString *)organizerEmail
                          withJavaUtilList:(ArrayList*)attendees
                       withJBBoolean:(JBBoolean *)organizer
                       withJBBoolean:(JBBoolean *)allDayEvent
                       withJBBoolean:(JBBoolean *)recurrent
                                   withInt:(int)maxResults;

- (ResultData *)resolveLocationWithNSString:(NSString *)searchTerm
                               withTSOPlace:(TSOPlace *)location;

- (ResultData *)resolveLocationWithNSString:(NSString *)searchTerm
                               withTSOPlace:(TSOPlace *)location
                                    withInt:(int)maxResults;

- (ResultData *)getResolvedLocationsWithNSString:(NSString *)searchTerm
                                    withTSOPlace:(TSOPlace *)location
                                         withInt:(int)maxResults
                                    withNSString:(NSString *)userId
                                    withNSString:(NSString *)requestId
                                withFlowType:(FlowType *)flowType;

- (ResultData *)getResolvedExpressionsWithNSString:(NSString *)searchTerm
                                      withTSOPlace:(TSOPlace *)location
                                           withInt:(int)maxResults
                                      withNSString:(NSString *)userId
                                      withNSString:(NSString *)requestId
                                  withFlowType:(FlowType *)flowType
                           withUniqueCalendarEvent:(UniqueCalendarEvent *)calendarEvent;

- (ResultData *)resolveBusinessPhoneWithNSString:(NSString *)phoneNumber
                                    withTSOPlace:(TSOPlace *)location;

- (ResultData *)resolveAsYouTypeLocationWithNSString:(NSString *)searchTerm
                                        withTSOPlace:(TSOPlace *)location
                                             withInt:(int)maxResults;

- (ResultData *)getAdditionalDetailsWithNSString:(NSString *)googleLocationId;

- (ResultData *)getResolveBusinessPhoneWithNSString:(NSString *)phoneNumber
                                       withTSOPlace:(TSOPlace *)location
                                       withNSString:(NSString *)userId
                                       withNSString:(NSString *)requestId
                                   withFlowType:(FlowType *)flowType;

- (ResultData *)handleRetryIfNeededWithResultData:(ResultData *)firstResponse
                                     withNSString:(NSString *)searchTerm
                                     withTSOPlace:(TSOPlace *)location
                                          withInt:(int)maxNumOfResults
                                 withFlowType:(FlowType *)flowType
                                     withNSString:(NSString *)userId
                                     withNSString:(NSString *)requestId;

- (boolean)resolverInvalidResponseWithResultData:(ResultData *)res;

- (ResultData *)getResolveBusinessPhoneResponseResultDataWithResultData:(ResultData *)sdkRes;

- (ResolvedLocation *)getBusinessLocationWithResolvedLocationsResponse:(ResolvedLocationsResponse *)serverRes;

- (ResultData *)handleResolveRequestWithNSString:(NSString *)searchTerm
                                    withTSOPlace:(TSOPlace *)location
                                         withInt:(int)maxResults
                                withFlowType:(FlowType *)flowType
                                    withNSString:(NSString *)userId
                                    withNSString:(NSString *)requestId;

- (ResultData *)handleResolveRequestWithNSString:(NSString *)searchTerm
                                    withTSOPlace:(TSOPlace *)location
                                         withInt:(int)maxResults
                                withFlowType:(FlowType *)flowType
                                    withNSString:(NSString *)userId
                                    withNSString:(NSString *)requestId
                         withUniqueCalendarEvent:(UniqueCalendarEvent *)calendarEvent;

- (void)sendToAuditWithNSString:(NSString *)searchTerm
                   withTSOPlace:(TSOPlace *)location
                        withInt:(int)maxResults
               withFlowType:(FlowType *)flowType
                   withNSString:(NSString *)userId
                   withNSString:(NSString *)requestId
                 withResultData:(ResultData *)res;

- (ResolveResponseV1 *)sendToServerWithResolveRequestV1:(ResolveRequestV1 *)resolveRequest;

- (NSString *)generateRequestId;

- (NSString *)getUserId;

- (void)copyAllFieldsTo:(ResolverImpl *)other;

@end

FOUNDATION_EXPORT BOOL ResolverImpl_initialized;
J2OBJC_STATIC_INIT(ResolverImpl)

//J2OBJC_FIELD_SETTER(ResolverImpl, apiUsageUtil_, id<IApiUsageUtil>)

J2OBJC_STATIC_FIELD_GETTER(ResolverImpl, DEFAULT_MAX_RESULTS, int)

FOUNDATION_EXPORT TSOPlace *ResolverImpl_DEFAULT_LOCATION_;
J2OBJC_STATIC_FIELD_GETTER(ResolverImpl, DEFAULT_LOCATION_, TSOPlace *)

J2OBJC_STATIC_FIELD_GETTER(ResolverImpl, PHONE_DEFINED_RESULTS, int)

typedef ResolverImpl ComIntelWearablePlatformTimeiqResolverResolverImpl;

#endif // _ResolverImpl_H_
