//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/platform/android/factory/ResolverFactoryInitializer.java
//

#ifndef _ResolverFactoryInitializer_H_
#define _ResolverFactoryInitializer_H_

@class ClassFactory;

#import "JB.h"

/**
 @brief Created by stzour on 12/02/2015.
 */
@interface ResolverFactoryInitializer : NSObject {
}

+ (void)initFactoryGeneralWithClassFactory:(ClassFactory *)classFactory OBJC_METHOD_FAMILY_NONE;

+ (void)initFactoryForTestWithClassFactory:(ClassFactory *)classFactory OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void ResolverFactoryInitializer_init() {}

typedef ResolverFactoryInitializer ComIntelWearablePlatformTimeiqPlatformAndroidFactoryResolverFactoryInitializer;

#endif // _ResolverFactoryInitializer_H_
