//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/resolver/Resolver.java
//

#ifndef _Resolver_H_
#define _Resolver_H_

@class ClassFactory;
#import "NSNumber+JavaAPI.h"
@class ResultData;
@class TSOPlace;
@protocol IApiUsageUtil;
@protocol IResolverModule;
#import "JBArrayList.h"

#import "JB.h"
#import "IResolver.h"

/**
 @brief Created by stzour on 07/12/2015.
 */
@interface Resolver : NSObject < IResolver > {
 @public
  id<IResolverModule> resolverModule_;
  id<IApiUsageUtil> apiUsageUtil_;
}

- (instancetype)init;

- (instancetype)initWithClassFactory:(ClassFactory *)classFactory;

- (instancetype)initWithIResolverModule:(id<IResolverModule>)resolverModule
                      withIApiUsageUtil:(id<IApiUsageUtil>)apiUsageUtil;

- (ResultData *)resolveMeetingWithNSString:(NSString *)searchTerm
                              withTSOPlace:(TSOPlace *)location
                              withNSString:(NSString *)subject
                                  withLong:(long64)startTime
                                  withLong:(long64)endTime
                              withNSString:(NSString *)organizerEmail
                          withJavaUtilList:(ArrayList*)attendees
                       withJBBoolean:(JBBoolean *)organizer
                       withJBBoolean:(JBBoolean *)allDayEvent
                       withJBBoolean:(JBBoolean *)recurrent;

- (ResultData *)resolveMeetingWithNSString:(NSString *)searchTerm
                              withTSOPlace:(TSOPlace *)location
                              withNSString:(NSString *)subject
                                  withLong:(long64)startTime
                                  withLong:(long64)endTime
                              withNSString:(NSString *)organizerEmail
                          withJavaUtilList:(ArrayList*)attendees
                       withJBBoolean:(JBBoolean *)organizer
                       withJBBoolean:(JBBoolean *)allDayEvent
                       withJBBoolean:(JBBoolean *)recurrent
                                   withInt:(int)maxResults;

- (ResultData *)resolveLocationWithNSString:(NSString *)searchTerm
                               withTSOPlace:(TSOPlace *)location;

- (ResultData *)resolveLocationWithNSString:(NSString *)searchTerm
                               withTSOPlace:(TSOPlace *)location
                                    withInt:(int)maxResults;

- (ResultData *)resolveBusinessPhoneWithNSString:(NSString *)phoneNumber
                                    withTSOPlace:(TSOPlace *)location;

- (void)copyAllFieldsTo:(Resolver *)other;

@end

__attribute__((always_inline)) inline void Resolver_init() {}

//J2OBJC_FIELD_SETTER(Resolver, resolverModule_, id<IResolverModule>)
//J2OBJC_FIELD_SETTER(Resolver, apiUsageUtil_, id<IApiUsageUtil>)

typedef Resolver ComIntelWearablePlatformTimeiqResolverResolver;

#endif // _Resolver_H_
