//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/resolver/ResolverImplStub.java
//

#ifndef _ResolverImplStub_H_
#define _ResolverImplStub_H_

#import "NSNumber+JavaAPI.h"
@class ResultData;
@class TSOPlace;
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "ResolverImpl.h"

/**
 @brief Created by stzour on 12/02/2015.
 */
@interface ResolverImplStub : ResolverImpl {
 @public
  HashMap* searchTermToMockRespnse_;
  boolean isTestingResolveBySourceLocation_;
  int numberOfResolverCalls_;
}

- (void)setTestingResolveBySourceLocationWithBoolean:(boolean)isTestingResolveBySourceLocation;

- (void)putMockResponseWithNSString:(NSString *)searchTerm
                     withResultData:(ResultData *)mockResponse;

- (ResultData *)resolveLocationWithNSString:(NSString *)searchTerm
                               withTSOPlace:(TSOPlace *)location;

- (ResultData *)resolveMeetingWithNSString:(NSString *)searchTerm
                              withTSOPlace:(TSOPlace *)location
                              withNSString:(NSString *)subject
                                  withLong:(long64)startTime
                                  withLong:(long64)endTime
                              withNSString:(NSString *)organizerEmail
                          withJavaUtilList:(ArrayList*)attendees
                       withJBBoolean:(JBBoolean *)organizer
                       withJBBoolean:(JBBoolean *)allDayEvent
                       withJBBoolean:(JBBoolean *)recurrent;

- (boolean)shouldLocationGetResponseWithTSOPlace:(TSOPlace *)location;

- (void)clear;

- (int)getNumberOfResolverCalls;

- (instancetype)init;

- (void)copyAllFieldsTo:(ResolverImplStub *)other;

@end

FOUNDATION_EXPORT BOOL ResolverImplStub_initialized;
J2OBJC_STATIC_INIT(ResolverImplStub)

//J2OBJC_FIELD_SETTER(ResolverImplStub, searchTermToMockRespnse_, HashMap*)

FOUNDATION_EXPORT TSOPlace *ResolverImplStub_LOCATION_WHICH_SHOULD_RECEIVE_RESPONSE_;
J2OBJC_STATIC_FIELD_GETTER(ResolverImplStub, LOCATION_WHICH_SHOULD_RECEIVE_RESPONSE_, TSOPlace *)
//J2OBJC_STATIC_FIELD_SETTER(ResolverImplStub, LOCATION_WHICH_SHOULD_RECEIVE_RESPONSE_, TSOPlace *)

typedef ResolverImplStub ComIntelWearablePlatformTimeiqResolverResolverImplStub;

@interface ResolverImplStub_MapValue : NSObject {
 @public
  ResultData *resultData_;
}

- (instancetype)initWithResolverImplStub:(ResolverImplStub *)outer$
                          withResultData:(ResultData *)resultData;

- (ResultData *)getResultData;

- (void)copyAllFieldsTo:(ResolverImplStub_MapValue *)other;

@end

__attribute__((always_inline)) inline void ResolverImplStub_MapValue_init() {}

//J2OBJC_FIELD_SETTER(ResolverImplStub_MapValue, resultData_, ResultData *)

#endif // _ResolverImplStub_H_
