//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/resolver/dataobjects/ResolverSdkRequestParams.java
//

#ifndef _ResolverSdkRequestParams_H_
#define _ResolverSdkRequestParams_H_

@class ResolverApiType;
@class TSOPlace;

#import "JB.h"

/**
 @brief Created by stzour on 11/03/2015.
 */
@interface ResolverSdkRequestParams : NSObject {
 @public
  NSString *searchTerm_;
  TSOPlace *location_;
  int maxParams_;
  ResolverApiType *userApiChoice_;
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)searchTerm
                    withTSOPlace:(TSOPlace *)location
         withResolverApiType:(ResolverApiType *)chosenApiType;

- (instancetype)initWithNSString:(NSString *)searchTerm
                    withTSOPlace:(TSOPlace *)location
                         withInt:(int)maxParams
         withResolverApiType:(ResolverApiType *)chosenApiType;

- (NSString *)getSearchTerm;

- (void)setSearchTermWithNSString:(NSString *)searchTerm;

- (TSOPlace *)getLocation;

- (void)setLocationWithTSOPlace:(TSOPlace *)location;

- (int)getMaxParams;

- (void)setMaxParamsWithInt:(int)maxParams;

- (ResolverApiType *)getUserApiChoice;

- (void)setUserApiChoiceWithResolverApiType:(ResolverApiType *)userApiChoice;

- (void)copyAllFieldsTo:(ResolverSdkRequestParams *)other;

@end

__attribute__((always_inline)) inline void ResolverSdkRequestParams_init() {}

//J2OBJC_FIELD_SETTER(ResolverSdkRequestParams, searchTerm_, NSString *)
//J2OBJC_FIELD_SETTER(ResolverSdkRequestParams, location_, TSOPlace *)
//J2OBJC_FIELD_SETTER(ResolverSdkRequestParams, userApiChoice_, ResolverApiType *)

typedef ResolverSdkRequestParams ComIntelWearablePlatformTimeiqResolverDataobjectsResolverSdkRequestParams;

#endif // _ResolverSdkRequestParams_H_
