#ifndef __JavaBridge_ResultCode__
#define __JavaBridge_ResultCode__

#import "JB.h"
#import "JBEnum.h"
#include "NSArray+JavaAPI.h"

//@class ResultCode;

typedef NS_ENUM(NSInteger, eResultCode)
{
 	ResultCode_SUCCESS , 
 	ResultCode_GENERAL_ERROR , 
 	ResultCode_GENERAL_NOT_AUTHENTICATED , 
 	ResultCode_GENERAL_EXTERNAL_PROVIDER_DID_NOT_RESPOND , 
 	ResultCode_GENERAL_EXTERNAL_PROVIDER_FAILURE , 
 	ResultCode_GENERAL_MISSING_MANDATORY_FIELD , 
 	ResultCode_GENERAL_ILLEGAL_PARAMETER_VALUE , 
 	ResultCode_GENERAL_SERVER_ERROR , 
 	ResultCode_GENERAL_EXCEPTION_WAS_THROWN , 
 	ResultCode_GENERAL_NULL_ERROR , 
 	ResultCode_RESPONSE_IS_NULL_ERROR , 
 	ResultCode_PARSE_ERROR_UNSUPPORTED_ENCODING , 
 	ResultCode_SEARCH_TERM_NOT_SUPPORTED , 
 	ResultCode_SEARCH_NO_RESULTS , 
 	ResultCode_LOCATION_IS_NULL , 
 	ResultCode_LOCATION_NO_ACCURACY , 
 	ResultCode_LOCATION_INSUFFICIENT_ACCURACY , 
 	ResultCode_LOCATION_TOO_OLD , 
 	ResultCode_LOCATION_RETRY , 
 	ResultCode_LOCATION_UNRESOLVED , 
 	ResultCode_MOT_MODULE_IS_DISABLED , 
 	ResultCode_MOT_IS_NULL , 
 	ResultCode_NETWORK_HTTP_NO_CONTENT , 
 	ResultCode_NETWORK_HTTP_INTERNAL_ERROR , 
 	ResultCode_SHOULD_RE_TRY , 
 	ResultCode_TTL_CANNOT_REACH_DESTINATION_IN_TIME , 
 	ResultCode_TTL_NO_ROUTE_TO_DESTINATION , 
 	ResultCode_TTL_IS_OVERDUE , 
 	ResultCode_TTL_DESTINATION_TOO_FAR_FOR_NAVIGATION , 
 	ResultCode_TTL_NO_NEED_TO_WAKE_UP_AGAIN , 
 	ResultCode_TTL_ALERT_ALREADY_NOTIFIED , 
 	ResultCode_NO_NEED_TO_POSTPONE_FIRST_WAKE_UP , 
 	ResultCode_ROUTE_REQUEST_FOR_WALK_WHILE_DRIVING , 
 	ResultCode_ROUTE_REQUEST_FOR_TTL_IN_THE_PAST , 
 	ResultCode_ADD_TRIGGER_WITH_LISTENER , 
 	ResultCode_TRIGGERS_LISTENER_NOT_REGISTERED , 
 	ResultCode_COULD_NOT_ADD_TRIGGER , 
 	ResultCode_TRIGGER_ALREADY_ADDED , 
 	ResultCode_REMINDER_ALREADY_ADDED , 
 	ResultCode_COULD_NOT_ADD_REMINDER , 
 	ResultCode_REMINDER_IS_ACTIVE , 
 	ResultCode_REMINDER_IS_ENDED , 
 	ResultCode_REMINDER_NOT_FOUND , 
 	ResultCode_ERROR_EVENT_LOCATION_INVALID , 
 	ResultCode_ERROR_EVENT_TIME_INVALID , 
 	ResultCode_ERROR_EVENT_TIME_IS_IN_THE_PAST , 
 	ResultCode_ERROR_EVENT_ID_EMPTY , 
 	ResultCode_ERROR_EVENT_ID_NULL , 
 	ResultCode_ERROR_EVENT_ID_NOT_FOUND , 
 	ResultCode_ERROR_EVENT_NULL , 
 	ResultCode_ERROR_EVENT_DURATION_INVALID , 
 	ResultCode_ERROR_NEGATIVE_TIME , 
 	ResultCode_ERROR_START_TIME_BIGGER_THAN_END_TIME , 
 	ResultCode_ERROR_EVENT_USER_ACTION_IS_NULL , 
 	ResultCode_ERROR_EVENT_USER_ACTION_DELAY_IS_NEGATIVE , 
 	ResultCode_ERROR_EVENT_MAX_ALLOWED_DELAY_IS_ONE_DAY , 
 	ResultCode_ERROR_EVENT_DELETION_FAILED , 
 	ResultCode_ERROR_CANNOT_EXECUTE_RECURRENT_OPERATION_ON_NON_RECURRENT_EVENT , 
 	ResultCode_ERROR_EVENT_TYPE_IS_NULL , 
 	ResultCode_ERROR_EVENT_TYPE_LIST_EMPTY , 
 	ResultCode_ERROR_EVENT_TYPE_LIST_NULL , 
 	ResultCode_ERROR_EVENT_GENERAL_REMINDER_IS_NEGATIVE , 
 	ResultCode_ERROR_EVENT_CALENDAR_IDS_NULL , 
 	ResultCode_ERROR_EVENT_CALENDAR_IDS_EMPTY , 
 	ResultCode_ERROR_EVENT_CALENDAR_ID_NOT_FOUND , 
 	ResultCode_ERROR_FAILED_TO_ADD_EVENT , 
 	ResultCode_ERROR_FAILED_TO_UPDATE_EVENT , 
 	ResultCode_ERROR_WEEKLY_RECURRENCE_MUST_STATE_THE_DAYS_OF_WEEK , 
 	ResultCode_ERROR_MONTHLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH , 
 	ResultCode_ERROR_YEARLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH_AND_MONTH_OF_YEAR , 
 	ResultCode_ERROR_RECURRENCE_SHOULD_EITHER_HAVE_ENDDATE_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE , 
 	ResultCode_ERROR_RECURRENCE_SHOULD_EITHER_HAVE_NUMBEROFOCCURRENCES_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE , 
 	ResultCode_ERROR_RECURRENCE_INTERVAL_MUST_BE_GREATER_THAN_ZERO , 
 	ResultCode_ERROR_RECURRENCE_INVALID_VALUE_DAYS_OF_WEEK , 
 	ResultCode_ERROR_RECURRENCE_INVALID_VALUE_DAY_OF_MONTH , 
 	ResultCode_ERROR_RECURRENCE_INVALID_VALUE_MONTH_OF_YEAR , 
 	ResultCode_ERROR_FAILED_CALENDAR_SYNC , 
 	ResultCode_ERROR_NO_ETA_DUE_TO_INVALID_LOCATION , 
 	ResultCode_ERROR_UNSUPPORTED_EVENT_TYPE , 
 	ResultCode_ERROR_NOT_ALL_EVENTS_IN_TIME_FRAME_WERE_FETCHED , 
 	ResultCode_WRITE_CALENDAR_UNDEFINED , 
 	ResultCode_READ_CALENDARS_UNDEFINED , 
 	ResultCode_UNKNOWN_CALENDAR_ID , 
 	ResultCode_ERROR_NO_PLACE_FOUND , 
 	ResultCode_PLACE_ALREADY_EXISTS , 

};

@interface ResultCode : Enum

+ (Array*)values;
+ (Array*) getEnumConstants;
+ (ResultCode *)valueOfWithNSString:(NSString*)name;
+ (ResultCode *)valueOf:(NSString*)name;
+ (ResultCode *)parseWithInt:(int)name;
+ (ResultCode *)fromIdWithInt:(int)name;
+ (ResultCode *)fromId:(int)val;

+ (void)load;
-(eResultCode) ordinal;

 +(ResultCode*) SUCCESS; 
 +(ResultCode*) GENERAL_ERROR; 
 +(ResultCode*) GENERAL_NOT_AUTHENTICATED; 
 +(ResultCode*) GENERAL_EXTERNAL_PROVIDER_DID_NOT_RESPOND; 
 +(ResultCode*) GENERAL_EXTERNAL_PROVIDER_FAILURE; 
 +(ResultCode*) GENERAL_MISSING_MANDATORY_FIELD; 
 +(ResultCode*) GENERAL_ILLEGAL_PARAMETER_VALUE; 
 +(ResultCode*) GENERAL_SERVER_ERROR; 
 +(ResultCode*) GENERAL_EXCEPTION_WAS_THROWN; 
 +(ResultCode*) GENERAL_NULL_ERROR; 
 +(ResultCode*) RESPONSE_IS_NULL_ERROR; 
 +(ResultCode*) PARSE_ERROR_UNSUPPORTED_ENCODING; 
 +(ResultCode*) SEARCH_TERM_NOT_SUPPORTED; 
 +(ResultCode*) SEARCH_NO_RESULTS; 
 +(ResultCode*) LOCATION_IS_NULL; 
 +(ResultCode*) LOCATION_NO_ACCURACY; 
 +(ResultCode*) LOCATION_INSUFFICIENT_ACCURACY; 
 +(ResultCode*) LOCATION_TOO_OLD; 
 +(ResultCode*) LOCATION_RETRY; 
 +(ResultCode*) LOCATION_UNRESOLVED; 
 +(ResultCode*) MOT_MODULE_IS_DISABLED; 
 +(ResultCode*) MOT_IS_NULL; 
 +(ResultCode*) NETWORK_HTTP_NO_CONTENT; 
 +(ResultCode*) NETWORK_HTTP_INTERNAL_ERROR; 
 +(ResultCode*) SHOULD_RE_TRY; 
 +(ResultCode*) TTL_CANNOT_REACH_DESTINATION_IN_TIME; 
 +(ResultCode*) TTL_NO_ROUTE_TO_DESTINATION; 
 +(ResultCode*) TTL_IS_OVERDUE; 
 +(ResultCode*) TTL_DESTINATION_TOO_FAR_FOR_NAVIGATION; 
 +(ResultCode*) TTL_NO_NEED_TO_WAKE_UP_AGAIN; 
 +(ResultCode*) TTL_ALERT_ALREADY_NOTIFIED; 
 +(ResultCode*) NO_NEED_TO_POSTPONE_FIRST_WAKE_UP; 
 +(ResultCode*) ROUTE_REQUEST_FOR_WALK_WHILE_DRIVING; 
 +(ResultCode*) ROUTE_REQUEST_FOR_TTL_IN_THE_PAST; 
 +(ResultCode*) ADD_TRIGGER_WITH_LISTENER; 
 +(ResultCode*) TRIGGERS_LISTENER_NOT_REGISTERED; 
 +(ResultCode*) COULD_NOT_ADD_TRIGGER; 
 +(ResultCode*) TRIGGER_ALREADY_ADDED; 
 +(ResultCode*) REMINDER_ALREADY_ADDED; 
 +(ResultCode*) COULD_NOT_ADD_REMINDER; 
 +(ResultCode*) REMINDER_IS_ACTIVE; 
 +(ResultCode*) REMINDER_IS_ENDED; 
 +(ResultCode*) REMINDER_NOT_FOUND; 
 +(ResultCode*) ERROR_EVENT_LOCATION_INVALID; 
 +(ResultCode*) ERROR_EVENT_TIME_INVALID; 
 +(ResultCode*) ERROR_EVENT_TIME_IS_IN_THE_PAST; 
 +(ResultCode*) ERROR_EVENT_ID_EMPTY; 
 +(ResultCode*) ERROR_EVENT_ID_NULL; 
 +(ResultCode*) ERROR_EVENT_ID_NOT_FOUND; 
 +(ResultCode*) ERROR_EVENT_NULL; 
 +(ResultCode*) ERROR_EVENT_DURATION_INVALID; 
 +(ResultCode*) ERROR_NEGATIVE_TIME; 
 +(ResultCode*) ERROR_START_TIME_BIGGER_THAN_END_TIME; 
 +(ResultCode*) ERROR_EVENT_USER_ACTION_IS_NULL; 
 +(ResultCode*) ERROR_EVENT_USER_ACTION_DELAY_IS_NEGATIVE; 
 +(ResultCode*) ERROR_EVENT_MAX_ALLOWED_DELAY_IS_ONE_DAY; 
 +(ResultCode*) ERROR_EVENT_DELETION_FAILED; 
 +(ResultCode*) ERROR_CANNOT_EXECUTE_RECURRENT_OPERATION_ON_NON_RECURRENT_EVENT; 
 +(ResultCode*) ERROR_EVENT_TYPE_IS_NULL; 
 +(ResultCode*) ERROR_EVENT_TYPE_LIST_EMPTY; 
 +(ResultCode*) ERROR_EVENT_TYPE_LIST_NULL; 
 +(ResultCode*) ERROR_EVENT_GENERAL_REMINDER_IS_NEGATIVE; 
 +(ResultCode*) ERROR_EVENT_CALENDAR_IDS_NULL; 
 +(ResultCode*) ERROR_EVENT_CALENDAR_IDS_EMPTY; 
 +(ResultCode*) ERROR_EVENT_CALENDAR_ID_NOT_FOUND; 
 +(ResultCode*) ERROR_FAILED_TO_ADD_EVENT; 
 +(ResultCode*) ERROR_FAILED_TO_UPDATE_EVENT; 
 +(ResultCode*) ERROR_WEEKLY_RECURRENCE_MUST_STATE_THE_DAYS_OF_WEEK; 
 +(ResultCode*) ERROR_MONTHLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH; 
 +(ResultCode*) ERROR_YEARLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH_AND_MONTH_OF_YEAR; 
 +(ResultCode*) ERROR_RECURRENCE_SHOULD_EITHER_HAVE_ENDDATE_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE; 
 +(ResultCode*) ERROR_RECURRENCE_SHOULD_EITHER_HAVE_NUMBEROFOCCURRENCES_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE; 
 +(ResultCode*) ERROR_RECURRENCE_INTERVAL_MUST_BE_GREATER_THAN_ZERO; 
 +(ResultCode*) ERROR_RECURRENCE_INVALID_VALUE_DAYS_OF_WEEK; 
 +(ResultCode*) ERROR_RECURRENCE_INVALID_VALUE_DAY_OF_MONTH; 
 +(ResultCode*) ERROR_RECURRENCE_INVALID_VALUE_MONTH_OF_YEAR; 
 +(ResultCode*) ERROR_FAILED_CALENDAR_SYNC; 
 +(ResultCode*) ERROR_NO_ETA_DUE_TO_INVALID_LOCATION; 
 +(ResultCode*) ERROR_UNSUPPORTED_EVENT_TYPE; 
 +(ResultCode*) ERROR_NOT_ALL_EVENTS_IN_TIME_FRAME_WERE_FETCHED; 
 +(ResultCode*) WRITE_CALENDAR_UNDEFINED; 
 +(ResultCode*) READ_CALENDARS_UNDEFINED; 
 +(ResultCode*) UNKNOWN_CALENDAR_ID; 
 +(ResultCode*) ERROR_NO_PLACE_FOUND; 
 +(ResultCode*) PLACE_ALREADY_EXISTS; 


@end

 #define ResultCode_get_SUCCESS() [ResultCode SUCCESS] 
 #define ResultCode_get_GENERAL_ERROR() [ResultCode GENERAL_ERROR] 
 #define ResultCode_get_GENERAL_NOT_AUTHENTICATED() [ResultCode GENERAL_NOT_AUTHENTICATED] 
 #define ResultCode_get_GENERAL_EXTERNAL_PROVIDER_DID_NOT_RESPOND() [ResultCode GENERAL_EXTERNAL_PROVIDER_DID_NOT_RESPOND] 
 #define ResultCode_get_GENERAL_EXTERNAL_PROVIDER_FAILURE() [ResultCode GENERAL_EXTERNAL_PROVIDER_FAILURE] 
 #define ResultCode_get_GENERAL_MISSING_MANDATORY_FIELD() [ResultCode GENERAL_MISSING_MANDATORY_FIELD] 
 #define ResultCode_get_GENERAL_ILLEGAL_PARAMETER_VALUE() [ResultCode GENERAL_ILLEGAL_PARAMETER_VALUE] 
 #define ResultCode_get_GENERAL_SERVER_ERROR() [ResultCode GENERAL_SERVER_ERROR] 
 #define ResultCode_get_GENERAL_EXCEPTION_WAS_THROWN() [ResultCode GENERAL_EXCEPTION_WAS_THROWN] 
 #define ResultCode_get_GENERAL_NULL_ERROR() [ResultCode GENERAL_NULL_ERROR] 
 #define ResultCode_get_RESPONSE_IS_NULL_ERROR() [ResultCode RESPONSE_IS_NULL_ERROR] 
 #define ResultCode_get_PARSE_ERROR_UNSUPPORTED_ENCODING() [ResultCode PARSE_ERROR_UNSUPPORTED_ENCODING] 
 #define ResultCode_get_SEARCH_TERM_NOT_SUPPORTED() [ResultCode SEARCH_TERM_NOT_SUPPORTED] 
 #define ResultCode_get_SEARCH_NO_RESULTS() [ResultCode SEARCH_NO_RESULTS] 
 #define ResultCode_get_LOCATION_IS_NULL() [ResultCode LOCATION_IS_NULL] 
 #define ResultCode_get_LOCATION_NO_ACCURACY() [ResultCode LOCATION_NO_ACCURACY] 
 #define ResultCode_get_LOCATION_INSUFFICIENT_ACCURACY() [ResultCode LOCATION_INSUFFICIENT_ACCURACY] 
 #define ResultCode_get_LOCATION_TOO_OLD() [ResultCode LOCATION_TOO_OLD] 
 #define ResultCode_get_LOCATION_RETRY() [ResultCode LOCATION_RETRY] 
 #define ResultCode_get_LOCATION_UNRESOLVED() [ResultCode LOCATION_UNRESOLVED] 
 #define ResultCode_get_MOT_MODULE_IS_DISABLED() [ResultCode MOT_MODULE_IS_DISABLED] 
 #define ResultCode_get_MOT_IS_NULL() [ResultCode MOT_IS_NULL] 
 #define ResultCode_get_NETWORK_HTTP_NO_CONTENT() [ResultCode NETWORK_HTTP_NO_CONTENT] 
 #define ResultCode_get_NETWORK_HTTP_INTERNAL_ERROR() [ResultCode NETWORK_HTTP_INTERNAL_ERROR] 
 #define ResultCode_get_SHOULD_RE_TRY() [ResultCode SHOULD_RE_TRY] 
 #define ResultCode_get_TTL_CANNOT_REACH_DESTINATION_IN_TIME() [ResultCode TTL_CANNOT_REACH_DESTINATION_IN_TIME] 
 #define ResultCode_get_TTL_NO_ROUTE_TO_DESTINATION() [ResultCode TTL_NO_ROUTE_TO_DESTINATION] 
 #define ResultCode_get_TTL_IS_OVERDUE() [ResultCode TTL_IS_OVERDUE] 
 #define ResultCode_get_TTL_DESTINATION_TOO_FAR_FOR_NAVIGATION() [ResultCode TTL_DESTINATION_TOO_FAR_FOR_NAVIGATION] 
 #define ResultCode_get_TTL_NO_NEED_TO_WAKE_UP_AGAIN() [ResultCode TTL_NO_NEED_TO_WAKE_UP_AGAIN] 
 #define ResultCode_get_TTL_ALERT_ALREADY_NOTIFIED() [ResultCode TTL_ALERT_ALREADY_NOTIFIED] 
 #define ResultCode_get_NO_NEED_TO_POSTPONE_FIRST_WAKE_UP() [ResultCode NO_NEED_TO_POSTPONE_FIRST_WAKE_UP] 
 #define ResultCode_get_ROUTE_REQUEST_FOR_WALK_WHILE_DRIVING() [ResultCode ROUTE_REQUEST_FOR_WALK_WHILE_DRIVING] 
 #define ResultCode_get_ROUTE_REQUEST_FOR_TTL_IN_THE_PAST() [ResultCode ROUTE_REQUEST_FOR_TTL_IN_THE_PAST] 
 #define ResultCode_get_ADD_TRIGGER_WITH_LISTENER() [ResultCode ADD_TRIGGER_WITH_LISTENER] 
 #define ResultCode_get_TRIGGERS_LISTENER_NOT_REGISTERED() [ResultCode TRIGGERS_LISTENER_NOT_REGISTERED] 
 #define ResultCode_get_COULD_NOT_ADD_TRIGGER() [ResultCode COULD_NOT_ADD_TRIGGER] 
 #define ResultCode_get_TRIGGER_ALREADY_ADDED() [ResultCode TRIGGER_ALREADY_ADDED] 
 #define ResultCode_get_REMINDER_ALREADY_ADDED() [ResultCode REMINDER_ALREADY_ADDED] 
 #define ResultCode_get_COULD_NOT_ADD_REMINDER() [ResultCode COULD_NOT_ADD_REMINDER] 
 #define ResultCode_get_REMINDER_IS_ACTIVE() [ResultCode REMINDER_IS_ACTIVE] 
 #define ResultCode_get_REMINDER_IS_ENDED() [ResultCode REMINDER_IS_ENDED] 
 #define ResultCode_get_REMINDER_NOT_FOUND() [ResultCode REMINDER_NOT_FOUND] 
 #define ResultCode_get_ERROR_EVENT_LOCATION_INVALID() [ResultCode ERROR_EVENT_LOCATION_INVALID] 
 #define ResultCode_get_ERROR_EVENT_TIME_INVALID() [ResultCode ERROR_EVENT_TIME_INVALID] 
 #define ResultCode_get_ERROR_EVENT_TIME_IS_IN_THE_PAST() [ResultCode ERROR_EVENT_TIME_IS_IN_THE_PAST] 
 #define ResultCode_get_ERROR_EVENT_ID_EMPTY() [ResultCode ERROR_EVENT_ID_EMPTY] 
 #define ResultCode_get_ERROR_EVENT_ID_NULL() [ResultCode ERROR_EVENT_ID_NULL] 
 #define ResultCode_get_ERROR_EVENT_ID_NOT_FOUND() [ResultCode ERROR_EVENT_ID_NOT_FOUND] 
 #define ResultCode_get_ERROR_EVENT_NULL() [ResultCode ERROR_EVENT_NULL] 
 #define ResultCode_get_ERROR_EVENT_DURATION_INVALID() [ResultCode ERROR_EVENT_DURATION_INVALID] 
 #define ResultCode_get_ERROR_NEGATIVE_TIME() [ResultCode ERROR_NEGATIVE_TIME] 
 #define ResultCode_get_ERROR_START_TIME_BIGGER_THAN_END_TIME() [ResultCode ERROR_START_TIME_BIGGER_THAN_END_TIME] 
 #define ResultCode_get_ERROR_EVENT_USER_ACTION_IS_NULL() [ResultCode ERROR_EVENT_USER_ACTION_IS_NULL] 
 #define ResultCode_get_ERROR_EVENT_USER_ACTION_DELAY_IS_NEGATIVE() [ResultCode ERROR_EVENT_USER_ACTION_DELAY_IS_NEGATIVE] 
 #define ResultCode_get_ERROR_EVENT_MAX_ALLOWED_DELAY_IS_ONE_DAY() [ResultCode ERROR_EVENT_MAX_ALLOWED_DELAY_IS_ONE_DAY] 
 #define ResultCode_get_ERROR_EVENT_DELETION_FAILED() [ResultCode ERROR_EVENT_DELETION_FAILED] 
 #define ResultCode_get_ERROR_CANNOT_EXECUTE_RECURRENT_OPERATION_ON_NON_RECURRENT_EVENT() [ResultCode ERROR_CANNOT_EXECUTE_RECURRENT_OPERATION_ON_NON_RECURRENT_EVENT] 
 #define ResultCode_get_ERROR_EVENT_TYPE_IS_NULL() [ResultCode ERROR_EVENT_TYPE_IS_NULL] 
 #define ResultCode_get_ERROR_EVENT_TYPE_LIST_EMPTY() [ResultCode ERROR_EVENT_TYPE_LIST_EMPTY] 
 #define ResultCode_get_ERROR_EVENT_TYPE_LIST_NULL() [ResultCode ERROR_EVENT_TYPE_LIST_NULL] 
 #define ResultCode_get_ERROR_EVENT_GENERAL_REMINDER_IS_NEGATIVE() [ResultCode ERROR_EVENT_GENERAL_REMINDER_IS_NEGATIVE] 
 #define ResultCode_get_ERROR_EVENT_CALENDAR_IDS_NULL() [ResultCode ERROR_EVENT_CALENDAR_IDS_NULL] 
 #define ResultCode_get_ERROR_EVENT_CALENDAR_IDS_EMPTY() [ResultCode ERROR_EVENT_CALENDAR_IDS_EMPTY] 
 #define ResultCode_get_ERROR_EVENT_CALENDAR_ID_NOT_FOUND() [ResultCode ERROR_EVENT_CALENDAR_ID_NOT_FOUND] 
 #define ResultCode_get_ERROR_FAILED_TO_ADD_EVENT() [ResultCode ERROR_FAILED_TO_ADD_EVENT] 
 #define ResultCode_get_ERROR_FAILED_TO_UPDATE_EVENT() [ResultCode ERROR_FAILED_TO_UPDATE_EVENT] 
 #define ResultCode_get_ERROR_WEEKLY_RECURRENCE_MUST_STATE_THE_DAYS_OF_WEEK() [ResultCode ERROR_WEEKLY_RECURRENCE_MUST_STATE_THE_DAYS_OF_WEEK] 
 #define ResultCode_get_ERROR_MONTHLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH() [ResultCode ERROR_MONTHLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH] 
 #define ResultCode_get_ERROR_YEARLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH_AND_MONTH_OF_YEAR() [ResultCode ERROR_YEARLY_RECURRENCE_MUST_STATE_THE_DAY_OF_MONTH_AND_MONTH_OF_YEAR] 
 #define ResultCode_get_ERROR_RECURRENCE_SHOULD_EITHER_HAVE_ENDDATE_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE() [ResultCode ERROR_RECURRENCE_SHOULD_EITHER_HAVE_ENDDATE_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE] 
 #define ResultCode_get_ERROR_RECURRENCE_SHOULD_EITHER_HAVE_NUMBEROFOCCURRENCES_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE() [ResultCode ERROR_RECURRENCE_SHOULD_EITHER_HAVE_NUMBEROFOCCURRENCES_OR_SET_BOOLEAN_NOENDDATE_TO_TRUE] 
 #define ResultCode_get_ERROR_RECURRENCE_INTERVAL_MUST_BE_GREATER_THAN_ZERO() [ResultCode ERROR_RECURRENCE_INTERVAL_MUST_BE_GREATER_THAN_ZERO] 
 #define ResultCode_get_ERROR_RECURRENCE_INVALID_VALUE_DAYS_OF_WEEK() [ResultCode ERROR_RECURRENCE_INVALID_VALUE_DAYS_OF_WEEK] 
 #define ResultCode_get_ERROR_RECURRENCE_INVALID_VALUE_DAY_OF_MONTH() [ResultCode ERROR_RECURRENCE_INVALID_VALUE_DAY_OF_MONTH] 
 #define ResultCode_get_ERROR_RECURRENCE_INVALID_VALUE_MONTH_OF_YEAR() [ResultCode ERROR_RECURRENCE_INVALID_VALUE_MONTH_OF_YEAR] 
 #define ResultCode_get_ERROR_FAILED_CALENDAR_SYNC() [ResultCode ERROR_FAILED_CALENDAR_SYNC] 
 #define ResultCode_get_ERROR_NO_ETA_DUE_TO_INVALID_LOCATION() [ResultCode ERROR_NO_ETA_DUE_TO_INVALID_LOCATION] 
 #define ResultCode_get_ERROR_UNSUPPORTED_EVENT_TYPE() [ResultCode ERROR_UNSUPPORTED_EVENT_TYPE] 
 #define ResultCode_get_ERROR_NOT_ALL_EVENTS_IN_TIME_FRAME_WERE_FETCHED() [ResultCode ERROR_NOT_ALL_EVENTS_IN_TIME_FRAME_WERE_FETCHED] 
 #define ResultCode_get_WRITE_CALENDAR_UNDEFINED() [ResultCode WRITE_CALENDAR_UNDEFINED] 
 #define ResultCode_get_READ_CALENDARS_UNDEFINED() [ResultCode READ_CALENDARS_UNDEFINED] 
 #define ResultCode_get_UNKNOWN_CALENDAR_ID() [ResultCode UNKNOWN_CALENDAR_ID] 
 #define ResultCode_get_ERROR_NO_PLACE_FOUND() [ResultCode ERROR_NO_PLACE_FOUND] 
 #define ResultCode_get_PLACE_ALREADY_EXISTS() [ResultCode PLACE_ALREADY_EXISTS] 


#endif
