//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/engine/SensorStateManagerReceiver.java
//

#ifndef _SensorStateManagerReceiver_H_
#define _SensorStateManagerReceiver_H_

@class ReceiverSensorsRequest;
@class SensorType;
@protocol ISensorDataReceiver;

#import "JB.h"

/**
 @brief Created by aeirew on 17/11/2014.
 */
@interface SensorStateManagerReceiver : NSObject {
 @public
  id<ISensorDataReceiver> m_receiver_;
  ReceiverSensorsRequest *m_receiverSensorsRequest_;
}

- (instancetype)initWithISensorDataReceiver:(id<ISensorDataReceiver>)receiver
                 withReceiverSensorsRequest:(ReceiverSensorsRequest *)receiverSensorsRequest;

- (id<ISensorDataReceiver>)getReceiver;

- (boolean)isRegisteredOnSensorTypeWithSensorType:(SensorType *)sensorType;

- (ReceiverSensorsRequest *)getReceiverSensorsRequest;

- (void)setReceiverSensorsRequestWithReceiverSensorsRequest:(ReceiverSensorsRequest *)receiverSensorsRequest;

- (boolean)shouldListenToChangeUpdatesWithSensorType:(SensorType *)sensorType;

- (void)copyAllFieldsTo:(SensorStateManagerReceiver *)other;

@end

__attribute__((always_inline)) inline void SensorStateManagerReceiver_init() {}

//J2OBJC_FIELD_SETTER(SensorStateManagerReceiver, m_receiver_, id<ISensorDataReceiver>)
//J2OBJC_FIELD_SETTER(SensorStateManagerReceiver, m_receiverSensorsRequest_, ReceiverSensorsRequest *)

typedef SensorStateManagerReceiver ComIntelWearablePlatformTimeiqSensorsEngineSensorStateManagerReceiver;

#endif // _SensorStateManagerReceiver_H_
