//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/visitinplacemodule/SensedPlace.java
//

#ifndef _SensedPlace_H_
#define _SensedPlace_H_

@class Coord;
@class IPC;
@class PlaceID;
@class SourceDataType;
@class State;
@class TSOCoordinate;
@class VisitedPlace;
@class WifiScan;
#import "JBArrayList.h"

#import "JB.h"

@interface SensedPlace : NSObject {
 @public
  VisitedPlace *visitedPlace_;
  PlaceID *placeId_;
}

/**
 @brief Constructor
 @param placeId
 */
- (instancetype)initWithPlaceID:(PlaceID *)placeId;

- (instancetype)initWithNSString:(NSString *)identifier
          withSourceDataType:(SourceDataType *)sourceDataType;

- (VisitedPlace *)updateVisitedPlaceWithIPC:(IPC *)ipc
                                   withNSString:(NSString *)manaualId
                                   withNSString:(NSString *)detectedId
                                       withLong:(long64)timestamp
                                   withNSString:(NSString *)interactionId
                                  withState:(State *)state;

- (VisitedPlace *)getVisitedPlace;

- (boolean)hasEnvelpe;

- (NSString *)mkidWithVisitedPlace:(VisitedPlace *)vp;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (long64)visitDistanceToCenterWithCoord:(Coord *)centerCoordinate
                             withDouble:(double)radius;

- (PlaceID *)getPlaceId;

- (TSOCoordinate *)getCenter;

- (long64)distanceToCenterWithCoord:(Coord *)coord;

- (long64)distanceToEnvelopeWithCoord:(Coord *)coord;

- (int)getWifSignaureNum;

- (int)calcMatchingSignatureWithWifiScan:(WifiScan *)wifiScan;

- (int)signatureNumWithJavaUtilList:(ArrayList*)refPointList;

- (int)matchingSignatureWithWifiScan:(WifiScan *)wifiScan
                     withJavaUtilList:(ArrayList*)refPointList;

- (NSString *)getManaualId;

- (NSString *)getDetectedId;

- (void)copyAllFieldsTo:(SensedPlace *)other;

@end

__attribute__((always_inline)) inline void SensedPlace_init() {}

//J2OBJC_FIELD_SETTER(SensedPlace, visitedPlace_, VisitedPlace *)
//J2OBJC_FIELD_SETTER(SensedPlace, placeId_, PlaceID *)

typedef SensedPlace ComIntelWearablePlatformTimeiqPlacesModulesVisitinplacemoduleSensedPlace;

#endif // _SensedPlace_H_
