//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/tso/sdk/common/ioc/SingletonFactory.java
//

#ifndef _SingletonFactory_H_
#define _SingletonFactory_H_

#import "JBClass.h"

#import "JB.h"
#include "AObjectFactory.h"

/**
 @brief Created by gilsharo on 6/16/2015.
 */
@interface SingletonFactory : AObjectFactory {
 @public
  Class m_impType_;
  id m_lock_;
  id m_instance_;
}

- (instancetype)initWithClass :(Class )impType;

- (id)getObject;

- (AObjectFactory *)asSingleton;

- (AObjectFactory *)asMultiInstance;

- (void)copyAllFieldsTo:(SingletonFactory *)other;

@end

__attribute__((always_inline)) inline void SingletonFactory_init() {}

//J2OBJC_FIELD_SETTER(SingletonFactory, m_impType_, Class )
//J2OBJC_FIELD_SETTER(SingletonFactory, m_lock_, id)
//J2OBJC_FIELD_SETTER(SingletonFactory, m_instance_, id)

typedef SingletonFactory ComIntelTsoSdkCommonIocSingletonFactory;

#endif // _SingletonFactory_H_


