//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/visitsmodule/algs/SlidingWindow.java
//

#ifndef _SlidingWindow_H_
#define _SlidingWindow_H_

#import "JBNativeArray.h"

#import "JB.h"

/**
 @brief Created by rcshah on 2/23/2015.
 */
@interface SlidingWindow : NSObject {
 @public
  int numElements_;
  int winSize_;
  IOSDoubleArray *elements_;
  double average_;
}

- (instancetype)init;

- (void)Reset;

- (void)SetWinSizeWithInt:(int)size;

- (void)AddElementWithDouble:(double)val;

- (double)Average;

- (void)copyAllFieldsTo:(SlidingWindow *)other;

@end

__attribute__((always_inline)) inline void SlidingWindow_init() {}

//J2OBJC_FIELD_SETTER(SlidingWindow, elements_, IOSDoubleArray *)

typedef SlidingWindow ComIntelWearablePlatformTimeiqPlacesModulesVisitsmoduleAlgsSlidingWindow;

#endif // _SlidingWindow_H_
