//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/db/SyncSlaveDbs.java
//

#ifndef _SyncSlaveDbs_H_
#define _SyncSlaveDbs_H_

@class DaoType;
#import "JBClass.h"
@class TSOSlaveDBSyncResponse;
@protocol IHttpProviderWrapper;
#import "JBHashSet.h"
#import "JBArrayList.h"

#import "JB.h"

/**
 @brief Created by aeirew on 30/07/2015.
 */
@interface SyncSlaveDbs : NSObject {
 @public
  id<IHttpProviderWrapper> m_httpProvider_;
}

- (instancetype)init;

- (instancetype)initWithIHttpProviderWrapper:(id<IHttpProviderWrapper>)httpProvider;

/**
 @brief Sync Slave DB from server to client and merge with local Repo, method intended to run only on first installation of the app and create a sync state on first installation
 @return true if sync success, false otherwise
 */
- (boolean)syncSlaveDbs;

- (boolean)handleResultWithTSOSlaveDBSyncResponse:(TSOSlaveDBSyncResponse *)result;

- (boolean)convertToObjectsAndCommitToDBWithJavaUtilCollection:(Set*)stringCollection
                                                withDaoType:(DaoType *)daoType;

/**
 @brief try to commit the remote Slave DB objects to the local repo and create a sync state on first installation
 @param classDefinition - the classDefinition DB to commit
 @param resultObjectsFromServer - Slave DB result objects synced from server needed to be persisted to client DB in first installation of the app
 */
- (boolean)commitToDBWithClass :(Class )classDefinition
                  withJavaUtilList:(ArrayList*)resultObjectsFromServer;

/**
 @brief Merge list from remote and local in case local repo already inserted objects while this process is running.
 @param localObjects - the local objects from the local repo
 @param remoteObjects - the result object from the remote repo
 @return the merged set
 */
- (ArrayList*)mergeWithLocalRepoWithJavaUtilCollection:(Set*)localObjects
                                            withJavaUtilList:(ArrayList*)remoteObjects;

- (void)copyAllFieldsTo:(SyncSlaveDbs *)other;

@end

FOUNDATION_EXPORT BOOL SyncSlaveDbs_initialized;
J2OBJC_STATIC_INIT(SyncSlaveDbs)

//J2OBJC_FIELD_SETTER(SyncSlaveDbs, m_httpProvider_, id<IHttpProviderWrapper>)

FOUNDATION_EXPORT NSString *SyncSlaveDbs_TAG_;
J2OBJC_STATIC_FIELD_GETTER(SyncSlaveDbs, TAG_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(SyncSlaveDbs, TAG_, NSString *)

FOUNDATION_EXPORT NSString *SyncSlaveDbs_syncUrl_;
J2OBJC_STATIC_FIELD_GETTER(SyncSlaveDbs, syncUrl_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(SyncSlaveDbs, syncUrl_, NSString *)

typedef SyncSlaveDbs ComIntelWearablePlatformTimeiqCommonDbSyncSlaveDbs;

#endif // _SyncSlaveDbs_H_
