//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/replay/TimeManager.java
//

#ifndef _TimeManager_H_
#define _TimeManager_H_

#import "JB.h"

/**
 @brief Created by orencoh2 on 9/11/14.
 */
@interface TimeManager : NSObject {
}

- (instancetype)init;

@end

__attribute__((always_inline)) inline void TimeManager_init() {}

typedef TimeManager ComIntelWearablePlatformTimeiqSensorsReplayTimeManager;

#endif // _TimeManager_H_
