//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/time/TimeTriggersMemoryStorage.java
//

#ifndef _TimeTriggersMemoryStorage_H_
#define _TimeTriggersMemoryStorage_H_

#import "JBHashSet.h"

#import "JB.h"
#include "ABaseTriggersMemoryStorage.h"
#include "ITimeTriggerStorage.h"

/**
 @brief Created by smoradof on 5/5/2015.
 */
@interface TimeTriggersMemoryStorage : ABaseTriggersMemoryStorage < ITimeTriggerStorage > {
}

- (Set*)getAllTriggersForTimeWithLong:(long64)time;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void TimeTriggersMemoryStorage_init() {}

typedef TimeTriggersMemoryStorage ComIntelWearablePlatformTimeiqTriggersTimeTimeTriggersMemoryStorage;

#endif // _TimeTriggersMemoryStorage_H_
