//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/triggers/TriggerAudit.java
//

#ifndef _TriggerAudit_H_
#define _TriggerAudit_H_

@protocol ITSOTimeUtil;
@protocol ITriggerInner;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by mleib on 27/07/2015.
 */
@interface TriggerAudit : NSObject < IMappable > {
 @public
  id<ITSOTimeUtil> m_timeUtil_;
  HashMap* m_map_;
}

- (instancetype)initWithITSOTimeUtil:(id<ITSOTimeUtil>)timeUtil;

- (instancetype)initWithITriggerInner:(id<ITriggerInner>)triggerInner;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)setRemoved;

- (void)copyAllFieldsTo:(TriggerAudit *)other;

@end

__attribute__((always_inline)) inline void TriggerAudit_init() {}

//J2OBJC_FIELD_SETTER(TriggerAudit, m_timeUtil_, id<ITSOTimeUtil>)
//J2OBJC_FIELD_SETTER(TriggerAudit, m_map_, HashMap*)

FOUNDATION_EXPORT NSString *TriggerAudit_TRIGGER_REMOVED_STATUS_;
J2OBJC_STATIC_FIELD_GETTER(TriggerAudit, TRIGGER_REMOVED_STATUS_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(TriggerAudit, TRIGGER_REMOVED_STATUS_, NSString *)

FOUNDATION_EXPORT NSString *TriggerAudit_TRIGGER_REMOVED_TIME_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(TriggerAudit, TRIGGER_REMOVED_TIME_FIELD_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(TriggerAudit, TRIGGER_REMOVED_TIME_FIELD_, NSString *)

typedef TriggerAudit ComIntelWearablePlatformTimeiqTriggersTriggerAudit;

#endif // _TriggerAudit_H_
