//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/internalApi/ttlAlerts/TSOAlertTriggeredResult.java
//

#ifndef _TSOAlertTriggeredResult_H_
#define _TSOAlertTriggeredResult_H_

@class TSOAlert;
@class TriggeredAlertResultType;
@class TtlRouteData;

#import "JB.h"
#include "TSOAlertResult.h"

/**
 @brief The result object that the ITSOAlertListener gets when an alert was triggered
 */
@interface TSOAlertTriggeredResult : TSOAlertResult {
 @public
  TriggeredAlertResultType *m_resultType_;
  long64 m_requestedReminderTimeDiffFromTtl_;
  long64 m_actualReminderTimeDiffFromTtl_;
  boolean m_isDone_;
}

/**
 @brief The result object that the ITSOAlertListener gets when an alert was triggered
 @param alert the alert that the user has added and to which this alert refers to
 @param resultType the type of the alert that was just triggered
 @param triggeredTime the trigger time for the result
 @param requestedReminderTimeDiffFromTtl the type of the alert that was just triggered
 @param actualReminderTimeDiffFromTtl the actual time difference from the TTL
 @param ttlRouteData the route data that contains the route segments, the arrival time and departure time
 @param isDone
 */
- (instancetype)initWithTSOAlert:(TSOAlert *)alert
withTriggeredAlertResultType:(TriggeredAlertResultType *)resultType
                        withLong:(long64)triggeredTime
                        withLong:(long64)requestedReminderTimeDiffFromTtl
                        withLong:(long64)actualReminderTimeDiffFromTtl
                withTtlRouteData:(TtlRouteData *)ttlRouteData
                     withBoolean:(boolean)isDone;

/**
 @brief Get the type of the alert result that was just triggered
 @return the result type as TriggeredAlertResultType
 */
- (TriggeredAlertResultType *)getAlertResultType;

/**
 @brief Get the requested time difference before the TTL
 @return the requested time difference in milliseconds before the TTL as added to the TSOAlert.TSOAlertBuilder when creating the TSOAlert . <BR> if negative - the alert is before the TTL <BR> if 0 - the alert is at the TTL
 */
- (long64)getRequestedReminderTimeDiffFromTtl;

/**
 @brief Get the actual time difference from the TTL
 @return the actual time difference in milliseconds from the TTL as added to the TSOAlert.TSOAlertBuilder when creating the TSOAlert . <BR> if negative - the alert is before the TTL <BR> if positive - the alert is after the TTL
 */
- (long64)getActualReminderTimeDiffFromTtl;

/**
 @brief Is the alert done (are there no more reminders)
 @return true if the alert is done
 */
- (boolean)isDone;

- (NSString *)description;

- (void)copyAllFieldsTo:(TSOAlertTriggeredResult *)other;

@end

FOUNDATION_EXPORT BOOL TSOAlertTriggeredResult_initialized;
J2OBJC_STATIC_INIT(TSOAlertTriggeredResult)

//J2OBJC_FIELD_SETTER(TSOAlertTriggeredResult, m_resultType_, TriggeredAlertResultType *)

FOUNDATION_EXPORT NSString *TSOAlertTriggeredResult_TAG_;
J2OBJC_STATIC_FIELD_GETTER(TSOAlertTriggeredResult, TAG_, NSString *)

typedef TSOAlertTriggeredResult ComIntelWearablePlatformTimeiqInternalApiTtlAlertsTSOAlertTriggeredResult;

#endif // _TSOAlertTriggeredResult_H_
