//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/events/TSOCompositeEvent.java
//

#ifndef _TSOCompositeEvent_H_
#define _TSOCompositeEvent_H_

@class TSOEventType;
@class TSOPlace;
@class TransportType;
#import "JBArrayList.h"

#import "JB.h"
#include "ITSOEvent.h"

/**
 @brief Created by kyablonk on 05/07/2015.
 */
@interface TSOCompositeEvent : NSObject < ITSOEvent > {
 @public
  id<ITSOEvent> refEvent_;
  ArrayList* events_;
}

- (instancetype)initWithITSOEvent:(id<ITSOEvent>)refEvent;

- (boolean)addWithITSOEvent:(id<ITSOEvent>)newEvent;

- (boolean)canAddEventWithITSOEvent:(id<ITSOEvent>)event;

- (ArrayList*)getEvents;

- (id<ITSOEvent>)getRefEvent;

- (boolean)isEmpty;

- (boolean)removeWithNSString:(NSString *)eventId
          withTSOEventType:(TSOEventType *)eventType;

- (boolean)isSameEventButDifferentTypeWithITSOEvent:(id<ITSOEvent>)event
                                       withITSOEvent:(id<ITSOEvent>)otherEvent;

- (NSString *)getEventId;

- (TSOPlace *)getLocation;

- (long64)getArrivalTime;

- (TSOEventType *)getEventType;

- (long64)getDuration;

- (long64)getEndTime;

- (long64)getLastUpdateTime;

- (void)setLastUpdateTimeWithLong:(long64)time;

- (long64)getGeneralAlarmTime;

- (NSString *)getCalendarId;

- (NSString *)getSubject;

- (NSString *)getDescription;

- (long64)getReminderTimeBeforeTTL;

- (boolean)isDisableTTLAlerts;

- (boolean)isDisableGeneralReminderAlerts;

- (boolean)isAlertOnEventStart;

- (boolean)isAlertOnEventEnd;

- (TransportType *)getPreferredTransportType;

- (NSString *)description;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(TSOCompositeEvent *)other;

@end

__attribute__((always_inline)) inline void TSOCompositeEvent_init() {}

//J2OBJC_FIELD_SETTER(TSOCompositeEvent, refEvent_, id<ITSOEvent>)
//J2OBJC_FIELD_SETTER(TSOCompositeEvent, events_, ArrayList*)

typedef TSOCompositeEvent ComIntelWearablePlatformTimeiqEventsTSOCompositeEvent;

#endif // _TSOCompositeEvent_H_
