//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/protocol/datatypes/location/TSOPosition.java
//

#ifndef _TSOPosition_H_
#define _TSOPosition_H_

@class TSOCoordinate;

#import "JB.h"

/**
 @brief Created by orencoh2 on 18/2/15.
 */
@interface TSOPosition : NSObject {
 @public
  TSOCoordinate *coord_;
  float accuracy_;
  long64 timeStamp_;
}

- (instancetype)initWithTSOCoordinate:(TSOCoordinate *)coordinate
                            withFloat:(float)accuracy
                             withLong:(long64)timeStamp;

- (TSOCoordinate *)getCoordinate;

- (float)getAccuracy;

- (long64)getTimeStamp;

- (void)copyAllFieldsTo:(TSOPosition *)other;

@end

__attribute__((always_inline)) inline void TSOPosition_init() {}

//J2OBJC_FIELD_SETTER(TSOPosition, coord_, TSOCoordinate *)

typedef TSOPosition ComIntelWearablePlatformTimeiqCommonProtocolDatatypesLocationTSOPosition;

#endif // _TSOPosition_H_
