//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/protocol/response/TSOSlaveDBSyncResponse.java
//

#ifndef _TSOSlaveDBSyncResponse_H_
#define _TSOSlaveDBSyncResponse_H_

#import "JBHashtable.h"

#import "JB.h"
#include "TSORetCodeResponse.h"

@interface TSOSlaveDBSyncResponse : TSORetCodeResponse {
 @public
  HashMap* responseObjects_;
}

- (HashMap*)getResponseObjects;

- (void)setResponseObjectsWithJavaUtilMap:(HashMap*)responseObjects;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (instancetype)init;

- (void)copyAllFieldsTo:(TSOSlaveDBSyncResponse *)other;

@end

__attribute__((always_inline)) inline void TSOSlaveDBSyncResponse_init() {}

//J2OBJC_FIELD_SETTER(TSOSlaveDBSyncResponse, responseObjects_, HashMap*)

FOUNDATION_EXPORT NSString *TSOSlaveDBSyncResponse_RESPONSE_OBJECTS_;
J2OBJC_STATIC_FIELD_GETTER(TSOSlaveDBSyncResponse, RESPONSE_OBJECTS_, NSString *)

typedef TSOSlaveDBSyncResponse ComIntelWearablePlatformTimeiqProtocolResponseTSOSlaveDBSyncResponse;

#endif // _TSOSlaveDBSyncResponse_H_
