//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/api/common/auth/TSOUserInfo.java
//

#ifndef _TSOUserInfo_H_
#define _TSOUserInfo_H_

#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"

/**
 @brief Created by orencoh2 on 8/3/15.
 */
@interface TSOUserInfo : NSObject < IMappable > {
 @public
  NSString *m_identifier_;
  NSString *m_userName_;
  NSString *m_password_;
}

/**
 @param identifier
 @param userName
 @param password
 */
- (instancetype)initWithNSString:(NSString *)identifier
                    withNSString:(NSString *)userName
                    withNSString:(NSString *)password;

- (instancetype)initWithNSString:(NSString *)identifier
                    withNSString:(NSString *)userName;

- (NSString *)getIdentifier;

- (NSString *)getUserName;

- (NSString *)getPassword;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(TSOUserInfo *)other;

@end

__attribute__((always_inline)) inline void TSOUserInfo_init() {}

//J2OBJC_FIELD_SETTER(TSOUserInfo, m_identifier_, NSString *)
//J2OBJC_FIELD_SETTER(TSOUserInfo, m_userName_, NSString *)
//J2OBJC_FIELD_SETTER(TSOUserInfo, m_password_, NSString *)

FOUNDATION_EXPORT NSString *TSOUserInfo_IDENTIFIER_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(TSOUserInfo, IDENTIFIER_FIELD_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(TSOUserInfo, IDENTIFIER_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *TSOUserInfo_USERNAME_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(TSOUserInfo, USERNAME_FIELD_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(TSOUserInfo, USERNAME_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *TSOUserInfo_PASSWORD_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(TSOUserInfo, PASSWORD_FIELD_, NSString *)
//J2OBJC_STATIC_FIELD_SETTER(TSOUserInfo, PASSWORD_FIELD_, NSString *)

typedef TSOUserInfo ComIntelWearablePlatformTimeiqApiCommonAuthTSOUserInfo;

#endif // _TSOUserInfo_H_
