//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/platform/android/factory/TtlAlertsProviderFactoryInitializer.java
//

#ifndef _TtlAlertsProviderFactoryInitializer_H_
#define _TtlAlertsProviderFactoryInitializer_H_

@class ClassFactory;

#import "JB.h"

/**
 @brief Created by smoradof on 1/19/15.
 */
@interface TtlAlertsProviderFactoryInitializer : NSObject {
}

+ (void)initFactoryGeneralWithClassFactory:(ClassFactory *)classFactory OBJC_METHOD_FAMILY_NONE;

+ (void)initFactoryGeneral4TestingWithClassFactory:(ClassFactory *)classFactory OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void TtlAlertsProviderFactoryInitializer_init() {}

typedef TtlAlertsProviderFactoryInitializer ComIntelWearablePlatformTimeiqPlatformAndroidFactoryTtlAlertsProviderFactoryInitializer;

#endif // _TtlAlertsProviderFactoryInitializer_H_
