//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/common/protocol/datatypes/calendar/UniqueCalendarEvent.java
//

#ifndef _UniqueCalendarEvent_H_
#define _UniqueCalendarEvent_H_

@class AttendeeMeetingData;
#import "NSNumber+JavaAPI.h"
#import "NSNumber+JavaAPI.h"
#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief DO NOT DELETE THE EQUALS & HASH CODE METHODS!!!!!
 */
@interface UniqueCalendarEvent : NSObject < IMappable > {
 @public
  NSString *subject_;
  NSString *organizerEmail_;
  JBBoolean *organizer_;
  Long *startDate_;
  Long *endDate_;
  NSString *locationField_;
  ArrayList* attendees_;
  JBBoolean *allDayEvent_;
  JBBoolean *recurrent_;
  JBBoolean *debug_;
  NSString *primaryKey_;
}

/**
 @brief Constructor
 @param startTime
 @param endTime
 @param locationField
 */
- (instancetype)initWithNSString:(NSString *)subject
                withLong:(Long *)startTime
                withLong:(Long *)endTime
                    withNSString:(NSString *)organizerEmail
                    withNSString:(NSString *)locationField
                withJavaUtilList:(ArrayList*)attendees
             withJBBoolean:(JBBoolean *)organizer
             withJBBoolean:(JBBoolean *)allDayEvent
             withJBBoolean:(JBBoolean *)recurrent
             withJBBoolean:(JBBoolean *)debug;

- (instancetype)initWithNSString:(NSString *)subject
                withLong:(Long *)startTime
                withLong:(Long *)endTime
                    withNSString:(NSString *)organizerEmail
                    withNSString:(NSString *)locationField
                withJavaUtilList:(ArrayList*)attendees
             withJBBoolean:(JBBoolean *)organizer
             withJBBoolean:(JBBoolean *)allDayEvent
             withJBBoolean:(JBBoolean *)recurrent;

- (instancetype)init;

- (NSString *)description;

- (NSUInteger)hash;

- (boolean)isEqual:(id)obj;

- (ArrayList*)getEmailsListWithJavaUtilList:(ArrayList*)attendees2;

- (Long *)getStartTime;

- (Long *)getEndDate;

- (NSString *)getOrganizerEmail;

- (ArrayList*)getAttendees;

- (AttendeeMeetingData *)getAttendeeByEmailWithNSString:(NSString *)email;

- (AttendeeMeetingData *)getFirstAttendeeWithEventID;

- (JBBoolean *)setAtendeeEventIdWithNSString:(NSString *)email
                                      withNSString:(NSString *)EventId;

- (NSString *)getLocationField;

- (Long *)getStartDate;

- (void)setStartDateWithLong:(Long *)startDate;

- (void)setEndDateWithLong:(Long *)endDate;

- (void)setLocationFieldWithNSString:(NSString *)locationField;

- (JBBoolean *)isOrganizer;

- (NSString *)getSubject;

- (void)setSubjectWithNSString:(NSString *)subject;

- (void)setOrganizerEmailWithNSString:(NSString *)organizerEmail;

- (void)setOrganizerWithJBBoolean:(JBBoolean *)organizer;

- (void)setAttendeesWithJavaUtilList:(ArrayList*)attendees;

- (JBBoolean *)getAllDayEvent;

- (void)setAllDayEventWithJBBoolean:(JBBoolean *)allDayEvent;

- (JBBoolean *)getRecurrent;

- (void)setRecurrentWithJBBoolean:(JBBoolean *)recurrent;

- (JBBoolean *)getDebug;

- (void)setDebugWithJBBoolean:(JBBoolean *)debug;

- (boolean)isValidEvent;

- (NSString *)getPrimaryKey;

- (void)setPrimaryKeyWithNSString:(NSString *)primaryKey;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (void)copyAllFieldsTo:(UniqueCalendarEvent *)other;

@end

__attribute__((always_inline)) inline void UniqueCalendarEvent_init() {}

//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, subject_, NSString *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, organizerEmail_, NSString *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, organizer_, JBBoolean *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, startDate_, Long *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, endDate_, Long *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, locationField_, NSString *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, attendees_, ArrayList*)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, allDayEvent_, JBBoolean *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, recurrent_, JBBoolean *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, debug_, JBBoolean *)
//J2OBJC_FIELD_SETTER(UniqueCalendarEvent, primaryKey_, NSString *)

typedef UniqueCalendarEvent ComIntelWearablePlatformTimeiqCommonProtocolDatatypesCalendarUniqueCalendarEvent;

#endif // _UniqueCalendarEvent_H_
