//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/audit/UserStateAuditManager.java
//

#ifndef _UserStateAuditManager_H_
#define _UserStateAuditManager_H_

@class UserState;
@class UserStateChanges;
@protocol IAuditManager;
@protocol IUserStateManagerInternal;

#import "JB.h"
#include "IUserStateChangeListener.h"
#include "IUserStateAuditManager.h"

/**
 @brief Created by mleib on 23/07/2015.
 */
@interface UserStateAuditManager : NSObject < IUserStateAuditManager, IUserStateChangeListener > {
 @public
  id<IUserStateManagerInternal> m_userStateManager_;
  id<IAuditManager> m_auditManager_;
}

- (instancetype)init;

- (void)startAuditWithIUserStateManagerInternal:(id<IUserStateManagerInternal>)userStateManager;

- (void)stopAudit;

- (void)onStateChangedWithUserState:(UserState *)oldState
                      withUserState:(UserState *)newState
               withUserStateChanges:(UserStateChanges *)changes;

- (void)copyAllFieldsTo:(UserStateAuditManager *)other;

@end

__attribute__((always_inline)) inline void UserStateAuditManager_init() {}

//J2OBJC_FIELD_SETTER(UserStateAuditManager, m_userStateManager_, id<IUserStateManagerInternal>)
//J2OBJC_FIELD_SETTER(UserStateAuditManager, m_auditManager_, id<IAuditManager>)

typedef UserStateAuditManager ComIntelWearablePlatformTimeiqUserstateAuditUserStateAuditManager;

#endif // _UserStateAuditManager_H_
