//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/audit/UserStateAuditManagerStub.java
//

#ifndef _UserStateAuditManagerStub_H_
#define _UserStateAuditManagerStub_H_

@protocol IUserStateManagerModule;

#import "JB.h"
#import "IUserStateAuditManager.h"

/**
 @brief Created by mleib on 23/07/2015.
 */
@interface UserStateAuditManagerStub : NSObject < IUserStateAuditManager > {
}

- (instancetype)init;

- (void)startAuditWithIUserStateManagerModule:(id<IUserStateManagerModule>)userStateManager;

- (void)stopAudit;

@end

__attribute__((always_inline)) inline void UserStateAuditManagerStub_init() {}

typedef UserStateAuditManagerStub ComIntelWearablePlatformTimeiqUserstateAuditUserStateAuditManagerStub;

#endif // _UserStateAuditManagerStub_H_
