//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/audit/UserStateDataVisitsAudit.java
//

#ifndef _UserStateDataVisitsAudit_H_
#define _UserStateDataVisitsAudit_H_

@class UserStateData;
@class VisitedPlaces;
#import "JBHashtable.h"

#import "JB.h"
#include "IMappable.h"

/**
 @brief Created by mleib on 23/07/2015.
 */
@interface UserStateDataVisitsAudit : NSObject < IMappable > {
 @public
  VisitedPlaces *m_data_;
  long64 m_timeStamp_;
}

/**
 @brief Constructor
 */
- (instancetype)init;

/**
 @brief Constructor
 @param visits
 */
- (instancetype)initWithUserStateData:(UserStateData *)visits;

- (VisitedPlaces *)getVisits;

- (long64)getTimeStamp;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)map OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (NSString *)description;

- (void)copyAllFieldsTo:(UserStateDataVisitsAudit *)other;

@end

__attribute__((always_inline)) inline void UserStateDataVisitsAudit_init() {}

//J2OBJC_FIELD_SETTER(UserStateDataVisitsAudit, m_data_, VisitedPlaces *)

FOUNDATION_EXPORT NSString *UserStateDataVisitsAudit_DATA_;
J2OBJC_STATIC_FIELD_GETTER(UserStateDataVisitsAudit, DATA_, NSString *)

FOUNDATION_EXPORT NSString *UserStateDataVisitsAudit_TIME_STAMP_;
J2OBJC_STATIC_FIELD_GETTER(UserStateDataVisitsAudit, TIME_STAMP_, NSString *)

typedef UserStateDataVisitsAudit ComIntelWearablePlatformTimeiqUserstateAuditUserStateDataVisitsAudit;

#endif // _UserStateDataVisitsAudit_H_
