//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/userstate/UserStateManagerImp.java
//

#ifndef _UserStateManagerImp_H_
#define _UserStateManagerImp_H_

@class ResultData;
@class UserState;
@class UserStateChanges;
@protocol IApiUsageUtil;
@protocol IUserStateFilter;

#import "JB.h"
#include "IUserStateChangeListener.h"
#include "BaseUserStateChangeProvider.h"
#include "IUserStateManagerInternal.h"

/**
 @brief Created by gilsharo on 5/12/2015.
 */
@interface UserStateManagerImp : BaseUserStateChangeProvider < IUserStateManagerInternal, IUserStateChangeListener > {
 @public
  id<IUserStateFilter> m_stateFilter_;
  id<IApiUsageUtil> m_apiUsageUtil_;
}

- (instancetype)init;

- (instancetype)initWithIUserStateFilter:(id<IUserStateFilter>)stateFilter
                       withIApiUsageUtil:(id<IApiUsageUtil>)apiUsageUtil;

- (void)onStateChangedWithUserState:(UserState *)oldState
                      withUserState:(UserState *)newState
               withUserStateChanges:(UserStateChanges *)changes;

- (ResultData *)registerForStateChangesWithIUserStateChangeListener:(id<IUserStateChangeListener>)listener;

- (void)unregisterForStateChangesWithIUserStateChangeListener:(id<IUserStateChangeListener>)listener;

- (ResultData *)getCurrentState;

- (void)copyAllFieldsTo:(UserStateManagerImp *)other;

@end

__attribute__((always_inline)) inline void UserStateManagerImp_init() {}

//J2OBJC_FIELD_SETTER(UserStateManagerImp, m_stateFilter_, id<IUserStateFilter>)
//J2OBJC_FIELD_SETTER(UserStateManagerImp, m_apiUsageUtil_, id<IApiUsageUtil>)

typedef UserStateManagerImp ComIntelWearablePlatformTimeiqUserstateUserStateManagerImp;

#endif // _UserStateManagerImp_H_
