//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/sensors/datatypes/wifi/WifiFingerPrintCollection.java
//

#ifndef _WifiFingerPrintCollection_H_
#define _WifiFingerPrintCollection_H_

#import "JBArrayList.h"
#import "JBHashtable.h"

#import "JB.h"
#import "IMappable.h"

/**
 @brief Created by eleuchte on 11/23/2014.
 */
@interface WifiFingerPrintCollection : NSObject < IMappable > {
 @public
  NSString *ssid_;
  ArrayList* capabilities_;
  ArrayList* associatedWifiSpots_;
}

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(ArrayList*)capabilities
                        withNSString:(NSString *)ssid
                    withJavaUtilList:(ArrayList*)associatedWifiSpots;

- (ArrayList*)getCapabilities;

- (NSString *)getSSID;

- (ArrayList*)getAssociatedWifiSpots;

- (void)initObjectFromMapWithJavaUtilMap:(HashMap*)stringObjectMap OBJC_METHOD_FAMILY_NONE;

- (HashMap*)objectToMap;

- (boolean)isEqual:(id)o;

- (NSUInteger)hash;

- (void)copyAllFieldsTo:(WifiFingerPrintCollection *)other;

@end

__attribute__((always_inline)) inline void WifiFingerPrintCollection_init() {}

//J2OBJC_FIELD_SETTER(WifiFingerPrintCollection, ssid_, NSString *)
//J2OBJC_FIELD_SETTER(WifiFingerPrintCollection, capabilities_, ArrayList*)
//J2OBJC_FIELD_SETTER(WifiFingerPrintCollection, associatedWifiSpots_, ArrayList*)

FOUNDATION_EXPORT NSString *WifiFingerPrintCollection_SSID_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(WifiFingerPrintCollection, SSID_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *WifiFingerPrintCollection_CAPABILITIES_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(WifiFingerPrintCollection, CAPABILITIES_FIELD_, NSString *)

FOUNDATION_EXPORT NSString *WifiFingerPrintCollection_ASSOCIATED_WIFI_SPOTS_FIELD_;
J2OBJC_STATIC_FIELD_GETTER(WifiFingerPrintCollection, ASSOCIATED_WIFI_SPOTS_FIELD_, NSString *)

typedef WifiFingerPrintCollection ComIntelWearablePlatformTimeiqSensorsDatatypesWifiWifiFingerPrintCollection;

#endif // _WifiFingerPrintCollection_H_
