//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/places/modules/visitsmodule/common/WifiScan.java
//

#ifndef _WifiScan_H_
#define _WifiScan_H_

@class WifiSource;
#import "JBArrayList.h"

#import "JB.h"

@interface WifiScan : NSObject {
 @public
  long64 timeStamp_;
  ArrayList* sources_;
}

- (instancetype)initWithJavaUtilList:(ArrayList*)wifiFingerPrintList
                            withLong:(long64)timeStamp;

- (instancetype)init;

- (instancetype)initWithLong:(long64)timeStamp;

- (ArrayList*)getSources;

- (void)setSourceWithWifiSource:(WifiSource *)wifiSource;

- (long64)getTimeStamp;

- (void)copyAllFieldsTo:(WifiScan *)other;

@end

__attribute__((always_inline)) inline void WifiScan_init() {}

//J2OBJC_FIELD_SETTER(WifiScan, sources_, ArrayList*)

FOUNDATION_EXPORT NSString *WifiScan_ZERO_BSSID_;
J2OBJC_STATIC_FIELD_GETTER(WifiScan, ZERO_BSSID_, NSString *)

typedef WifiScan ComIntelWearablePlatformTimeiqPlacesModulesVisitsmoduleCommonWifiScan;

#endif // _WifiScan_H_
