//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: //com/intel/wearable/platform/timeiq/dbobjects/places/cluster/XY.java
//

#ifndef _XY_H_
#define _XY_H_

#import "JB.h"

@interface XY : NSObject {
 @public
  double x_;
  double y_;
}

- (instancetype)initWithDouble:(double)x
                    withDouble:(double)y;

- (double)distanceToWithXY:(XY *)other;

- (double)getX;

- (double)getY;

- (NSString *)description;

- (void)copyAllFieldsTo:(XY *)other;

@end

__attribute__((always_inline)) inline void XY_init() {}

typedef XY ComIntelWearablePlatformTimeiqDbobjectsPlacesClusterXY;

#endif // _XY_H_
